### ISSUE TITLE
case中检查项的预期值为null时，执行后报ValidationError

### ISSUE THREAD

**Issue by wangkangreg** [HttpRunner/HttpRunner#100]
使用har2case把fiddler导出的har转换为case后，部分验证项的预期值为null，如
`        {
          "eq": [
            "content.trace",
            null
          ]
        },`
此时执行用例后会报错，如下

Traceback (most recent call last):
httprunner.exception.ValidationError:
        check item name: content.trace;
        check item value: None (NoneType);
        comparator: equals;
        expected value:  (str).

**Comment by debugtalk** [comment]
@wangkangreg 确定是个bug，已经修复了，感谢反馈。
