### ISSUE TITLE
Jenkins上执行hrun命令出错：missing dependency tool: black install black manually and try again: $ pip install black

### ISSUE THREAD

**Issue by Jamesparagon** [httprunner/httprunner#1007]
## 问题描述

请对遇到的 bug 进行简要描述。
Jenkins执行构建命令 hrun xx.py 日志如下：
开始执行任务
/var/lib/jenkins/workspace/cos_qa_tools/cos_api_test/testsuites/cos_old/login_test.py
上面是执行的case路径，下面执行任务
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: black in /usr/local/python3/lib/python3.7/site-packages (20.8b1)
Requirement already satisfied: regex>=2020.1.8 in /usr/local/python3/lib/python3.7/site-packages (from black) (2020.7.14)
Requirement already satisfied: click>=7.1.2 in /usr/local/python3/lib/python3.7/site-packages (from black) (7.1.2)
Requirement already satisfied: appdirs in /usr/local/python3/lib/python3.7/site-packages (from black) (1.4.4)
Requirement already satisfied: typed-ast>=1.4.0 in /usr/local/python3/lib/python3.7/site-packages (from black) (1.4.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/python3/lib/python3.7/site-packages (from black) (0.4.3)
Requirement already satisfied: pathspec<1,>=0.6 in /usr/local/python3/lib/python3.7/site-packages (from black) (0.8.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/python3/lib/python3.7/site-packages (from black) (3.7.4.3)
Requirement already satisfied: toml>=0.10.1 in /usr/local/python3/lib/python3.7/site-packages (from black) (0.10.1)
2020-09-11 15:16:19.118 | INFO     | httprunner.make:__make:512 - make path: /var/lib/jenkins/workspace/cos_qa_tools/cos_api_test/testsuites/cos_old/login_test.py
2020-09-11 15:16:19.119 | INFO     | httprunner.make:format_pytest_with_black:170 - format pytest cases with black ...
2020-09-11 15:16:19.126 | ERROR    | httprunner.make:format_pytest_with_black:189 - 
missing dependency tool: black
install black manually and try again:
$ pip install black

Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
结束任务
Finished: 
## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. centos]
 - Python 版本 [e.g. 3.7.5]
 - HttpRunner 版本 [e.g. 3.1.4]
 - **设备 ID**: [e.g. 90520738788868]

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

```bash
>>> import uuid; print(uuid.getnode())
190070690681122
```

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

2020-09-11 15:16:19.118 | INFO     | httprunner.make:__make:512 - make path: /var/lib/jenkins/workspace/cos_qa_tools/cos_api_test/testsuites/cos_old/login_test.py
2020-09-11 15:16:19.119 | INFO     | httprunner.make:format_pytest_with_black:170 - format pytest cases with black ...
2020-09-11 15:16:19.126 | ERROR    | httprunner.make:format_pytest_with_black:189 - 
missing dependency tool: black
install black manually and try again:
$ pip install black

**Comment by Jamesparagon** [comment]
![image](https://user-images.githubusercontent.com/13159966/92894198-f565c200-f44c-11ea-9642-1ff3d9b1d086.png)
这个python_path指的是哪里呢

**Comment by Jamesparagon** [comment]
问题解决了，是环境的问题，不是代码问题

**Comment by JK-yan** [comment]
> 问题解决了，是环境的问题，不是代码问题

所以环境问题 具体是啥问题？我现在也遇到这个了
