### ISSUE TITLE
支持分布式执行吗？

### ISSUE THREAD

**Issue by idibmzjm** [httprunner/httprunner#1024]
## 背景描述

> 重点描述遇到的问题：在什么场景下，HttpRunner 当前的功能特性不能（很好地）实现需求。

## 期望的功能特性

> 期望 HttpRunner 实现怎样的功能特性。

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。

**Comment by Deacone** [comment]
我也急需这个功能呢

**Comment by Deacone** [comment]
pytest本身支持分布式，但是加入debugtalk.py 这个文件就会出问题

**Comment by idibmzjm** [comment]
咨询个问题，httprunner V3版本中 使用extract关键字提取变量供后续的用例使用。

现在是执行多个文件，第一个测试文件中提取了变量a，为什么也可以在第二个测试文件中继续使用：
我理解的是 __session_variables作为httprunner类的类变量，pytest在执行每个test文件时，都会初始化子类，既然是初始化子类
__session_variables默认都为{}才对，为什么在执行第二个测试文件时，__session_variables已经存入了从第一个测试文件中提取的变量

**Comment by debugtalk** [comment]
在压测中会支持分布式执行，可关注这个 issue：https://github.com/httprunner/httprunner/issues/1193
