### ISSUE TITLE
__session_variables，是如何做到前一个用例提取的值，在下一个用例中继续使用的

### ISSUE THREAD

**Issue by idibmzjm** [httprunner/httprunner#1027]
## 背景描述
V3版本后，使用pytest执行用例时，都会实例化HttpRunner类的子类来执行test_start()方法;
__session_variables作为父类（HttpRunner）的类变量，为什么每次子类实例化后，__session_variables还可以保留上一个子类extract的结果呢，不是很理解；不应该每次实例化子类的时候，__session_variables都是{}吗？

**Comment by bingosong17** [comment]
同样问题，关注

**Comment by debugtalk** [comment]
在最新的 v3 版本中已经不存在该问题
