### ISSUE TITLE
post请求数据格式的支持问题

### ISSUE THREAD

**Issue by jeo1988** [HttpRunner/HttpRunner#103]
项目现在在post请求时支持的data参数好像只有json类型的，对于multpart/form-data格式的参数不支持，尤其是还需要上传文件的时候，不知道是否我没有用明白，自己在项目里面打了个烂补丁，可以用了，后面是否可以优化支持下，谢谢

**Comment by debugtalk** [comment]
@jeo1988 HttpRunner 底层完全基于 requests，参数名称也完全相同，所以你如何采用 requests 请求 multpart/form-data，就如何使用 HttpRunner。

甚至图片上传功能也是可以实现的 #23。

你要是还不明白，你可以将你上传的代码贴出来，我给你演示下。

**Comment by jeo1988** [comment]
@debugtalk 看了下你链接的之前的问题，我文件上传也是用的那个库，但是现在就是formdata数据总是提示无法解析
`- test:
    name: 【申诉 】正常场景-->201
    request:
        url: /devices/$guest_Id/appeal
        data: {"id_card_no": $ID, "phone_no": $phone, "code": $Code, "id_card_image": $ID_IMAGE, "name": $uname}
    validators:
      - {"check": "status_code", "comparator": "eq", "expected": 201}
    teardown:
      - ${delete_appeal_sms($phone)}`
如上代码片段data在接口文档中明确要求是multipart/form-data格式的，id_card_image就是要上传的图片，我在runner源代码中加了一段代码就能运行了，加的代码片段如下（第一行是源代码，后面是我加的，因为我调试的时候看到parsed_reqeuest是空的）：
`parsed_request = self.init_config(testcase, level="testcase")
if 'headers' in parsed_request.keys() and 'Content-Type' in parsed_request['headers'].keys() and 'multipart/form-data' == parsed_request['headers']['Content-Type']:
    m = MultipartEncoder(fields=parsed_request['data'])
    parsed_request['headers']['Content-Type'] = m.content_type
    parsed_request['data'] = m`
你看下是否是我data的格式写的不对，尝试了另外两种写法还是不能运行，谢谢
在贴一下response_content信息吧，里面有错误提示
response_content': '{"timestamp":1519646687829,"status":500,"error":"Internal Server Error","exception":"org.springframework.web.multipart.MultipartException","message":"**Could not parse multipart servlet request**; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",

**Comment by yanghuo662** [comment]
没有写Content-Type吧

**Comment by jeo1988** [comment]
@yanghuo662 写了
