### ISSUE TITLE
2.x 传入标准的测试用例结构体是什么样的？

### ISSUE THREAD

**Issue by lijuelijue** [httprunner/httprunner#1039]
官方网站（https://v2.httprunner.org/development/dev-api/）的2.x 传入标准的测试用例结构体无法使用，对比了一下跟1.x是一模一样。谁能否提供一下2.x 传入标准的测试用例结构体

**Comment by hazer491** [comment]
你可以参考下面：
https://github.com/httprunner/httprunner/issues/736
https://github.com/httprunner/httprunner/issues/808

**Comment by lijuelijue** [comment]
我早就解决了，谢谢了。
