### ISSUE TITLE
不兼容python3.9

### ISSUE THREAD

**Issue by laolyu** [httprunner/httprunner#1055]
## Describe the bug

httprunner和har2case都存在不兼容python3.9,报错如下
File "....\Python39\lib\typing.py", line 688, in __getattr__
    raise AttributeError(attr)
AttributeError: __args__

## Versions
 - OS: [Windows]
 - Python [3.9.1]
 - HttpRunner [3.1.4]
- **Device ID**: [193866608796714]
## Traceback

File "....\Python39\lib\typing.py", line 688, in __getattr__
    raise AttributeError(attr)
AttributeError: __args__

**Comment by Wc-lab** [comment]
![image](https://user-images.githubusercontent.com/75770537/149742078-c8246744-cbd1-4c8d-99e0-1c1f71551fc6.png)
我的3.9没问题呀

**Comment by debugtalk** [comment]
@laolyu 在 github actions 已增加 3.9/3.10 的持续集成测试。
