### ISSUE TITLE
3.1.4版本，设置断言，我的实际值是一个函数，这个函数返回一个字符串，但是断言一直失败，我理解如果我用的是函数，就直接把check_item赋值给check_value就好啦，为什么还要用check_item去我的应答里比对哈？最后转换出来是None

### ISSUE THREAD

**Issue by fangxiaoyaner** [httprunner/httprunner#1056]
断言：
"validate": [
        {
          "eq":[
            "${checkpricejsonretmsg(DSCSTORAGE, $request, $response, DSC仓储询价-全量阶梯计价-结算周期阶梯-无规格)}",
            "success"
          ]
        }
      ]
checkpricejsonretmsg函数：
def checkpricejsonretmsg(merchant,request = None, response = None,pricename = None):
    """
    验证询价金额，失败返回错误信息
    """
    return str("success")

错误：
2021-01-17 14:25:30.348 | ERROR    | httprunner.response:validate:292 - assert success equal success(str)	==> fail
check_item: success
check_value: None(NoneType)
assert_method: equal
expect_value: success(str)

我自己加的打印：
8888
"success"
success
55555
success
str
True
111
666
success
str

源码：
print(check_item)
            if "$" in check_item:
                # check_item is variable or function

                print('77777')
                print(check_item)
                print(variables_mapping)
                print(functions_mapping)

                check_item = parse_data(
                    check_item, variables_mapping, functions_mapping
                )
                print('8888')
                print(check_item)

                check_item = parse_string_value(check_item)
                print(check_item)

            #check_item = ''
            print('55555')
            print(check_item)
            print(type(check_item).__name__)
            print(isinstance(check_item, Text))
            if check_item and isinstance(check_item, Text):
                print('111')
                check_value = self._search_jmespath(check_item)
                print('222')
                print(check_value)
            else:
                print('333')
                # variable or function evaluation result is "" or not text
                check_value = check_item
                print('444')
                print(check_value)

**Comment by jeremy8250** [comment]
我也遇到了同样的问题，在拿数据库str类型的数据做断言时check_value提示NoneType，int类型数据就没这个问题。我的解决方案是临时在check_item下加一个判断，如果search_jmespath返回类型是None，则直接把check_item赋值给check_value，完美解决。

**Comment by whitexie** [comment]
@debugtalk  这应该是一个bug， 我本地在 `tests/response_test.py` 中的 `test_validate_functions`用例中添加了一个示例，单元测试便无法通过

```python
    def test_validate_functions(self):
        variables_mapping = {"index": 1}
        functions_mapping = {"get_num": lambda x: x}
        self.resp_obj.validate([
            {"eq": ["${get_num(a)}", 'a']}],
            variables_mapping=variables_mapping,
            functions_mapping=functions_mapping,
        )
```

log：
```
FAILED           [100%]
2021-04-24 00:53:12.008 | INFO     | httprunner.response:validate:246 - assert 0 equal 0(int)	==> pass
2021-04-24 00:53:12.008 | INFO     | httprunner.response:validate:246 - assert 1 equal 1(int)	==> pass
2021-04-24 00:53:12.009 | ERROR    | httprunner.response:validate:263 - assert a equal a(str)	==> fail
check_item: a
check_value: None(NoneType)
assert_method: equal
expect_value: a(str)
```


解决方法：

将`response.py` 中 212行

```python
if check_item and isinstance(check_item, Text):
  check_value = self._search_jmespath(check_item)
```

修改为

```python
resp_obj_meta_keys = ['status_code', 'headers', 'cookies', 'body']
if check_item and isinstance(check_item, Text) and check_item.split('.')[0] in resp_obj_meta_keys:
  check_value = self._search_jmespath(check_item)
```
