### ISSUE TITLE
无法在用例中通过转义字符${}调用python的内置函数么，比如：${len(str)}

### ISSUE THREAD

**Issue by wushenghang** [HttpRunner/HttpRunner#106]

**Comment by debugtalk** [comment]
这个建议不错，后续加上。

**Comment by wushenghang** [comment]
更新了新的报告模板，新的报告比之前漂亮了许多呢！而且执行多个用例文件的时候终于不会生成多个报告了
还有，建议单个报告内以yml文件为单位将结果切割出来，这样跑多个用例的时候日志看起来会清晰点

**Comment by debugtalk** [comment]
@wushenghang 已经支持调用内置函数了。

报告按文件切分那个，也有计划做。

**Comment by wushenghang** [comment]
看到了，赞！
