### ISSUE TITLE
testsuite的testcase配置里填写了parameters不起作用

### ISSUE THREAD

**Issue by littlwish** [httprunner/httprunner#1065]
## 背景描述
在testsuite.yaml中配置了parameters参数化，
可是hmake生成的pytest文件中，没有parameters

## 期望的功能特性

能够支持使testsuite支持parameters参数化

## 环境

windows10
python：3.7.5
httprunner：3.1.4

**Comment by whitexie** [comment]
已经支持parameters参数化了， 可以看下这个示例
https://github.com/httprunner/httprunner/blob/master/examples/postman_echo/request_methods/request_with_parameters.yml

**Comment by littlwish** [comment]
testcase里的parameters参数化可以，但是testsuite里的parameters参数化不行
