### ISSUE TITLE
用例使用setup_hook或teardown_hook需要返回值保存到变量时，生成的pytest python错误

### ISSUE THREAD

**Issue by vankillua** [httprunner/httprunner#1068]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.6
 - HttpRunner 版本 3.1.4

获取方式：

`httprunner/make.py`文件中的`make_teststep_chain_style`函数，具体问题如下图：

![image](https://user-images.githubusercontent.com/20939027/108808935-bc786e80-75e2-11eb-90cd-796ecb82d61d.png)

**Comment by debugtalk** [comment]
@vankillua 感谢反馈，下次麻烦直接提 PR 哈

**Comment by vankillua** [comment]
> @vankillua 感谢反馈，下次麻烦直接提 PR 哈

好的
