### ISSUE TITLE
用Charles导出har文件后，用har2case转换yml文件

### ISSUE THREAD

**Issue by testwangchao** [HttpRunner/HttpRunner#108]
转为yml文件会出现!!python/unicode
\-   config:
        headers:
            User-Agent: !!python/unicode 'neonking/1.0.0 (iPhone; iOS 11.2.6; Scale/3.00)'
        name: testset description
        variables: []
转json格式是没问题的

**Comment by debugtalk** [comment]
这是 PyYAML 的特性，在Python 2 下非ASCII 编码会有这样的问题。我这边没法修改的。
