### ISSUE TITLE
目前validate是否支持判断某个字段是否存在的方法

### ISSUE THREAD

**Issue by imliyachao** [HttpRunner/HttpRunner#111]
目前validate是否支持判断某个字段是否存在的方法，比如某些字段是随着后台配置改变的或者动态改变的，所以断言这些字段时，只能去断言这个字段存在或者不为空就可以，貌似目前没有支持这种断言方式

**Comment by debugtalk** [comment]
针对这个问题：
1、通常 validate 应该选择确定的字段；
2、支持自定义校验方法。
