### ISSUE TITLE
locust性能测试报错RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by JacobHZ** [HttpRunner/HttpRunner#112]
使用locusts -f demo_login.json，开始运行性能测试时会报错：RecursionError: maximum recursion depth exceeded while calling a Python object

我尝试用源生locust运行项目根目录下已生成的locustfile.py：locust -f locust.py，能够正常运行。

**Comment by debugtalk** [comment]
@JacobHZ 我用你的文件跑了下，没有遇到你说的问题，不知道是不是因为你的被测系统我这边访问不了的原因。

![image](https://user-images.githubusercontent.com/3657070/37271071-620dd8c8-260c-11e8-991d-32cee2b3e133.png)

**Comment by JacobHZ** [comment]
@debugtalk 

1. `locusts -f demo_login.json`，这一步没问题，http://localhost:8089也能正常打开
2. 在web页面输入需要模拟的用户数量，点击“start”之后报错，无法进行正常的测试

**Comment by debugtalk** [comment]
@JacobHZ 我这边试了下，在 Mac 系统下正常，在 Linux 下会出现 RecursionError 的问题；你那边是什么系统？

**Comment by JacobHZ** [comment]
@debugtalk 那就比较奇怪，我这边macOS High Sierra 10.13.3，python版本3.6.0

**Comment by guohongxing** [comment]
我今天也同样遇到了这个问题，目前拿locust -f 文件测试OK

**Comment by searchbb** [comment]
@debugtalk 帮你定位问题了，典型的Please monkey-patch earlier问题，网上一搜一堆解释，这个问题只有在url里面是https的时候发生，locust本身引用的顺序在新版本里是对的，不过你的locusts在Cli里面就引用了case什么的结果会先import request，导致引用到urllib，导致了这个错误，我已经在两个mac重现了，看你的截图，你只是用hrun测试了一下那个https，但是没有用locusts，你看一下吧，虽然我定位问题了，但是你的代码我不太熟悉，希望你能尽快修正，我这里有的很多接口都是https的呢

➜  HttpRunner git:(dev) ✗ pipenv run python main-debug.py locusts -f /Users/searchbb/Desktop/Lefit/Test/TestGit/AutoScript/Payment/lefit-balance_payment.yml
/Users/searchbb/.local/share/virtualenvs/HttpRunner-_3-s9PUt/lib/python3.6/site-packages/locust/core.py:18: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (/Users/searchbb/.local/share/virtualenvs/HttpRunner-_3-s9PUt/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py)', 'urllib3.util (/Users/searchbb/.local/share/virtualenvs/HttpRunner-_3-s9PUt/lib/python3.6/site-packages/urllib3/util/__init__.py)']. 
  monkey.patch_all()
INFO     Starting web monitor at *:8089
INFO     Starting Locust 0.8.1

**Comment by searchbb** [comment]
今天早上花了点时间看了下代码，主要是main debug里先引用了httprunner.cli，造成gevent的引用早于了locust, 我在前面加了 from gevent import monkey    monkey.patch_all()，这样monkey的加载在前面了，就不会报错了，这只是简单的解决的debug模式的问题，locusts为什么一样会报错还没空看

<img width="646" alt="image" src="https://user-images.githubusercontent.com/42245656/43937657-85661c62-9c91-11e8-9711-a8d70089fdda.png">

**Comment by debugtalk** [comment]
@searchbb 非常感谢。按照你的指导，我修复了下代码，在本地验证是可以解决 RecursionError 的问题。
