### ISSUE TITLE
3.x中如何实现自定义结果校验器?

### ISSUE THREAD

**Issue by jiangtao69039** [httprunner/httprunner#1123]
我看到3.x版本中似乎移除了这个功能,那怎么实现呢?

**Comment by panyuan209** [comment]
在 debugtalk.py 文件里自定义一个结果处理函数，然后在用例把响应结果作为参数传入，就可以实现自定义校验了

**Comment by Patrick-kk** [comment]
> 

@panyuan209  请问，传入参数如果是 dict['key'] 或者 list[0]，要怎么写呢？ 目前使用来说，只能传入 string
