### ISSUE TITLE
如何去掉日志中的颜色?

### ISSUE THREAD

**Issue by jiangtao69039** [httprunner/httprunner#1124]
目前可以通过参数配置去掉颜色吗?

**Comment by panyuan209** [comment]
httprunner 用的是 loguru 库生成日志，它是自带颜色的，如果想去掉，loguru 也提供了自定义颜色的方式，改成自己想要的就行了。
`logger.add(sys.stdout, colorize=True, format="<green>{time}</green> <level>{message}</level>")
`
