### ISSUE TITLE
httprunner.context.Context.init_context 方法 level 条件判断

### ISSUE THREAD

**Issue by xie0723** [HttpRunner/HttpRunner#113]
问题：
25 行有一个 `if level == "testset":` 判断
38 行有一个 `if level == "testset":` 判断

根据这个方法的doc, 应该是：
38 行 ` if level == "testcase":`

如果不是：
 `if level == "testcase":`

38行没必要再判断一次了啊。直接写在上一个if 条件代码块逻辑中就可以了。

**Comment by debugtalk** [comment]
@xie0723 38行的确也应该是 testset，这是全局的。
之所以分开写，是因为在执行 self.import_module_items 之前，要初始化 self.testset_functions_config 和 self.testcase_functions_config。
