### ISSUE TITLE
 HttpRunner httprunner3  $ 转义问题

### ISSUE THREAD

**Issue by stone9159** [httprunner/httprunner#1136]
## 问题描述
测试用户删除接口时，需要使用执行 sql 语句初始化，创建专门用来创建测试接口的用户，新建用户中的密码是需要加密的，加密后基本都有 $ 符号：

'insert into rdb_server_jdbc_db.users values(100,"user_for_test_delete_api","$2a$15$QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy",1,"user_for_test_delete_api","user@example.com","2021-11-30 01:56:40","2021-11-30 01:56:40");',

但是在 httprunner3 中，$2a$15$QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy 被解析为 3 个变量，导致报错：
raise exceptions.VariableNotFound(not_defined_variables)
E httprunner.exceptions.VariableNotFound: ['QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy', '2a', '15']

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Linux]
 - Python 版本 [3.7]
 - HttpRunner 版本 [3.1.6]
 - **设备 ID**: []

获取方式：
直接在pycharm中运行代码

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
`# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/demo_testcase_request.yml
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
import pytest
from httprunner import Parameters
from common import Prepare_env,tools
import config
from test_initial_files import rdb_server_jdbc_db_inital_sql

class TestCase_delete_user_API_Request(HttpRunner):
    # @pytest.mark.parametrize(
    #     "param",
    #     Parameters(
    #         {
    #             "user_id-is_real_login-status_code-body_message": [
    #                 [9999,False, 404,"user info not find for 9999"],
    #                 # ["abc",False,200,"Oops, we got one problem! Please contact support!"],
    #                 # ["",False,200,"Oops, we got one problem! Please contact support!"],
    #                 # [100, True, 500, "Oops, we got one problem! Please contact support!"],
    #                 # [100, False, 500, "Oops, we got one problem! Please contact support!"]
    #
    #             ]
    #         }
    #     ),
    # )
    # def test_start(self, param):
    #     super().test_start(param)
    config = (
        Config("Test_get_auth_center_version")
        .base_url("http://${get_ip_by_service_name(rdb-server-auth-center)}:9110/AuthCenter")
        .variables(
            **{
                "inital_sql": "insert into rdb_server_jdbc_db.users values(100,'usser_for_test_delete_api1','$2a$15$QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy',1,'user_for_test_delete_api','road@ygomi.com','2021-11-30 01:56:40','2021-11-30 01:56:40');",
            }
        )
    )

    teststeps = [
        Step(
            RunRequest("get_auth_center_version")
            # .setup_hook("${hook_up($inital_sql)}")
            # .setup_hook("${login_fork(is_real_login=False)}")
            .delete("/api/users/9999")
            .validate()
            .assert_equal("status_code", "200")
            # .assert_string_equals("body.message","${body_message}")
        )
    ]

if __name__ == "__main__":
    TestCase_delete_user_API_Request().test_start()
`

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

`Testing started at 下午9:37 ...
/usr/bin/python3 /home/user/3-software/pycharm-community-2018.2.5/helpers/pycharm/_jb_pytest_runner.py --target Test_delete_user_API.py::TestCase_delete_user_API_Request
Launching pytest with arguments Test_delete_user_API.py::TestCase_delete_user_API_Request in /home/user/4-study/interfacedemo/testcases/Test_Auth_Center/Auth/Users

============================= test session starts ==============================
platform linux -- Python 3.7.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/user/4-study/interfacedemo/testcases/Test_Auth_Center/Auth/Users
plugins: html-2.1.1, metadata-1.11.0collected 1 item

Test_delete_user_API.py Fexecute cmd is : kubectl get service |grep -v -headless|awk '{print $1,$3}' in ./
execute cmd is : kubectl get service |grep -v -headless|awk '{print $1,$3}' in ./
2021-12-08 21:38:06.943 | INFO     | httprunner.runner:test_start:451 - Start to run testcase: Test_get_auth_center_version, TestCase ID: caa8cb12-cae1-4a6f-addf-dc434cb71527
2021-12-08 21:38:06.943 | INFO     | httprunner.runner:test_start:460 - generate testcase log: /home/user/4-study/interfacedemo/testcases/Test_Auth_Center/logs/caa8cb12-cae1-4a6f-addf-dc434cb71527.run.log

../../../../../../../../usr/local/lib/python3.7/site-packages/httprunner/runner.py:423 (TestCase_delete_user_API_Request.test_start)
self = <Test_delete_user_API.TestCase_delete_user_API_Request object at 0x7fc85650af10>
param = None

    def test_start(self, param: Dict = None) -> "HttpRunner":
        """main entrance, discovered by pytest"""
        self.__init_tests__()
        self.__project_meta = self.__project_meta or load_project_meta(
            self.__config.path
        )
        self.__case_id = self.__case_id or str(uuid.uuid4())
        self.__log_path = self.__log_path or os.path.join(
            self.__project_meta.RootDir, "logs", f"{self.__case_id}.run.log"
        )
        log_handler = logger.add(self.__log_path, level="DEBUG")
    
        # parse config name
        config_variables = self.__config.variables
        if param:
            config_variables.update(param)
        config_variables.update(self.__session_variables)
        self.__config.name = parse_data(
            self.__config.name, config_variables, self.__project_meta.functions
        )
    
        if USE_ALLURE:
            # update allure report meta
            allure.dynamic.title(self.__config.name)
            allure.dynamic.description(f"TestCase ID: {self.__case_id}")
    
        logger.info(
            f"Start to run testcase: {self.__config.name}, TestCase ID: {self.__case_id}"
        )
    
        try:
            return self.run_testcase(
>               TestCase(config=self.__config, teststeps=self.__teststeps)
            )

/usr/local/lib/python3.7/site-packages/httprunner/runner.py:456: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.7/site-packages/httprunner/runner.py:334: in run_testcase
    self.__parse_config(self.__config)
/usr/local/lib/python3.7/site-packages/httprunner/runner.py:310: in __parse_config
    config.variables, self.__project_meta.functions
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

variables_mapping = {'inital_sql': "insert into rdb_server_jdbc_db.users values(100,'usser_for_test_delete_api1','$2a$15$QeuSCLP8s8r5xMJsW...YJCrWlLlabbYWX2R7VBFwwXy',1,'user_for_test_delete_api','road@ygomi.com','2021-11-30 01:56:40','2021-11-30 01:56:40');"}
functions_mapping = {'get_httprunner_version': <function get_httprunner_version at 0x7fc854204c20>, 'get_ip_by_service_name': <function ge...c854204f80>, 'hook_down': <function hook_down at 0x7fc854204cb0>, 'hook_up': <function hook_up at 0x7fc8541adb00>, ...}

    def parse_variables_mapping(
        variables_mapping: VariablesMapping, functions_mapping: FunctionsMapping = None
    ) -> VariablesMapping:
    
        parsed_variables: VariablesMapping = {}
    
        while len(parsed_variables) != len(variables_mapping):
            for var_name in variables_mapping:
    
                if var_name in parsed_variables:
                    continue
    
                var_value = variables_mapping[var_name]
                variables = extract_variables(var_value)
    
                # check if reference variable itself
                if var_name in variables:
                    # e.g.
                    # variables_mapping = {"token": "abc$token"}
                    # variables_mapping = {"key": ["$key", 2]}
                    raise exceptions.VariableNotFound(var_name)
    
                # check if reference variable not in variables_mapping
                not_defined_variables = [
                    v_name for v_name in variables if v_name not in variables_mapping
                ]
                if not_defined_variables:
                    # e.g. {"varA": "123$varB", "varB": "456$varC"}
                    # e.g. {"varC": "${sum_two($a, $b)}"}
>                   raise exceptions.VariableNotFound(not_defined_variables)
E                   httprunner.exceptions.VariableNotFound: ['QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy', '2a', '15']

/usr/local/lib/python3.7/site-packages/httprunner/parser.py:455: VariableNotFound
                                                [100%]

=================================== FAILURES ===================================
_________________ TestCase_delete_user_API_Request.test_start __________________

self = <Test_delete_user_API.TestCase_delete_user_API_Request object at 0x7fc85650af10>
param = None

    def test_start(self, param: Dict = None) -> "HttpRunner":
        """main entrance, discovered by pytest"""
        self.__init_tests__()
        self.__project_meta = self.__project_meta or load_project_meta(
            self.__config.path
        )
        self.__case_id = self.__case_id or str(uuid.uuid4())
        self.__log_path = self.__log_path or os.path.join(
            self.__project_meta.RootDir, "logs", f"{self.__case_id}.run.log"
        )
        log_handler = logger.add(self.__log_path, level="DEBUG")
    
        # parse config name
        config_variables = self.__config.variables
        if param:
            config_variables.update(param)
        config_variables.update(self.__session_variables)
        self.__config.name = parse_data(
            self.__config.name, config_variables, self.__project_meta.functions
        )
    
        if USE_ALLURE:
            # update allure report meta
            allure.dynamic.title(self.__config.name)
            allure.dynamic.description(f"TestCase ID: {self.__case_id}")
    
        logger.info(
            f"Start to run testcase: {self.__config.name}, TestCase ID: {self.__case_id}"
        )
    
        try:
            return self.run_testcase(
>               TestCase(config=self.__config, teststeps=self.__teststeps)
            )

/usr/local/lib/python3.7/site-packages/httprunner/runner.py:456: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.7/site-packages/httprunner/runner.py:334: in run_testcase
    self.__parse_config(self.__config)
/usr/local/lib/python3.7/site-packages/httprunner/runner.py:310: in __parse_config
    config.variables, self.__project_meta.functions
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

variables_mapping = {'inital_sql': "insert into rdb_server_jdbc_db.users values(100,'usser_for_test_delete_api1','$2a$15$QeuSCLP8s8r5xMJsW...YJCrWlLlabbYWX2R7VBFwwXy',1,'user_for_test_delete_api','road@ygomi.com','2021-11-30 01:56:40','2021-11-30 01:56:40');"}
functions_mapping = {'get_httprunner_version': <function get_httprunner_version at 0x7fc854204c20>, 'get_ip_by_service_name': <function ge...c854204f80>, 'hook_down': <function hook_down at 0x7fc854204cb0>, 'hook_up': <function hook_up at 0x7fc8541adb00>, ...}

    def parse_variables_mapping(
        variables_mapping: VariablesMapping, functions_mapping: FunctionsMapping = None
    ) -> VariablesMapping:
    
        parsed_variables: VariablesMapping = {}
    
        while len(parsed_variables) != len(variables_mapping):
            for var_name in variables_mapping:
    
                if var_name in parsed_variables:
                    continue
    
                var_value = variables_mapping[var_name]
                variables = extract_variables(var_value)
    
                # check if reference variable itself
                if var_name in variables:
                    # e.g.
                    # variables_mapping = {"token": "abc$token"}
                    # variables_mapping = {"key": ["$key", 2]}
                    raise exceptions.VariableNotFound(var_name)
    
                # check if reference variable not in variables_mapping
                not_defined_variables = [
                    v_name for v_name in variables if v_name not in variables_mapping
                ]
                if not_defined_variables:
                    # e.g. {"varA": "123$varB", "varB": "456$varC"}
                    # e.g. {"varC": "${sum_two($a, $b)}"}
>                   raise exceptions.VariableNotFound(not_defined_variables)
E                   httprunner.exceptions.VariableNotFound: ['QeuSCLP8s8r5xMJsW9xcGe8f7EeI7YJCrWlLlabbYWX2R7VBFwwXy', '2a', '15']

/usr/local/lib/python3.7/site-packages/httprunner/parser.py:455: VariableNotFound
----------------------------- Captured stdout call -----------------------------
execute cmd is : kubectl get service |grep -v -headless|awk '{print $1,$3}' in ./
execute cmd is : kubectl get service |grep -v -headless|awk '{print $1,$3}' in ./
----------------------------- Captured stderr call -----------------------------
2021-12-08 21:38:06.943 | INFO     | httprunner.runner:test_start:451 - Start to run testcase: Test_get_auth_center_version, TestCase ID: caa8cb12-cae1-4a6f-addf-dc434cb71527
2021-12-08 21:38:06.943 | INFO     | httprunner.runner:test_start:460 - generate testcase log: /home/user/4-study/interfacedemo/testcases/Test_Auth_Center/logs/caa8cb12-cae1-4a6f-addf-dc434cb71527.run.log
=========================== short test summary info ============================
FAILED Test_delete_user_API.py::TestCase_delete_user_API_Request::test_start
============================== 1 failed in 12.41s ==============================
Process finished with exit code 0
`

**Comment by lemonadam** [comment]
我在建造长城，一会回复你。

**Comment by stone9159** [comment]
您的邮件已收到，我会尽快给您回复的。

**Comment by debugtalk** [comment]
@stone9159 使用 `$$` 转义即可。
