### ISSUE TITLE
make_test.py中的测试case存在获取路径问题

### ISSUE THREAD

**Issue by loveliwenli** [httprunner/httprunner#1144]
## 问题描述

make_test.py文件中的case：test_convert_testcase_path()
本地执行case的时候，抛出异常
`
raise exceptions.FileNotFound(err_msg)
E    httprunner.exceptions.FileNotFound: path not exist: /Users/xxxx/Documents/GitHub/httprunner/tests/tests/data/a-b.c/2 3.yml
`
路径拼接存在问题

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.9
 - HttpRunner 版本 最新master有这个问题

获取方式：

直接执行case即可

**Comment by zhengtong0898** [comment]
要运行 make_test.py 你需要做一下操作.
1. 回到项目根路径
```shell
$ pwd
/Users/xxxxx/httprunner
$ ls 
LICENSE         README.md       docs            examples        httprunner      
mkdocs.yml      poetry.lock     pyproject.toml  tests     
```
2. 创建一个 debugtalk.py 文件(到 examples 中去拷贝一个过来)
3. 执行测试命令
```shell
$ hrun tests/make_test.py
```
