### ISSUE TITLE
修改项目名称后，使用pycharm重新打开项目hrun、har2case等命令行报不是内部或外部命令

### ISSUE THREAD

**Issue by Wc-lab** [httprunner/httprunner#1148]
## 问题描述
修改项目名称后，使用pycharm重新打开项目hrun、har2case等命令行，报不是内部或外部命令
请对遇到的 bug 进行简要描述。

![捕获](https://user-images.githubusercontent.com/75770537/149345568-0e713c85-b694-40be-b855-77c069251974.PNG)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]
 - **设备 ID**: [e.g. 190070690681122]

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

```bash
>>> import uuid; print(uuid.getnode())
190070690681122
```

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd
/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/tests
$ hrun testcases/setup.yml
INFO     Loading environment variables from /Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/tests/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
ModuleNotFoundError: No module named 'tests.api_server'
```

**Comment by zhengtong0898** [comment]
看起来像是重命名项目后虚拟环境路径没有找到，所以无法执行正确的命令，建议你重建venv虚拟环境和重新安装httprunner和相关的依赖库。

**Comment by Wc-lab** [comment]
> 看起来像是重命名项目后虚拟环境路径没有找到，所以无法执行正确的命令，建议你重建venv虚拟环境和重新安装httprunner和相关的依赖库。

![image](https://user-images.githubusercontent.com/75770537/149717383-df62818e-2a7a-4921-88f5-c8b0cfc4884e.png)
![image](https://user-images.githubusercontent.com/75770537/149717462-b063f116-a87a-4247-aeb8-e45ccf56cca8.png)
虚拟环境是正常的，可以找到虚拟环境的编译器，这个框架不能该项目名啊

**Comment by Wc-lab** [comment]
> 看起来像是重命名项目后虚拟环境路径没有找到，所以无法执行正确的命令，建议你重建venv虚拟环境和重新安装httprunner和相关的依赖库。

重新安装httprunner 和 har2case 也没用感觉项目的名称已经缓存在框架里面的，只要修改工程名称就没办法运行

**Comment by Wc-lab** [comment]
> 看起来像是重命名项目后虚拟环境路径没有找到，所以无法执行正确的命令，建议你重建venv虚拟环境和重新安装httprunner和相关的依赖库。

![image](https://user-images.githubusercontent.com/75770537/149718681-af6d8eca-8755-4761-a741-5ff70e054e98.png)
![image](https://user-images.githubusercontent.com/75770537/149718743-ae5890d1-b357-4ae9-8a81-73debac03323.png)
虚拟环境的编译器是已经切换正常了的
