### ISSUE TITLE
用例执行环境的配置，有更好的方法嘛？

### ISSUE THREAD

**Issue by happyMeiyo** [HttpRunner/HttpRunner#115]
**期望**：可在执行一个项目的测试时，选择用例的执行环境，比如线下环境，或者线上环境
**目前解决方案**：

1. 一个线下环境的env文件，一个线上环境的env文件；env文件定义不同的http的域名和账号信息
2. 执行用例时，选择不同的env文件
3. debugtalk.py中读取环境变量：http域名、账号信息

**Comment by happyMeiyo** [comment]
@debugtalk httpRunner目前支持用例执行环境的配置嘛？

**Comment by debugtalk** [comment]
@happyMeiyo 正如你列出的几点，现在 HttpRunner 已经支持了 env 和 debugtalk.py 两种方式。

可以尝试采用这种做法：

1、在测试用例中引用 HOST、账号信息，这些信息定义在 debugtalk.py 中；

例如：

```yaml
- config:
    request:
        base_url: $HOST
```

2、在 debugtalk.py 中，通过环境变量来选择使用测试环境还是线上环境；

```python
test_env = os.environ.get("test_env", "TEST")
if test_env == "PRODUCTION":
    HOST = "http://cn.httprunner.org"
else:
    HOST = "http://en.httprunner.org" 
```

**Comment by happyMeiyo** [comment]
@debugtalk 嗯，谢谢，因为每个环境的账号信息不同，我目前的做法：
1. .env文件中定义host和账号信息
2. debugtalk.py中，通过环境变量来选择测试环境
‘’‘python
activateCode = os.environ.get('activateCode')
userCode = os.environ.get('userCode')
userPwd = os.environ.get('userPwd')
vipTelephone = os.environ.get('vipTelephone')
base_url = os.environ.get('base_url')
'''
