### ISSUE TITLE
通过RunTestCase.with_variables 引用设置的变量 无法覆盖原testcase 中的变量 

### ISSUE THREAD

**Issue by JK-yan** [httprunner/httprunner#1157]
## 问题描述

1. testcase A 中设置一个变量a
2. 在testcase B 的step 通过RunTestCase.with_variables 引用test case A ，并且想要覆盖原来A中的变量a 的值
```
RunTestCase("上传文本创建staff").with_variables(**{"staff_source_id":"$staff_source_id"}).call(TestUploadTextSession)
```

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 3.7
 - HttpRunner  3.1.6

**Comment by zhengtong0898** [comment]
httprunner采取的是就近覆盖策略, 即: 子用例会优先使用自己定义的变量.
可以尝试去掉子用例中的变量定义, 完全接受parent传递进来的变量.

**Comment by xyd0000** [comment]
staff_source_id如果是子用例testcase A中Config指定的全局变量，那么父用例testcase B应该可以覆盖掉子用例中staff_source_id的值吧

**Comment by JK-yan** [comment]
> taff_source_id如果是子用例testcase A中Config指定的全局变量，那么父用例testcase B应该可以覆盖掉子用例中staff_source_id的值吧

现实是，并没有覆盖
