### ISSUE TITLE
能否增加一个comparator来检查某个元素(key)不在返回的response body中？

### ISSUE THREAD

**Issue by lopoko** [HttpRunner/HttpRunner#116]
目前看到所有的comparator都是帮助判断元素是否存在的。能否加一个comparator来判断某个元素不存在于返回的response body中？这个可以帮助我们验证是不是有不应该返回的元素被服务器返回了。

**Comment by debugtalk** [comment]
@lopoko 支持自定义comparator的

参考：[《HttpRunner 的结果校验器优化》](http://debugtalk.com/post/HttpRunner-validator-optimization/)
