### ISSUE TITLE
文档网站（docs.httprunner.org）不可访问，貌似域名过期

### ISSUE THREAD

**Issue by xulz** [httprunner/httprunner#1164]
## HttpRunner v3官方文档网站访问不可达

访问 https://docs.httprunner.org  不可达，访问http://docs.httprunner.org后阿里云提示域名过期。

```
提示：该域名已过期，不能正常访问，续费后可恢复使用。
请您联系您的域名服务商尽快完成续费，以避免域名被删除或被他人注册的风险。

1.如果您是万网会员，请登录万网账户，进入会员中心->域名管理->急需续费域名，完成域名续费；

2.如果您的域名服务由万网代理商提供，请您联系您的代理商咨询续费事宜。
```

**Comment by debugtalk** [comment]
@xulz org 域名在国内没法注册了，后面统一将文档都部署到 httprunner.com 这个域名。
我这两天把 v3 的文档也迁过去吧

**Comment by debugtalk** [comment]
大家先使用这个访问吧：https://httprunner.com/httprunner/

**Comment by xulz** [comment]
已经可以用新地址访问了，👍
如果可行，最好对org的域名做个过渡性的重定向，现在搜索引擎检索出的一些信息还是指向org站点。

**Comment by debugtalk** [comment]
v1/v2/v3 的已有文档都存档到了 https://github.com/httprunner/docs，如果域名不可访问时可在此查看。
