### ISSUE TITLE
报错cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by kulakilam** [httprunner/httprunner#1165]
## 问题描述

安装后执行httprunner -V报错
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/markupsafe/__init__.py)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: MacOS 11.4
 - Python 版本：3.8.6
 - HttpRunner 版本：master最新版本，commit 476e2196458eb400d78cfce4e731ade9fcdb93ea
 - **设备 ID**: 68319969123134

**Comment by xuyucheng1992** [comment]
把jinja2 升级到最新版就行了

**Comment by kulakilam** [comment]
> 把jinja2 升级到最新版就行了

升级后可以了，多谢
