### ISSUE TITLE
请教一个Cookie的问题

### ISSUE THREAD

**Issue by imliyachao** [HttpRunner/HttpRunner#117]
事情是这样的，我们系统是借用第三方系统登录的，登录的时候先调第三方登录接口，然后将第三方登录接口response header里返回的set cookie作为cookie值调我们自己系统的接口，生成一个token，后续在我们系统的操作都用这个token。现在的问题是，第一个接口和第二个接口顺序执行，调完第三方接口，在没有人为提取cookie的基础上，第二个接口就直接生成token了，如果单独调第二个接口就会报错，这就说明在执行第一个用例之后，自动记住了这个cookie，这个是属于unitest的特性么？还是httprunner的特性，在之前的学习中，没有看到过会自动记住cookie这种说法，麻烦帮忙解惑

**Comment by debugtalk** [comment]
@imliyachao 这是 requests 的特性。详情可参考[官方文档](http://docs.python-requests.org/en/master/user/advanced/#session-objects)。
