### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for ResponseData，返回data为null的时候报错

### ISSUE THREAD

**Issue by 360kevin** [httprunner/httprunner#1174]
## 问题描述

执行接口测试的时候由于接口返回数据为null(符合预期成功)，导致执行报错；
报错信息：
##############################################################
pydantic/main.py:331: in pydantic.main.BaseModel.__init__
    ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for ResponseData
E   body
E     none is not an allowed value (type=type_error.none.not_allowed)

## 版本信息
httprunner 3.16版本

请提供如下版本信息：

 - 操作系统类型: macos
 - Python  3.9.7
 - HttpRunner 3.1.6
 

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。
======================================================================================================= FAILURES =======================================================================================================
__________________________________________________________________________________________ TestCaseDemoTestcaseRef.test_start __________________________________________________________________________________________
../../Library/Python/3.8/lib/python/site-packages/httprunner/runner.py:455: in test_start
    return self.run_testcase(
../../Library/Python/3.8/lib/python/site-packages/httprunner/runner.py:357: in run_testcase
    extract_mapping = self.__run_step(step)
../../Library/Python/3.8/lib/python/site-packages/httprunner/runner.py:295: in __run_step
    step_data = self.__run_step_request(step)
../../Library/Python/3.8/lib/python/site-packages/httprunner/runner.py:166: in __run_step_request
    resp = self.__session.request(method, url, **parsed_request_dict)
../../Library/Python/3.8/lib/python/site-packages/httprunner/client.py:208: in request
    self.data.req_resps = [
../../Library/Python/3.8/lib/python/site-packages/httprunner/client.py:209: in <listcomp>
    get_req_resp_record(resp_obj) for resp_obj in response_list
../../Library/Python/3.8/lib/python/site-packages/httprunner/client.py:93: in get_req_resp_record
    response_data = ResponseData(
pydantic/main.py:331: in pydantic.main.BaseModel.__init__
    ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for ResponseData
E   body
E     none is not an allowed value (type=type_error.none.not_allowed)

**Comment by debugtalk** [comment]
@360kevin 感谢反馈，该问题在 3.1.9 中修复了。
