### ISSUE TITLE
如何自动对响应进行全量验证

### ISSUE THREAD

**Issue by xyd0000** [httprunner/httprunner#1175]
## 背景描述
假设响应json是：
`body = {
key1:vaule1,
key2:{key3:vaule3,},
key4:[{},{}]
}`
通过har2case转化的测试例，只会自动生成对key1的校验

## 期望的功能特性

har2case转化的测试例实现响应的全量校验

**Comment by debugtalk** [comment]
@xyd0000 全量校验的稳定性可能会很差，因为每次响应中有很多参数都可能会发生变化。更好的方式是实现 schema 层级的校验，详见 #1257
