### ISSUE TITLE
能否暴露一个请求前可以修改请求参数的接口，以便调用

### ISSUE THREAD

**Issue by yxder** [HttpRunner/HttpRunner#118]
比如，发送请求前我想签名，或者删除一个请求参数，暂时没有想到可以获取请求信息的方法，于是我只能在client.py里面修改源码实现想要的功能

先拜谢大神！

**Comment by debugtalk** [comment]
HttpRunner 从 1.2.0 版本开始支持 hook 机制，可以在请求前和请求后调用钩子函数。

http://cn.httprunner.org/request-hook/
