### ISSUE TITLE
返回数据json中key存在“-”时json用例转pytest用例后出现多余双引号，修复建议见详情

### ISSUE THREAD

**Issue by 472173257dl** [httprunner/httprunner#1209]
## 问题描述

返回数据json中key以-1结尾时json用例转pytest用例后出现多余双引号，导致运行报错

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g.Windows]
 - Python 版本 [e.g. 3.7.3]
 - HttpRunner 版本 [e.g. 3.17]

获取方式：

源码clone

## 项目文件内容（非必须）

![image](https://user-images.githubusercontent.com/20190050/160132135-39237e68-23a8-44b9-8bd7-5f129423d340.png)

![image](https://user-images.githubusercontent.com/20190050/160132340-463fad5b-2b84-481a-a85d-67b39fbb43a8.png)

**Comment by 472173257dl** [comment]
修改建议：
![image](https://user-images.githubusercontent.com/20190050/160151282-07532f0c-50d9-4a77-80f3-6161a5a8c23a.png)
增加jmespath特有管道符进行判断

**Comment by debugtalk** [comment]
@472173257dl 该问题已经在 3.1.8 中修复了，你升级后再看下呢？
如果还有问题的话，可以 reopen 这个 issue 再反馈下。

**Comment by debugtalk** [comment]
@472173257dl 仔细看了下，这种情况的确是误处理了，需要再修复下
