### ISSUE TITLE
go版本希望能够自定义一些函数，类似python版本的debugtalk.py 

### ISSUE THREAD

**Issue by JK-yan** [httprunner/httprunner#1219]
## 背景描述

> 通过hashicorp.go注册debugtalk.go 发现是开启了grpc，并且需要在testcase里面指定path，而写了一个获取环境变量的方法ENV注册以后在testcase 里面的baseurl 希望通过ENV（XXX） 获取域名，但是系统提示我grpc 相关的error

## 期望的功能特性

> 能够自定义一些方法可以直接使用

**Comment by debugtalk** [comment]
@JK-yan 已经支持了的，你可以参考这里面的示例 
https://github.com/httprunner/httprunner/tree/master/examples

**Comment by JK-yan** [comment]
> 考

抱歉，是我写的func 获取配置文件数据没取到，看懂报grpc的error 就主观认为 是grpc的锅了

@debugtalk  另外问一下，hrp 是否已经支持对
1. 对report的自定义命名和自定义报告模版 ，(ps：计划搞个服务直接把每次执行的结果返回出去)
2. 是否有个api 可以直接返回本次执行的结果返回true/false  （ps：希望是能放到ci里面进行初步判断）
