### ISSUE TITLE
hrp 版本hrp.NewStep("get with params").CallRefCase().Export() ，的export 不起作用

### ISSUE THREAD

**Issue by JK-yan** [httprunner/httprunner#1231]
## 问题描述
`testcas1->ExportVars("varFoo1)  ->step 1 ->Extract().
				WithJmesPath("body.args.foo1", "varFoo1").
WithJmesPath("body.args.foo1", "varFoo2")`

`testcas1->setp1->.CallRefCase(testcas1)->setp2 可以直接使用($varFoo1)`
现象：
`testcas1->setp1->.CallRefCase(testcas1).ExportVars("varFoo2)->setp2 无法使用($varFoo2)`

**Comment by bbx-winner** [comment]
@JK-yan 可以提供下具体的 testcase 脚本吗？便于复现问题

**Comment by JK-yan** [comment]
> @JK-yan 可以提供下具体的 testcase 脚本吗？便于复现问题

我先关闭缺陷，可能是我当时使用问题，现在没有复现，如果再遇到了 我再从新打开
