### ISSUE TITLE
httprunner startproject 新项目后，项目里没有 testsuite 文件夹 （mac 电脑）

### ISSUE THREAD

**Issue by matthewxuda** [httprunner/httprunner#1236]
## 问题描述
<img width="1234" alt="屏幕快照 2022-04-10 22 38 34" src="https://user-images.githubusercontent.com/5927005/162624807-48b1a725-3437-4b42-a00d-7cdbc6c17ab6.png">

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macOS, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]
 - **设备 ID**: [e.g. 190070690681122]

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

```bash
>>> import uuid; print(uuid.getnode())
190070690681122
```

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

**Comment by binbinu** [comment]
我也没有,自己创建了一个

**Comment by debugtalk** [comment]
@matthewxuda 在 v3 之后的版本中去除了 testsuite 的概念，一个文件夹中的所有文件即对应一个 suite 用例集。
