### ISSUE TITLE
template evaluate error occurred when generating API html report

### ISSUE THREAD

**Issue by debugtalk** [httprunner/httprunner#1237]
## 问题描述

执行 API 接口测试生成 HTML 测试报告时，出现如下报错信息。

```
ERR execute applies a parsed template to the specified data object failed error="template: report:242:63: executing \"report\" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}"
```

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macOS
 - HttpRunner 版本：v4.0.0-alpha

## 运行命令 && 堆栈信息

复现步骤：

```bash
$ hrp startproject demo
$ cd demo
$ hrp run testcases/demo_requests.yml testcases/demo_ref_testcase.yml -g
```

报错信息：

```
ERR execute applies a parsed template to the specified data object failed error="template: report:242:63: executing \"report\" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}"
```

**Comment by zlcolin** [comment]
+1 hrp -v 为啥v4.3.0 还有这个问题？
hrp version v4.3.0  

5:57PM INF validate body.form.foo2 assertMethod=eq checkExpr=body.form.foo2 checkValue=bar21 checkValueType=string expectValue=bar21 expectValueType=string result=true
ReqResps in type interface {}"
5:57PM INF quit hashicorp plugin process
2022-12-23T17:57:31.697+0800 [WARN]  grpc-py: plugin failed to exit gracefully
2022-12-23T17:57:31.713+0800 [ERROR] grpc-py: plugin process exited: path=C:\Users\Colin\.hrp\venv\Scripts\python.exe pid=18300 error="exit status 1"
Error: template: report:242:63: executing "report" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}
5:57PM WRN hrp exit code=1

**Comment by Liu-Ying-95** [comment]
hrp version v4.3.0 @
testcase里面调用其他用例时生产报告也遇到了相同的问题，单独执行某个接口时可以正常生成报告

ERR execute applies a parsed template to the specified data object failed error="template: report:242:63: executing \"report\" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}"

**Comment by CheapSesame** [comment]
hrp version v4.3.0


> hrp version v4.3.0 @ testcase里面调用其他用例时生产报告也遇到了相同的问题，单独执行某个接口时可以正常生成报告
> 
> ERR execute applies a parsed template to the specified data object failed error="template: report:242:63: executing "report" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}"

+1 同样的版本和问题

> Error: template: report:242:63: executing "report" at <.Data.ReqResps.Request>: can't evaluate field ReqResps in type interface {}

**Comment by jonzha9527** [comment]
我这边也是一直存在这个问题，只要运行嵌套的testcase，就会报错导致report无法生成
尝试了mac，Windows，docker 执行都是一样的结果，和Python版本无关，就是**grpc-py** 的问题
### 这个bug覆盖面太大了，所有嵌套的case都无法执行，麻烦尽快fix

`hrp run debug/ref_testcase.yml -g -c`
![image](https://user-images.githubusercontent.com/43426348/213353303-13aed729-1c20-4615-acd5-73653e295d93.png)
![image](https://user-images.githubusercontent.com/43426348/213353386-1fb6bb10-00e0-428e-bbcd-094608382da5.png)
