### ISSUE TITLE
设置.set_allow_redirects(False)，response.raw为None导致报错

### ISSUE THREAD

**Issue by cwk0099** [httprunner/httprunner#1247]
## 问题描述

> 请对 bug 进行简要描述；
> 尽量附带运行的命令和报错时的堆栈信息

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本: 3.9
 - HttpRunner 版本 3.1.8

## 项目文件内容（非必须）

    config = (
        Config(name="登录")
        .base_url('${getLoginUrl()}')
        .verify(False)
        .export(*['php_token', 'token_id'])
    )
    teststeps=[
        Step(
            RunRequest('获取phpSessionId')
            .get('/authorize')
            .set_verify(False)
            .with_headers(**header)
            .with_params(**params)
            .extract()
            .with_jmespath('cookies', 'php_token')
            # .teardown_hook('${setToken($response)}')
            .validate()
            .assert_equal('status_code', 200, "失败")

        ),
        Step(
            RunRequest('获取tokenid')
            .post('/authorize')
            .with_headers(**id_header)
            .with_data(f"username={username}&password={passwd}")
            .with_params(**params)
            .set_allow_redirects(False)

**Comment by cwk0099** [comment]
![image](https://user-images.githubusercontent.com/37758451/163511593-0e0b4aec-256a-4149-983a-3683f314ca4e.png)

**Comment by debugtalk** [comment]
@cwk0099 感谢反馈，该问题将在 3.1.9 中修复

**Comment by cwk0099** [comment]
![image](https://user-images.githubusercontent.com/37758451/163744917-eede922c-2e17-4355-88b3-5bb3fdd8cb70.png)
