### ISSUE TITLE
设置.set_allow_redirects(False)报错

### ISSUE THREAD

**Issue by cwk0099** [httprunner/httprunner#1249]
## 问题描述
延续#1247
https://github.com/httprunner/httprunner/issues/1247#issue-1205203219
> 请对 bug 进行简要描述；
> 尽量附带运行的命令和报错时的堆栈信息
![image](https://user-images.githubusercontent.com/37758451/163745104-ab81ee8d-8e9e-4f36-92c2-7ea2e0cef52d.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Python 版本: 3.9
 - HttpRunner 版本 3.1.9

**Comment by cwk0099** [comment]
大佬你写反了吧

**Comment by debugtalk** [comment]
@cwk0099 嗯，我修复下

**Comment by debugtalk** [comment]
@cwk0099 修复了，新版本 3.1.10
