### ISSUE TITLE
安装说明中，开发者模式运行单元测试用例报错INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000

### ISSUE THREAD

**Issue by FrancisJen** [HttpRunner/HttpRunner#125]
step：
pipenv run python3 -m unittest discover
or
pipenv run python -m unittest discover

----------------------------------------------------------------------
Ran 10 tests in 0.042s

OK (skipped=4)
...ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ssssERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.----------------------------------------------------------------------
Ran 10 tests in 0.041s

OK (skipped=4)
...ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ssssERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
----------------------------------------------------------------------
Ran 10 tests in 0.035s

OK (skipped=4)
.ERROR:root:Failed to extract data with regex!
response: {'status_code': 200, 'headers': {'Content-Type': 'application/json', 'Content-Length': '2', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Tue, 20 Mar 2018 12:51:02 GMT'}, 'body': ''}
regex: content.abc

.....ERROR:root:Failed to extract value from response!
response: {'status_code': 200, 'headers': {'Content-Type': 'application/json', 'Content-Length': '15', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Tue, 20 Mar 2018 12:51:02 GMT'}, 'body': 'LB123abcRB789'}
extract field: LB123.*RB789

...ERROR:root:401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.ERROR:root:request:
headers: {'content-type': 'application/json', 'user_agent': 'iOS/10.3', 'device_sn': 'HZfFBh6tU59EdXJ', 'os_platform': 'ios', 'app_version': '2.8.6'}
json: {'sign': 'f1219719911caae89ccc301679857ebfda115ca2'}

ERROR:root:response:
status_code: 200
headers: {'Content-Type': 'application/json', 'Content-Length': '46', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Tue, 20 Mar 2018 12:51:02 GMT'}
body: {"success": true, "token": "IbB7xaAsalpwNgKp"}

..get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.016s

OK
get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.

----------------------------------------------------------------------
Ran 3 tests in 0.021s

OK
.get token with iOS/10.3, 2.8.6
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.062s

OK
.get token with iOS/10.3, 2.8.6
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.064s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.013s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
.get token with iOS/10.1 and 2.8.5
.
get token with iOS/10.1 and 2.8.6
.
get token with iOS/10.2 and 2.8.5
.
get token with iOS/10.2 and 2.8.6
.
get token with iOS/10.3 and 2.8.5
.
get token with iOS/10.3 and 2.8.6
.

----------------------------------------------------------------------
Ran 6 tests in 0.034s

OK
.get token with iOS/10.3, 2.9.7
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.062s

OK
.get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.
get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 6 tests in 0.036s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.015s

OK
...............ERROR:root:JSONDecodeError: JSON file format error: tests/data/tmp.json
ERROR:root:Testcase file content is empty: tests/data/tmp.json
ERROR:root:JSONDecodeError: JSON file format error: tests/data/tmp.json
.......ERROR:root:file not found: /Users/francis/Projects/Interface/HttpRunner/tests/data_not_exist
ERROR:root:file not found: /Users/francis/Projects/Interface/HttpRunner/tests/data_not_exist/
.ERROR:root:Testcase file content is empty: tests/data/tmp.yml
ERROR:root:Testcase file content format invalid: tests/data/tmp.yml
..................Start to create new project: /Users/francis/Projects/Interface/HttpRunner/projectABC

created folder: /Users/francis/Projects/Interface/HttpRunner/projectABC
created folder: /Users/francis/Projects/Interface/HttpRunner/projectABC/tests
created folder: /Users/francis/Projects/Interface/HttpRunner/projectABC/tests/api
created folder: /Users/francis/Projects/Interface/HttpRunner/projectABC/tests/suite
created folder: /Users/francis/Projects/Interface/HttpRunner/projectABC/tests/testcases
created file: /Users/francis/Projects/Interface/HttpRunner/projectABC/tests/debugtalk.py

..................
----------------------------------------------------------------------
Ran 113 tests in 4.917s

OK
pgdeMacBook-Pro:HttpRunner francis$

Session Contents Restored

Last login: Thu Mar 22 10:18:49 on ttys000
pgdeMacBook-Pro:HttpRunner francis$ pipenv install --dev
Installing dependencies from Pipfile.lock (518770)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 8/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 9/29 — 00:  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 15/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 16/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 17/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 18/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 19/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 20/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 21/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 22/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 23/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 24/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 25/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 26/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 27/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 28/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 29/29 — 00  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 29/29 — 00:00:04
To activate this project's virtualenv, run the following:
 $ pipenv shell
pgdeMacBook-Pro:HttpRunner francis$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bash-3.2$ . /Users/francis/.local/share/virtualenvs/HttpRunner-NKNoFnQz/bin/activate
(HttpRunner-NKNoFnQz) bash-3.2$ pipienv run python -m unittest discovier
bash: pipienv: command not found
(HttpRunner-NKNoFnQz) bash-3.2$ pipienv run python -m unittest discover
bash: pipienv: command not found
(HttpRunner-NKNoFnQz) bash-3.2$ pipienv run python -m unittest discover
bash: pipienv: command not found
(HttpRunner-NKNoFnQz) bash-3.2$ deactivate
bash-3.2$
bash-3.2$ exit()
>
bash-3.2$ exit
exit
pgdeMacBook-Pro:HttpRunner francis$ pipenv run python3 -m unittest discover
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 500 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "DELETE /api/users/1000 HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "DELETE /api/users/1000 HTTP/1.1" 404 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /customize-response HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /customize-response HTTP/1.1" 210 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/users/1000 HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/users/1000 HTTP/1.1" 404 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/users HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/users HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1001 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/users HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET / HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "PUT /api/users/1000 HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "PUT /api/users/1000 HTTP/1.1" 404 -
. * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
.127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/get-token HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "GET /api/reset-all HTTP/1.1" 200 -
127.0.0.1 - - [22/Mar/2018 13:51:02] "POST /api/users/1000 HTTP/1.1" 201 -
.............get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
create user which existed (skip unconditionally)
s
create user which existed (skip unconditionally)
s
create user which existed (skip if condition)
s
create user which existed (skip if condition)
s
create user which existed (skip unless condition)
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
create user which existed (skip unless condition)
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 10 tests in 0.044s

OK (skipped=4)
...ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ssssERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
----------------------------------------------------------------------
Ran 10 tests in 0.042s

OK (skipped=4)
...ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ssssERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
----------------------------------------------------------------------
Ran 10 tests in 0.036s

OK (skipped=4)
.ERROR:root:Failed to extract data with regex!
response: {'status_code': 200, 'headers': {'Content-Type': 'application/json', 'Content-Length': '2', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Thu, 22 Mar 2018 05:51:04 GMT'}, 'body': ''}
regex: content.abc

.....ERROR:root:Failed to extract value from response!
response: {'status_code': 200, 'headers': {'Content-Type': 'application/json', 'Content-Length': '15', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Thu, 22 Mar 2018 05:51:04 GMT'}, 'body': 'LB123abcRB789'}
extract field: LB123.*RB789

...ERROR:root:401 Client Error: UNAUTHORIZED for url: http://127.0.0.1:5000/api/users/1000
.ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.ERROR:root:request:
headers: {'content-type': 'application/json', 'user_agent': 'iOS/10.3', 'device_sn': 'HZfFBh6tU59EdXJ', 'os_platform': 'ios', 'app_version': '2.8.6'}
json: {'sign': 'f1219719911caae89ccc301679857ebfda115ca2'}

ERROR:root:response:
status_code: 200
headers: {'Content-Type': 'application/json', 'Content-Length': '46', 'Server': 'Werkzeug/0.14.1 Python/3.6.4', 'Date': 'Thu, 22 Mar 2018 05:51:04 GMT'}
body: {"success": true, "token": "5H5xflEcHiOC18GW"}

..get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.020s

OK
get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.

----------------------------------------------------------------------
Ran 3 tests in 0.017s

OK
.get token with iOS/10.3, 2.8.6
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.067s

OK
.get token with iOS/10.3, 2.8.6
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.066s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.017s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.013s

OK
.get token with iOS/10.1 and 2.8.5
.
get token with iOS/10.1 and 2.8.6
.
get token with iOS/10.2 and 2.8.5
.
get token with iOS/10.2 and 2.8.6
.
get token with iOS/10.3 and 2.8.5
.
get token with iOS/10.3 and 2.8.6
.

----------------------------------------------------------------------
Ran 6 tests in 0.039s

OK
.get token with iOS/10.3, 2.9.7
.
reset all users
.
get user that does not exist
ERROR:root:404 Client Error: NOT FOUND for url: http://127.0.0.1:5000/api/users/1000
.
create user which does not exist
.
get user that has been created
.
create user which exists
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.
update user which exists
.
get user that has been updated
.
get users
.
delete user that exists
.
get users
.
create user which has been deleted
.
get users
.

----------------------------------------------------------------------
Ran 13 tests in 0.067s

OK
.get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/2000
.
get token
.
create user which does not exist
.
create user which existed
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 6 tests in 0.042s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
.get token
.
create user which does not exist
.
create user which does not exist
ERROR:root:500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/api/users/1000
.

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
...............ERROR:root:JSONDecodeError: JSON file format error: tests/data/tmp.json
ERROR:root:Testcase file content is empty: tests/data/tmp.json
ERROR:root:JSONDecodeError: JSON file format error: tests/data/tmp.json
.......ERROR:root:file not found: /Users/francis/Projects/Interface/HttpRunner/tests/data_not_exist
ERROR:root:file not found: /Users/francis/Projects/Interface/HttpRunner/tests/data_not_exist/
.ERROR:root:Testcase file content is empty: tests/data/tmp.yml
ERROR:root:Testcase file content format invalid: tests/data/tmp.yml

**Comment by debugtalk** [comment]
在这个内置的demo中，重复创建相同ID的用户就会报500的错；这是单元测试的需要。
