### ISSUE TITLE
testcase 中的变量是否可以通过一种方式来标识请求是是否需要使用这个变量

### ISSUE THREAD

**Issue by JK-yan** [httprunner/httprunner#1272]
## 背景描述

>  testcase1 -》定义一个变量A，但是它不是一个必填参数，在有些case中需要传，有些不需要
testcase2 -〉我是希望，能有直接通过hrp.NewStep("新增角色").CallRefCase(testcase1)，调用这个case ， 通过我是否传入A来实现不同的测试场景

## 期望的功能特性

>  希望能够有个标识，比如 WithVariables(map[string]interface{}{ “A":nil}, 当A的值是nil 时，就不使用A，非nil 时就使用，
这样就可以，直接使用.CallRefCase(testcase1) 来实现不同的case，而不需要再每个step 里面都把A的接口 参数 断言再写一遍了

**Comment by debugtalk** [comment]
这种设计太复杂了，最好还是在用例分组设计的时候梳理下
