### ISSUE TITLE
请问有没有可能提供一个入口，可以允许直接将构造好的数据结构传递给Httprunner，而不是通过YAML/JSON文件中转

### ISSUE THREAD

**Issue by lopoko** [HttpRunner/HttpRunner#128]
目前HttpRunner提供的构造方法仅能传入YAML/JSON文件路径。如果不希望生成中间文件而是直接将构造好的数据结构传递给HttpRunner是否可行？

**Comment by debugtalk** [comment]
@lopoko 现在还没有这么一个入口，但要实现也挺容易的。但意义在哪儿呢？能说下你期望但使用场景么？

**Comment by lopoko** [comment]
场景是这样的。目前测试数据是存储在 Excel里面。因为数据量比较大（每项测试大约100个步骤，一个test用来完成一个步骤外带验证操作结果），所以使用Python开发了一个工具解析Excel内容然后生成Httprunner所需要的数据结构。所以如果能够直接将从Excel解析出来的数据结构传给Httprunner，就可以避免使用临时的YAML/JSON文件。

**Comment by debugtalk** [comment]
@lopoko 已完成。

http://cn.httprunner.org/development/
