### ISSUE TITLE
go无法引入httprunner4.0的包

### ISSUE THREAD

**Issue by cwk0099** [httprunner/httprunner#1288]
## 问题描述

go无法引入httprunner4.0的包

## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Go 版本:  1.18
 - HttpRunner 版本 4.0

## 项目文件内容（非必须）

![image](https://user-images.githubusercontent.com/37758451/167262190-67703a9c-3dbf-4d9a-bf5b-635e8c4dd945.png)
![image](https://user-images.githubusercontent.com/37758451/167262193-f2264157-a10d-423b-871e-8275f92aead1.png)
![image](https://user-images.githubusercontent.com/37758451/167262201-c85c0bc3-81b1-47cc-b77f-e2bc8dd92ea8.png)

**Comment by cwk0099** [comment]
版本要手动改成
![image](https://user-images.githubusercontent.com/37758451/167262400-ea34271a-da6a-4b24-b165-e814d17a3a47.png)

**Comment by debugtalk** [comment]
@cwk0099 感谢反馈，已经修复了，预计在 v4.1.0 发布。
