### ISSUE TITLE
需求：关于测试数据的删除问题

### ISSUE THREAD

**Issue by JacobHZ** [HttpRunner/HttpRunner#129]
测试场景：创建目录，成功后extract新建的目录ID传给删除接口调用

问题：数据驱动创建目录接口，只能删除最后一个数据驱动生成的目录

需求：给testcase添加teardown，在teardown中能够调用相应的删除接口进行测试数据清除

**Comment by debugtalk** [comment]
@JacobHZ 已经支持 hook 机制了的。

http://cn.httprunner.org/advanced/request-hook/
