### ISSUE TITLE
V4版本是否取消了集成allure报告，运行 hrp pyest XX.py -- alluredir 提示没有这个参数

### ISSUE THREAD

**Issue by colleenle** [httprunner/httprunner#1298]
## 问题描述

V4版本是否取消了集成allure报告，运行 hrp pyest XX.py -- alluredir 提示没有这个参数

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macOS]
 - Python 版本: [3.10]
 - HttpRunner 版本 [4.0]

**Comment by debugtalk** [comment]
@colleenle 在 v4.0 版本中还没有默认安装 pytest allure 插件，你需要自行安装到 `~/.hrp/venv`

`pip install allure-pytest`

后续我们将再内置集成 allure，跟进 issue #1204
