### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by TCT-bag** [httprunner/httprunner#1300]
## 问题描述

>试过2.5.8和2.5.9版本，还是一样报错

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本: [3.10]
 - HttpRunner 版本 [ 2.5.7]

## 项目文件内容（非必须）

![image](https://user-images.githubusercontent.com/105657831/168626751-4159f891-a18d-4636-95ec-0cb6002db469.png)

**Comment by debugtalk** [comment]
@TCT-bag 这个问题是在 Python 3.10 中引入的

https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

**Comment by TCT-bag** [comment]
> @TCT-bag 这个问题是在 Python 3.10 中引入的
> 
> https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python
