### ISSUE TITLE
断言响应时，接口返回value又是一个json字符串，这个时候就不方便取值了

### ISSUE THREAD

**Issue by an5456** [httprunner/httprunner#1307]
## 背景描述
断言响应时，接口返回value又是一个json字符串，这个时候就不方便取值了
> 重点描述遇到的问题：在什么场景下，HttpRunner 当前的功能特性不能（很好地）实现需求。
如果body返回这样的数据，要取出其中type字段的值，目前的框架还没有办法取出来
body= {'address': '{"goodsId": 10893, "goodsName": "HUAWEI", "goodsIntro": [{"type": "P10"}]}'}

## 期望的功能特性
可以对返回body体数字，只要是value是字符串格式字典、列表、json，都可以json.loads()返回，这样就可以取到对应的值

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。
我目前的做法就该源码，在返回body体加了一个判断，
```
    def format_info(self, value):
        if isinstance(value, dict):
            for k, v in value.items():
                if isinstance(v, str) and v.startswith('{') or isinstance(v, str) and v.startswith('['):
                    try:
                        value[k] = json.loads(v)
                    except Exception:
                        value[k] = v
                elif isinstance(v, list):
                    for lis in v:
                        if isinstance(lis, dict):
                            for i, y in lis.items():
                                if isinstance(y, str) and y.startswith('{') or isinstance(v, str) and v.startswith('['):
                                    try:
                                        lis[i] = json.loads(y)
                                    except Exception:
                                        lis[i] = y
                elif isinstance(v, dict):
                    for a, b in v.items():
                        if isinstance(b, str) and b.startswith('{') or isinstance(b, str) and b.startswith('['):
                            try:
                                value[a] = json.loads(b)
                            except Exception:
                                value[a] = b
                self.format_info(v)
        return value
```
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/39398302/169549349-d42e3763-77ef-4934-b4c6-1aeb3f3a395f.png">
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/39398302/169549818-787daded-75d2-49cc-a3dd-e3d3890457c0.png">
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/39398302/169549907-eadab67c-cde7-42d5-bc2e-173d07031748.png">
![image](https://user-images.githubusercontent.com/39398302/169550106-a2b5b338-a17c-4309-b3b6-1bdf7722543b.png)

代码写的比较low，但是能解决问题了，希望大佬能给改进一下

**Comment by debugtalk** [comment]
如果body返回这样的数据，要取出其中type字段的值：
body= {'address': '{"goodsId": 10893, "goodsName": "HUAWEI", "goodsIntro": [{"type": "P10"}]}'}

其实是可以取值的，你可参考下 jmespath 语法：

`body.address.goodsIntro[0].type`

**Comment by shd0812** [comment]
jmespath              1.0.1

如果body返回这样的数据，要取出其中type字段的值：
body= {'address': '{"goodsId": 10893, "goodsName": "HUAWEI", "goodsIntro": [{"type": "P10"}]}'}

其实是可以取值的，你可参考下 jmespath 语法：

body.address.goodsIntro[0].type

返回是None啊

**Comment by shd0812** [comment]
> 如果body返回这样的数据，要取出其中type字段的值： body= {'address': '{"goodsId": 10893, "goodsName": "HUAWEI", "goodsIntro": [{"type": "P10"}]}'}
> 
> 其实是可以取值的，你可参考下 jmespath 语法：
> 
> `body.address.goodsIntro[0].type`

这样返回是None，从`body.address` 已经是None了
