### ISSUE TITLE
集成到allure测试报告时在测试用例的每个步骤打印详细日志

### ISSUE THREAD

**Issue by zixingkong** [httprunner/httprunner#1316]
## 背景描述

> 当场景测试用例包含的步骤较多时，日志里打印的信息是统一放在标准错误输出，需要上下翻动，期望能在每一步提供详细的请求和响应

## 期望的功能特性
测试用例每个步骤打印详细日志

## 示例描述（可选）

自己修改的runner.py,用于实现用例单步日志打印，供参考

![image](https://user-images.githubusercontent.com/3657070/170648320-135845a6-2ca1-4c8c-87e8-855427bd215e.png)

**Comment by colleenle** [comment]
可以问下怎么集成allure吗？按照作者给的方法 自行安装到 ~/.hrp/venv
pip install allure-pytest后 运行 hrp pytext xxx --alluredir=path 会报错--alluredir是无效参数
