### ISSUE TITLE
hrp解压后创建项目中的文件无法执行

### ISSUE THREAD

**Issue by Mr-Siunaus** [httprunner/httprunner#1318]
## 问题描述
>部署好hrp后，利用脚手架创建的项目中的用例无法执行
> D:\httprunner4x>hrp run ./xxx/demo.yml
5:03PM INF Set log to color console other than JSON format.
5:03PM ??? Set log level
5:03PM INF [init] SetFailfast failfast=true
5:03PM INF [init] SetSaveTests saveTests=false
5:03PM INF [init] SetRequestsLogOn
5:03PM INF load file path="xxx\\demo.yml"
5:03PM INF load testcases successfully count=1
5:03PM INF ensure python3 venv packages=["funppy"] python3="C:\\Users\\Administrator\\.hrp\\venv\\Scripts\\python3.exe"
5:03PM INF exec command cmd="python3 --version"
5:03PM ERR exec command failed error="exec: \"python3\": executable file not found in %PATH%"
5:03PM ERR init plugin failed: D:\httprunner4x\xxx\debugtalk.py error="ensure python venv failed: python3 not found: exec: \"python3\": executable file not found in %PATH%"
5:03PM ERR [Run] init session runner failed error="init plugin failed: ensure python venv failed: python3 not found: exec: \"python3\": executable file not found in %PATH%"

## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Python 版本: 3.9
 - Go 版本: 无
 - HttpRunner 版本 4.0.0

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by debugtalk** [comment]
@Mr-Siunaus 这个问题已经修复过，你升级到 v4.1.0-beta 再试下？

**Comment by Mr-Siunaus** [comment]
> @Mr-Siunaus 这个问题已经修复过，你升级到 v4.1.0-beta 再试下？

好的~
