### ISSUE TITLE
v4.1版本，在默认生成的debugtalk.py里面追加了一个函数，运行用例报错了。

### ISSUE THREAD

**Issue by gaku1028** [httprunner/httprunner#1326]
## 问题描述

> 请对 bug 进行简要描述；
在自动生成的debugtalk.py里面只加了一个获取随机字符串的函数（这个函数单独拿出来运行也是能正常获取字符串的），用例也没有引用该函数，结果运行用例报错了，
把这个函数去掉之后，用例又能正常运行，
> 尽量附带运行的命令和报错时的堆栈信息
![image](https://user-images.githubusercontent.com/38396589/171111466-c47c2b5e-d553-494f-8c23-54c175a46eb9.png)

![image](https://user-images.githubusercontent.com/38396589/171111393-1e41c581-6886-423b-b15e-5061cb5e89dc.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g., Windows]
 - Python 版本: [e.g. 3.8]
 - Go 版本: [e.g. 1.18]
 - HttpRunner 版本 [e.g. 4.1]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by debugtalk** [comment]
@gaku1028 感谢反馈，已经在 v4.1.1 版本修复了，麻烦升级下

**Comment by gaku1028** [comment]
> 
升级了之后，我用默认脚手架生成的debugtalk.py，也没动，然后运行了一条用例，还是一样的提示，运行昨天成功用例也一样的提示...
![image](https://user-images.githubusercontent.com/38396589/171329906-70054b89-7c08-4a21-86d3-91cb238b3ee2.png)
