### ISSUE TITLE
关于skip和times方法(v3.1.4)

### ISSUE THREAD

**Issue by Philip0707** [httprunner/httprunner#1332]
## 背景描述

在网上看到之前的版本是支持skip和times方法的，用于跳过用例和指定执行次数。

## 期望的功能特性

在3.1.4版本使用这两个方法失败。请问是已经移除这两个功能了吗？
现在想实现跳过某条用例或者某个API，请问如何实现？(用例是py, 不是yml/json)
非常感谢！

**Comment by debugtalk** [comment]
ref #1045
