### ISSUE TITLE
hrp v4.1.1执行hrp run报错ERR call function failed

### ISSUE THREAD

**Issue by yuanzhen-dong228** [httprunner/httprunner#1340]
hrp run testcases/create_doc_parameters_test.json 报错找不到function, 但是function已经加在debugtalk.py了

ref link:
https://ceshiren.com/t/topic/21113

**Comment by bbx-winner** [comment]
@yuanzhen-dong228 感谢反馈，可以总结为 3 个问题：
1. debugtalk.py 中自定义的函数，在 config 参数驱动中引用时无法找到定义
2. hrp run 兼容 v4 之前的测试用例格式时报错，已经定位到该空指针异常
3. hrp run 会忽略 pseudo header (e.g. :authority, :method, :path, :scheme)

**Comment by yuanzhen-dong228** [comment]
感谢🙏

**Comment by debugtalk** [comment]
pseudo-headers 的问题已在 v4.1.4 中修复

https://github.com/httprunner/httprunner/issues/1339
