### ISSUE TITLE
在debugtalk中引入第三方库时，提示error="connect grpc plugin failed: Unrecognized remote plugi

### ISSUE THREAD

**Issue by 406722575** [httprunner/httprunner#1353]
## 问题描述

封装了读取yaml的方法类名为 WrYaml，from ruamel import yaml为安装的库，
![image](https://user-images.githubusercontent.com/39303693/173312979-69e1c386-a05e-4fa0-8e61-4eee2f60aacb.png)
在debugtalk中引入该类from Common import WrYaml，运行时提示如下
![image](https://user-images.githubusercontent.com/39303693/173313288-646668a9-f758-4cf2-9c75-99f5a2abac8f.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows10]
 - Python 版本: [3.10]
 - Go 版本: [e.g. 1.18]
 - HttpRunner 版本 [4.1.2]

**Comment by debugtalk** [comment]
@406722575 该问题已在 v4.1.3 修复，你升级后再试试，有问题再反馈哈。

**Comment by 406722575** [comment]
@debugtalk 
最新的版本试了，没有解决
![image](https://user-images.githubusercontent.com/39303693/173757647-2eab9659-9656-4d24-8892-8e9958bb9409.png)

**Comment by xizibai** [comment]
> @debugtalk 最新的版本试了，没有解决 ![image](https://user-images.githubusercontent.com/39303693/173757647-2eab9659-9656-4d24-8892-8e9958bb9409.png)
同上反馈

**Comment by hancelChiu** [comment]
我也遇到了这个问题，麻烦问一下解决了吗
