### ISSUE TITLE
数据驱动多个参数关联时能否支持关联参数的引用？

### ISSUE THREAD

**Issue by luochun3731** [HttpRunner/HttpRunner#136]
`[
    {
        "username-password":[
            [
                "username1",
                "password1"
            ],
            [
                "username2",
                "password2"
            ]
        ]
    }
]`
现有需求：与参数password关联的username参数需被引用，目前貌似是不支持的吧？请问能否增加这种参数引用的功能？

**Comment by debugtalk** [comment]
@luochun3731 支持的。详细用法看文档：

http://cn.httprunner.org/advanced/data-driven/
