### ISSUE TITLE
脚手架工程运行hrp run yml用例，提示 build plugin failed error="python plugin syntax invalid: exit status 9009"

### ISSUE THREAD

**Issue by HJXDELL** [httprunner/httprunner#1366]
## 问题描述

> 1.  hrp startproject hrpv4  
> 2. 执行 hrp run testcases\requests.yml -g

`
(venv) E:\dev\httprunner-v4\hrpv4>hrp run testcases\requests.yml -g
3:08PM INF Set log to color console other than JSON format.
3:08PM ??? Set log level
3:08PM INF [init] SetFailfast failfast=true
3:08PM INF [init] SetSaveTests saveTests=false
3:08PM INF [init] SetgenHTMLReport genHTMLReport=true
3:08PM INF [init] SetRequestsLogOn
3:08PM INF load file path="testcases\\requests.yml"
3:08PM INF load file path="E:\\dev\\httprunner-v4\\hrpv4\\.env"
3:08PM INF set env key=base_url
3:08PM INF set env key=USERNAME
3:08PM INF set env key=PASSWORD
3:08PM INF load testcases successfully count=1
3:08PM INF exec command cmd="C:\\WINDOWS\\system32\\cmd.exe /c python3 -m py_compile E:\\dev\\httprunner-v4\\hrpv4\\debugtalk.py"
3:08PM ERR exec command failed error="exit status 9009"
3:08PM ERR build plugin failed error="python plugin syntax invalid: exit status 9009" path="E:\\dev\\httprunner-v4\\hrpv4\\debugtalk.py"

`
## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g.  Windows]
 - Python 版本: [e.g. 3.8]
 - HttpRunner 版本 [e.g. 4.1.3]

## 项目文件内容（非必须）

![image](https://user-images.githubusercontent.com/8569167/174013395-38cf2c2d-1947-40b1-a77b-557f04a6318e.png)

**Comment by debugtalk** [comment]
@HJXDELL 该问题已修复，将在 v4.1.4 中发布。

https://github.com/httprunner/httprunner/pull/1360
