### ISSUE TITLE
关于用例结构的疑问

### ISSUE THREAD

**Issue by wjian2580** [HttpRunner/HttpRunner#138]
您好，在加载用例文件的时候有这样的代码片段

```   
 elif os.path.isfile(path):
        try:
            testset = load_test_file(path)
            if testset["testcases"] or testset["api"]:
                testcases_list = [testset]
            else:
                testcases_list = []
```

请问一个测试集的结构不是一个config和多个test，代码中为什么是 testcases和api

另外创建scaffold的时候是 api,suite,testcases,debugtalk这样的结构，请问这样的结构怎么对测试用例进行分层

**Comment by debugtalk** [comment]
@wjian2580 可以参考如下文档：

http://debugtalk.com/post/HttpRunner-testcase-layer/
