### ISSUE TITLE
JmesPath存在“-”的时候，返回null

### ISSUE THREAD

**Issue by sunhao1256** [httprunner/httprunner#1395]
## 问题描述

```yml
body.data[?id=='sh-shanghai'].ref => null
body."data[?id=='sh-shanghai']".ref => []
body.data[?ref == '"cn-qingdao"'].id=>[]
```
## 版本信息
4.1.3

**Comment by sunhao1256** [comment]
`0AM INF extract value from="body.\"data[?name == '华东2（上海）']\".id" value=null

会自动增加“”导致null

11:20AM INF set variable value=null variable=regionId
11:20AM INF validate status_code assertMethod=eq checkExpr=status_code checkValue=200 checkValueType=int64 expectValue=200 expectValueType=int64 result=true
11:20AM INF run step end exportVars={"regionId":null} step=listRegion success=true type=api
11:20AM INF run step start step=createVpc type=api
`

**Comment by yajuanhe** [comment]
> ## 问题描述
> ```yaml
> body.data[?id=='sh-shanghai'].ref => null
> body."data[?id=='sh-shanghai']".ref => []
> body.data[?ref == '"cn-qingdao"'].id=>[]
> ```
> 
> ## 版本信息
> 4.1.3

请尝试使用以下方式查看是否能解决你的问题
.with_jmespath(jmes_path="headers.\"Allow-Token\"", var_name="allow_token")
