### ISSUE TITLE
如何提取response headers？

### ISSUE THREAD

**Issue by ztwo** [HttpRunner/HttpRunner#141]
有些特殊需求，不能使用requests.session特性。需要提取 response headers内的数据。

我看文档有有提到，但调用失败：
响应结果为 JSON 结构，可采用.运算符的方式，例如headers.Content-Type、content.success；

```yaml
extract:
 -   sess: ${get_sess(headers)}
```

问题：如何利用extract 提取出response headers，作为变量使用？

**Comment by wangbooth** [comment]
```
"extract": [
                {
                    "my_header_1": "headers"
                }
            ]
```

这样就能提取出来 response headers， 作为变量 my_header_1 的值。

使用的时候， 要注意一下：

```
                "json": {
                    "header1": "\"$my_header_1\""
                }
```

`$my_header_1` 不是`json`格式的数据， 而是`requests.structures.CaseInsensitiveDict`，也就是一个dict类型的数据， 所以`request`用的时候不能直接把`$my_header_1` 塞进去用， 而要先转换一下， 将dict转为str或者json

**Comment by ztwo** [comment]
@wangbooth 感谢你的恢复，问题得到了解决
