### ISSUE TITLE
httprunner v4.1.6 , 运行 har2case， 显示 -bash: har2case: command not found

### ISSUE THREAD

**Issue by matthewxuda** [httprunner/httprunner#1418]
## Describe the bug

> Please give a brief description of the bug;
> attach the running command and the stack information when the error is reported

## Versions v4.1.6

Please complete the following information:

- OS Type: [e.g. macOS, Linux, Windows]
- Python version: [e.g. 3.9]  3.8
- Go version: [e.g. 1.18]
- HttpRunner version [e.g. 3.1.8] v4.1.6

## Project files (If possible)

Provide your project files to help locate and debug bugs faster. This is not mandatory.

NOTICE: Before uploading your project files, don't forget to remove sensitive data, e.g. IP, username and password, key info etc.
![image](https://user-images.githubusercontent.com/5927005/179499413-6cae0830-3590-4bdf-9248-67bcd0461aa1.png)

**Comment by debugtalk** [comment]
@matthewxuda 在 v4 中，已经没有单独的 `har2case` 命令，替换为 `hrp convert` 命令。
