### ISSUE TITLE
提示command not found: hrp

### ISSUE THREAD

**Issue by UserFarmer** [httprunner/httprunner#1455]
安装版本v4.2.0，始终提示找不到hrp命令，如果用以前的har2case和hrun仍可以正常执行
系统Apple M1 macOS

**Comment by debugtalk** [comment]
你需要使用如下命令进行安装：

```bash
$ bash -c "$(curl -ksSL https://httprunner.com/script/install.sh)"
```

如果使用 pip 安装，只安装了 python 部分，不包含 goalng 的 hrp 部分。
