### ISSUE TITLE
接口测试报告（Go template）部分内容显示变量或格式异常

### ISSUE THREAD

**Issue by BoxTester** [httprunner/httprunner#1468]
## 问题描述

> 接口测试报告（Go template）部分内容显示变量或格式异常
> 

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本: [3.7]
 - Go 版本: [1.18]
 - HttpRunner 版本 [4.2.0]

## 项目文件内容（非必须）

![report](https://user-images.githubusercontent.com/37102283/188767422-890a0faf-adcb-402c-babc-5f4d194d9519.png)

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by ywanbing** [comment]
这个我看有些人，就需要这个变量，有的又要值。
我自己是实现了这个功能。但是目前不清楚状况，所以才没有pr的打算。

**Comment by ywanbing** [comment]
这个确实有用，应该加上😁

**Comment by ywanbing** [comment]
修复 url 变量显示改为 值显示。
