### ISSUE TITLE
报错 jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'response_time'

### ISSUE THREAD

**Issue by ebaocloud-ops-cn** [HttpRunner/HttpRunner#152]
今天下午pip install的HTTPRunner跑hrun生成report时报错：
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'response_time'

将report.py回退至大约一周前的版本就运行正常。

**Comment by debugtalk** [comment]
@ebaocloud-ops-cn 可否提供下报错堆栈，或者你的测试脚本？

**Comment by ebaocloud-ops-cn** [comment]
刚才尝试重现报错的时候，同一测试脚本又运行正常了。
pip 卸载httprunner再重新pip安装后也无法重现。

**Comment by ebaocloud-ops-cn** [comment]
能重现了：

----------------------------------------------------------------------
Ran 5 tests in 3.579s

OK
INFO     render with html report template: report_dynamic.html
INFO     Start to render Html report ...
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'response_time'

**Comment by ebaocloud-ops-cn** [comment]
另report.py回退至一周前的版本后，能够生成report， 但report details表里的response_time都为零。

**Comment by ebaocloud-ops-cn** [comment]
log info:

**Comment by ebaocloud-ops-cn** [comment]
Log info:
...
                            'response_time(ms)': 2549.55,
                            'status_code': 200,
                            'url': u'/pa/api/v1/vehicle/quotation'},
              'name': '/pa/api/v1/vehicle/quotation',
              'response_time': 0,
              'status': 'success'}],
 'stat': {'errors': 0,
          'expectedFailures': 0,
          'failures': 0,
          'skipped': 0,
          'successes': 6,
          'testsRun': 6,
          'unexpectedSuccesses': 0},
 'success': True,
 'time': {'duration': 7.717307090759277,
          'start_at': datetime.datetime(2018, 4, 5, 13, 53, 8, 731508)}}

**Comment by debugtalk** [comment]
@ebaocloud-ops-cn 定位到问题了。是因为上次我调整测试报告这块儿的时候，给响应时间添加了单位，对应地，response_time 也改为了 response_time_ms。
在你自定义的 Jinja 模版中，将 response_time 调整为 response_time_ms 就可以了。
