### ISSUE TITLE
hrp run 嵌套case，report生成失败

### ISSUE THREAD

**Issue by jonzha9527** [httprunner/httprunner#1547]
## 问题描述
hrp 执行嵌套用例，生成报告失败

hrp 是下载的二进制文件，V4.3.0
通过脚手架生成项目，命令如下：
hrp run -s -g testcases/ref_testcase.yml

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/43426348/211262914-432d9abf-789a-4e4a-918d-e66cb334d0c1.png">

## 版本信息

 - 操作系统类型: 
mac M1

 - Python 版本:
v3.10.9

- HttpRunner 版本
v4.3.0

**Comment by jiwzh** [comment]
同样问题啊。.

**Comment by ywanbing** [comment]
@jiwzh @jonzha9527  这是由于引用case的时候，在 `(*StepTestCaseWithOptionalArgs).Run` 中 的差异行为
![image](https://user-images.githubusercontent.com/30226135/232689364-df1f7b4e-17f5-411b-af1c-f0473ead939f.png)

和 其他单个step 的操作记录不同
![image](https://user-images.githubusercontent.com/30226135/232689516-d7d20ed5-0ec2-4bcb-9db3-dace1f6084a7.png)
