### ISSUE TITLE
测试报告中response_body为form表单+js脚本（实际上就是返回一个二维码）时，打开报告直接跳转到了二维码，无法查看报告内容

### ISSUE THREAD

**Issue by luochun3731** [HttpRunner/HttpRunner#155]
HttpRunner版本：1.3.7

接口返回的response_body如下：
`"response_body": "
                  <form id='frmID' name='frmName' method='post' action='https://public.baofoo.com/platform/business/gateway/show?codeUrl=aHR0cHM6Ly9xci5hbGlwYXkuY29tL2JheHdpYm1ydzFjaWR1c3Q0Mw=='></form>
                  <script language='javascript'>document.getElementById('frmID').submit();</script>"`

**Comment by debugtalk** [comment]
@luochun3731 感谢反馈，这就是典型的[跨站脚本攻击（XSS）](http://docs.jinkan.org/docs/flask/security.html#xss)问题。

**Comment by debugtalk** [comment]
@luochun3731 升级到 1.3.8.b2 ：

```
pip install -U httprunner --pre
```

**Comment by luochun3731** [comment]
升级到 1.3.8.b2后，经验证问题已修复。
