### ISSUE TITLE
hrp run嵌套的testcase，grpc-py就会报错导致report无法生成

### ISSUE THREAD

**Issue by jonzha9527** [httprunner/httprunner#1553]
我这边也是一直存在这个问题，只要运行嵌套的testcase，就会报错导致report无法生成
尝试了mac，Windows，docker 执行都是一样的结果，和Python版本无关，就是**grpc-py** 的问题
### 这个bug覆盖面太大了，所有嵌套的case都无法执行，麻烦尽快fix

`hrp run debug/ref_testcase.yml -g -c`
![image](https://user-images.githubusercontent.com/43426348/213353303-13aed729-1c20-4615-acd5-73653e295d93.png)
![image](https://user-images.githubusercontent.com/43426348/213353386-1fb6bb10-00e0-428e-bbcd-094608382da5.png)

_Originally posted by @jonzha9527 in https://github.com/httprunner/httprunner/issues/1237#issuecomment-1396417885_

![image](https://user-images.githubusercontent.com/43426348/213354203-27cd5f56-c069-46e7-a580-3c8e0760cbc5.png)

**Comment by dragonleeee** [comment]
我这两天也为这个问题发愁呢，麻烦大大们，解决一下

**Comment by chenzuge60** [comment]
有解决办法了么，我嵌套api同样报这个错，且用例无法执行

**Comment by dragonleeee** [comment]
降级 到4.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 下午4:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [httprunner/httprunner] hrp run嵌套的testcase，grpc-py就会报错导致report无法生成 (Issue #1553)





 
有解决办法了么，我嵌套api同样报这个错，且用例无法执行

**Comment by jonzha9527** [comment]
> 降级 到4.2
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月23日(星期四) 下午4:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [httprunner/httprunner] hrp run嵌套的testcase，grpc-py就会报错导致report无法生成 (Issue #1553) 有解决办法了么，我嵌套api同样报这个错，且用例无法执行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

4.2.0版本确实可以，虽然还是有warning，但是report可以正常生成了
这个bug在后续版本会fix么？
