### ISSUE TITLE
hrp命令参数太少了

### ISSUE THREAD

**Issue by jonzha9527** [httprunner/httprunner#1563]
## 4.x 的命令行功能缩减了好多

> 之前使用3.X版本的hrun命令，支持pytest 的参数，log日志
> 现在4.x 的hrp run 功能缩减了好多，report名称，summary 等都不能自定义，控制台的日志log也不生成了

## 期望保留3.X  的命令行的功能

> 不要把3.X 的核心功能都取消，保留日志文件生成，自定义HTML文件，pytest 参数等

**Comment by debugtalk** [comment]
如果期望使用 pytest 相关能力，可以运行：

```
hrp pytest -h
```
