### ISSUE TITLE
在httprunner下使用locust，运行压测，web端看不到输出

### ISSUE THREAD

**Issue by ccmteorljh** [HttpRunner/HttpRunner#159]
http://debugtalk.com/post/apitestengine-supersede-locust/
在该教程下，使用locustfile.py，然后运行命令
locust -f locustfile.py
启动web后，输入参数：
![image](https://user-images.githubusercontent.com/33303691/38594307-39ff0b12-3d78-11e8-9968-60c8e5e13ab7.png)

运行结果如下：
![image](https://user-images.githubusercontent.com/33303691/38594331-58196c82-3d78-11e8-80fe-153e9c9f4cee.png)

后端日志显示一直在持续发送请求，但是web端看不到任何请求时间，请求地址，统计信息等；
正常情况下，locust显示的是task的client的请求，以及响应的统计信息；
但是上述教程task里面运行了所有的任务；
请问，这种可以显示具体的请求信息吗？

**Comment by ccmteorljh** [comment]
![image](https://user-images.githubusercontent.com/33303691/38561249-2134c0ea-3d0a-11e8-9378-2a3c8acc74eb.png)

**Comment by debugtalk** [comment]
@ccmteorljh 这是你在运行 locust 时遇到的问题，还没有涉及到 HttpRunner。

出现你这种情况，可能是你的测试机访问不到被测系统，请求超时造成的。建议你先检查下。

**Comment by ccmteorljh** [comment]
代码如下,其中test_ymal_cases是运行的yaml格式的case，后台输出，这三个task都在运行，但是yaml格式的无法在web端统计出里面包括的具体case,而其他的两个task则可以统计出来：
![image](https://user-images.githubusercontent.com/33303691/38788443-449e6ac6-4166-11e8-8634-0bcc80bd0dbd.png)
请问，这种情况下，如何将yaml 里面的具体case的运行统计像其他task一样输出到web端
class WebPageTasks(TaskSet):
    def on_start(self):
        self.test_runner = runner.Runner()
        self.testset = self.locust.testset
    @task
    def test_ymal_cases(self):
        self.test_runner._run_testset(self.testset)

    @task
    def index(self):
        self.client.get("/")

    @task
    def about(self):
        self.client.get("/about/")
class WebPageUser(HttpLocust):
    host = 'http://debugtalk.com'
    task_set = WebPageTasks
    min_wait = 1000
    max_wait = 5000
    testcase_file_path = os.path.join(base_conf.ROOT_PATH,
            'system/cases/user_cases/cases_test_user.yml')
    testsets = testcase.load_testcases_by_path(testcase_file_path)
    testset = testsets[0]
    print testset
