### ISSUE TITLE
创建脚手架项目报错

### ISSUE THREAD

**Issue by YoGazz** [httprunner/httprunner#1618]
## 问题描述

> 请对 bug 进行简要描述；
> 使用命令创建脚手架项目报错：hrp startproject demo --y

![image](https://github.com/httprunner/httprunner/assets/37612998/a7ad434d-fe84-4621-89b2-ba8949b924b6)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: MacOS12.3
 - Python 版本: 3.8
 - 
 - Go 版本:1.18
 - HttpRunner 版本: 4.3.0

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by YoGazz** [comment]
解决办法：
降级urllib3库
pip install urllib3==1.26.15

**Comment by suzhenyu006** [comment]
我创建脚手架也遇到问题了：
系统：macOs X86
命令：./hrp startproject
就报了这么一个error
Error: accepts 1 arg(s), received 0
{"level":"warn","code":1,"time":"2023-06-25T17:47:51+08:00","message":"hrp exit"}
