### ISSUE TITLE
测试用例拆分

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#162]
当很多的测试用例都要使用一个extract的值时比如登陆用的token，文档会变得很长，有没有什么办法去做文档拆分，将这些被很多测试用例使用的东西都放入一个单独的文档里并且可以被其它文档调用？

**Comment by JacobHZ** [comment]
测试用例分层就能解决这个问题了
http://debugtalk.com/post/HttpRunner-testcase-layer/

**Comment by Renyqin** [comment]
这功能好棒，谢谢了
