### ISSUE TITLE
request 参数支持包含 $ 字符

### ISSUE THREAD

**Issue by debugtalk** [HttpRunner/HttpRunner#163]
请求参数中某个数值为 `0$1$2`，运行测试时会报错“$1 和 $2 变量不存在”。

**Comment by debugtalk** [comment]
duplicate with #101

**Comment by debugtalk** [comment]
fixed in 2.1.2

**Comment by biaogebest** [comment]
问题还存在 有什么方法可以绕过吗

**Comment by debugtalk** [comment]
https://github.com/httprunner/httprunner/issues/682
