### ISSUE TITLE
validator 支持 jmespath 语法

### ISSUE THREAD

**Issue by Bu1eCat** [httprunner/httprunner#164]
在提取返回值进行校验的时候，发现validator提取body中，字段值数据为列表字典嵌套结构数据时，始终无法提取。
![image](https://user-images.githubusercontent.com/21081337/38713434-b0fe0a9c-3f03-11e8-8e4c-80d8334e8352.png)
使用
```
- eq: ["body.bodyMessage.0.Uid","20162880"]
```
![image](https://user-images.githubusercontent.com/21081337/38713478-fd163aa8-3f03-11e8-9672-b06d330a20ac.png)
请问楼主，这种情况下是否只能使用正则表达式。

**Comment by debugtalk** [comment]
@Bu1eCat 返回的数据结构为 XML 么？

**Comment by Bu1eCat** [comment]
返回数据是第一张截图，是JSON格式的。
```json
 "response_body":{
“bodyMessage”=[{"Uid":20162880,"UserName":"XT3035985"}]
“code”=0
“message”=“查询用户成功”
}
```
提取code\message 正常的数据结构可以成功。
```
- eq: ["body.code","0"]
 - eq: ["body.message","查询用户成功"]
```
问题为：提取bodyMessage的value时，由于数据结构为数组嵌套字典格式，使用`.`方法提取时，就不能使用了.
```
- eq: ["body.bodyMessage.0.Uid",20162880]
```

**Comment by debugtalk** [comment]
@Bu1eCat 你的整体为JSON没错，但是bodyMessage部分为字符串，所以不能再用点运算符。
针对你这种情况，可以使用自定义的检验器。

**Comment by 781412862** [comment]
自定义的校验器怎么用，我记得其他工具可以使用这种方法
["body.bodyMessage[0].Uid","20162880"]
因为是一个数组，index是0
但是发现[]外还有一个[]，这里就冲突了。
实际环境中这样的数据很多，如果都转换json在取值，有点麻烦了

**Comment by Bu1eCat** [comment]
截图看看你的返回值结构。应该是需要用自己写函数的。




| |
黄达标
测试工程师
|
|
上海博协软件有限公司
13723866040
邮箱：calmpeter@163.com
上海市普陀区真南路150号
|

签名由 网易邮箱大师 定制

在2018年07月27日 09:56，781412862 写道：

自定义的校验器怎么用，我记得其他工具可以使用这种方法
["body.bodyMessage[0].Uid","20162880"]
因为是一个数组，index是0
但是发现[]外还有一个[]，这里就冲突了。
实际环境中这样的数据很多，如果都转换json在取值，有点麻烦了

**Comment by searchbb** [comment]
目前通过点点的方式提取json非常不灵活，比如不知道在一个list中的位置就没法处理了，我手工加了一个支持jmespath语法的hack，提取功能强大多了，宝宝再也不哭了~~
![1](https://user-images.githubusercontent.com/42245656/46242684-25e9f800-c3fe-11e8-84a6-68e9666bef03.png)
<img width="896" alt="2" src="https://user-images.githubusercontent.com/42245656/46242687-2bdfd900-c3fe-11e8-86f4-1e528321bfd3.png">
<img width="845" alt="3" src="https://user-images.githubusercontent.com/42245656/46242688-30a48d00-c3fe-11e8-9fbe-bada4ca6248d.png">

 @debugtalk 建议框架也安装这个思路改下，代码变动少，语法基本一样，除了那个list.0要改成list[0]

**Comment by debugtalk** [comment]
@searchbb 感谢反馈，后续我考虑兼容支持下。

**Comment by idle-man** [comment]
> @searchbb 感谢反馈，后续我考虑兼容支持下。

可以考虑在validate生成的时候就自动按照jmespath的格式来生成所有的eq吧？附一个我之前写的方法，代码应该还有很大优化空间，仅供参考：

`# 遍历字典/列表，以层级深度为1的目标，获取到所有的key/value对
    def get_all_items(self, item, prefix='', mode=1):
        """
        :param item: 一个字典或列表，无论深度如何
        :param prefix: key的前缀，默认为空，递归时会用到
        :param mode: 输出模式，1-value为纯扁平模式，0-各级value均保存
        :return: 字典，深度为1的key/value对
        """
        my_items = {}
        if isinstance(item, dict):
            if len(item) == 0:
                my_items[prefix] = {}
            for x in range(len(item)):
                t_key = item.keys()[x]
                t_val = item[t_key]
                if prefix != '':
                    t_key = str(prefix) + "." + str(t_key)
                else:
                    pass
                if not (mode and isinstance(t_val, (dict, list, tuple, set))):
                    my_items[t_key] = t_val
                my_items = dict(my_items.items() + self.get_all_items(item=t_val, prefix=t_key).items())
        elif isinstance(item, (list, set, tuple)):
            if len(item) == 0:
                my_items[prefix] = []
            for x in range(len(item)):
                if prefix != '':
                    t_key = "%s[%d]" % (prefix, x)
                else:
                    t_key = "[%d]" % x
                if not (mode and isinstance(item[x], (dict, list, tuple, set))):
                    my_items[t_key] = item[x]
                my_items = dict(my_items.items() + self.get_all_items(item=item[x], prefix=t_key).items())
        else:  # the end level
            if prefix == '':
                my_items[item] = ''

        return my_items`
