### ISSUE TITLE
测试用例分层文件目录结构

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#165]
看了一下debugtalk博客（http://debugtalk.com/post/HttpRunner-testcase-layer/）  写的测试用例文件结构test*： 
想请问一下，如果是下面这样的结构是否合法？
✗ tree tests
tests
|──test1
|──test2
|──test3

test1,2,3 的内部结构都和test*一致

test*
├── api
│   └── v1
│       ├── Account.yml
│       ├── BusinessTrip.yml
│       ├── Common.yml
│       └── Leave.yml
├── debugtalk.py
├── suite
│   ├── BusinessTravelApplication
│   │   ├── approve-application.yml
│   │   ├── executive-application.yml
│   │   ├── reject-application.yml
│   │   └── submit-application.yml
│   └── LeaveApplication
│       ├── approve.yml
│       ├── cancel.yml
│       └── submit-application.yml
└── testcases
    ├── scenario_A.yml
    ├── scenario_B.yml
    └── scenario_C.yml

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/
