### ISSUE TITLE
一键安装命令报错了

### ISSUE THREAD

**Issue by mmy83** [httprunner/httprunner#1652]
一键安装命令报错了

**Comment by mmy83** [comment]
手动按照发现没有最新的linux-amd版本，于是下载了4.3.3版本，安装后报错
<img width="742" alt="image" src="https://github.com/httprunner/httprunner/assets/4033717/7e37a84e-2987-424f-9578-72c75a948d63">
 
环境：ubuntu 22.04-server 

mac也是类似错误，手动执行 pip install httprunner==v4.3.3可以正常安装

**Comment by mmy83** [comment]
通过手动安装PYYAML-5.4.1解决，，，需要手动把包解压，修改里面是setup.cfg文件，然后才能安装上

**Comment by debugtalk** [comment]
已在 v4.3.5 解决

**Comment by YoGazz** [comment]
> 已在 v4.3.5 解决

大佬v4.3.5能解决POST请求，接口路径后面会自动拼接”/“的问题吗

**Comment by Lyzin** [comment]
> 通过手动安装PYYAML-5.4.1解决，，，需要手动把包解压，修改里面是setup.cfg文件，然后才能安装上

需要改setup.cfg什么内容呀
