### ISSUE TITLE
测试用例分层机制执行报错

### ISSUE THREAD

**Issue by juliansgit** [HttpRunner/HttpRunner#167]
自己按照测试用例分层机制谢了一个用户登录的用例，执行报错：
httprunner.exception.SuiteNotFound: suite login not found!
按照examples中的用例执行，同样报错：
httprunner.exception.SuiteNotFound: suite setup_and_reset not found!
然后分别执行suite和api中的用例，API中抛异常如下：
DEBUG    No html report template specified, use default.
INFO     Start to render Html report ...
DEBUG    render data: {'success': True, 'stat': {'testsRun': 0, 'failures': 0, 'errors': 0, 'skipped': 0, 'expectedFailures': 0, 'unexpectedSuccesses': 0, 'su
ccesses': 0}, 'platform': {'httprunner_version': '1.3.7', 'python_version': 'CPython 3.6.2', 'platform': 'Windows-10-10.0.16299-SP0'}}
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\httprunner\cli.py", line 83, in main_hrun
    html_report_template=args.html_report_template
  File "c:\python\lib\site-packages\httprunner\task.py", line 234, in run
    html_report_template
  File "c:\python\lib\site-packages\httprunner\report.py", line 167, in render_html_report
    start_datetime = summary["time"]["start_at"].strftime('%Y-%m-%d-%H-%M-%S')
KeyError: 'time'

请问是什么原因？

**Comment by JacobHZ** [comment]
先理解清楚完整的用例分层原理。

api用例中都没有test关键字，怎么能去执行呢？

用例分层的执行方法和单个用例是不一样的：hrun tests/testcases/xxx.yml
不是在testcases目录下运行hrun xxx.yml

**Comment by juliansgit** [comment]
谢谢，用例分层的问题解决了

**Comment by scuwjw** [comment]
> 先理解清楚完整的用例分层原理。
> 
> api用例中都没有test关键字，怎么能去执行呢？
> 
> 用例分层的执行方法和单个用例是不一样的：hrun tests/testcases/xxx.yml
> 不是在testcases目录下运行hrun xxx.yml

请问有用例分层原理的介绍么？
看官网这个是空页面：https://cn.httprunner.org/advanced/testcase-layer/
