### ISSUE TITLE
测试用例分层如何 extract value？

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#168]
比如login 想获取token的值，有没有办法调用分层了的def login返回出一个content.token或者可以在外部access之类的？

**Comment by debugtalk** [comment]
@Renyqin 可以的，你可以将 extract 定义在 api 中。在运行测试用例的时候，会先加载api中的定义，并将定义中的内容与test中的内容进行组合形成最终的test，然后才执行测试。
