### ISSUE TITLE
yaml文件提取变量中有-符号时，执行用例会jmespath会报错

### ISSUE THREAD

**Issue by annewwang** [httprunner/httprunner#1742]
## 问题描述
yaml文件提取变量中有-符号，执行用例会jmespath会报错
```
extract:
  cookie: headers.Set-Cookie
```
![image](https://github.com/httprunner/httprunner/assets/76645260/e213d652-2d9d-4a1f-9c9d-88e826cbb04a)

## 版本信息

版本信息：

 - 操作系统类型：Windows
 - Python 版本：3.7
 - HttpRunner 版本 ：4.3.5

**Comment by dragonleeee** [comment]
这不是bug，看文档 有说的，带"-"要加引号，像这样 headers.“Set-Cookie”

**Comment by annewwang** [comment]
谢谢大家，修改了写法，已解决： 
```
cookie: headers.\"Set-Cookie\"
```
