### ISSUE TITLE
分层测试时，base_url不能满足多域名联合测试

### ISSUE THREAD

**Issue by ferhas** [HttpRunner/HttpRunner#175]

**Comment by debugtalk** [comment]
如果有多域名，那就不用写 base_url，在各个 test 中使用完整的 url 即可。

**Comment by ferhas** [comment]
可以，但是生产和测试环境切换不方便

**Comment by debugtalk** [comment]
你可以把 host 统一放置在 debugtalk.py 中，并采用读取环境变量的方式，在测试用例中进行引用。需要切换时，只需要更改环境变量即可。

**Comment by steven-xgt** [comment]
@debugtalk 可不可以在testcases中不设置base_url，而只在suite中设置base_url？我试了一下，好像不行，不知道是不是不支持
