### ISSUE TITLE
数据驱动使用文档

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#176]
看了博客数据驱动那章 http://debugtalk.com/post/httprunner-data-driven/#csv-%E8%A7%A3%E6%9E%90%E5%99%A8
没有看懂最后的效果展示时数据源文档是从哪里引入的， 以及csv文档是否放在同一个文件夹，还是放在特定文件夹中？
能否给一个数据驱动的使用文档？
查询了过往issues中回复所给的使用文档显示404： http://cn.httprunner.org/data-driven/

**Comment by debugtalk** [comment]
http://cn.httprunner.org/advanced/data-driven/
