### ISSUE TITLE
hook机制，teardown_hooks

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#182]
validate 是否在teardown_hooks 之后执行？ 想使用teardown_hooks对response object做个性化处理然后再进行validate，这种方式是否可行？

**Comment by debugtalk** [comment]
validate 的确是在 teardown_hooks 之后执行的。
你说的那种方式可行。

**Comment by liwenliali** [comment]
需要先断言再做数据清理，这里怎么处理呢，求帮助
