### ISSUE TITLE
调试单个用例如果调用API下的内容，会提示APINotFound

### ISSUE THREAD

**Issue by testwangchao** [HttpRunner/HttpRunner#184]
目录结构
![image](https://user-images.githubusercontent.com/24589400/38976908-3de1ecea-43e5-11e8-9471-9a65a4921fb2.png)

单个用例调试会提示APINotFound
![image](https://user-images.githubusercontent.com/24589400/38976788-e518464a-43e4-11e8-946f-1f6d04cdecf7.png)

但是在tests目录下执行没有问题，有个疑问：如果调用API下的内容，必须在在tests目录下执行么？
![image](https://user-images.githubusercontent.com/24589400/38976963-6d7be5c8-43e5-11e8-961b-652f24041696.png)

**Comment by JacobHZ** [comment]
https://github.com/HttpRunner/HttpRunner/issues/167
