### ISSUE TITLE
像 skipIf 这种条件判断是否应该优先级最高比较好

### ISSUE THREAD

**Issue by zhengxs2018** [httprunner/httprunner#192]
比如如下的用例，我的期望是如果没有拿到登录的用户ID，就不执行这个用例，但是实际却是 parameters 比 skipIf 的优先级还要高

![image](https://user-images.githubusercontent.com/7506913/39082240-659ec430-4582-11e8-9a06-d85f707790fc.png)

![image](https://user-images.githubusercontent.com/7506913/39082233-4997b3be-4582-11e8-8cbf-17192d2d0983.png)

执行用例的过程中还发现了几个问题：
 1. name 中无法使用 output 出的变量
 2. parameters 无法使用 context 中的变量
 3. parameters 无法和 suite 待在一个 test 中
 4. 使用 skipIf 跳过的接口，它的请求数据和响应数据是上一条的，这是为什么？

**Comment by zhengxiansen** [comment]
有木有交流群，微信群，qq群，这些地方可以交流的
