### ISSUE TITLE
"Optional int parameter 'num' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive 

### ISSUE THREAD

**Issue by FrancisJen** [httprunner/httprunner#193]
ERROR    500 Server Error:  for url: http://IP和端口/service/generateTransId
ERROR    request:
headers: {'content-type': 'application/x-www-form-urlencoded', 'accept': 'application/json'}
json: {'platform': 'front', 'num': '1'}

ERROR    response:
status_code: 500
headers: {'X-Application-Context': 'gds-server:sit:18085', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 23 Apr 2018 06:23:49 GMT', 'Connection': 'close'}
body: {"timestamp":1524464629507,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"Optional int parameter 'num' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type.","path":"/service/generateTransId"}

配置文件：
- test:
    name: get transID
    request:
        url: http://IP和端口/service/generateTransId
        method: POST
        headers:
            Content-Type: 'application/x-www-form-urlencoded'
            Accept: 'application/json'
        json:
            platform: 'front'
            num: '1'
    validate:
        - {"check": "status_code", "comparator": "eq", "expect": 200}

**Comment by kyuubeiii97** [comment]
How can u fix that bug ?
