### ISSUE TITLE
脚本编写效率和调试效率很低

### ISSUE THREAD

**Issue by holysor** [HttpRunner/HttpRunner#195]
目前httprunner，编写脚本效率好低，主要是出错调试浪费太多时间了。现在的报错定位机制不是友好。关于extract的使用，感觉很牵强。按照官方的用法也经常出现str have not attribute items的错误

**Comment by JacobHZ** [comment]
really？我感觉效率可高了。

**Comment by debugtalk** [comment]
@holysor 提升调试效率这块儿的确还有很长的路要走。可否将你的问题拆分细化下，我们一件件来进行优化。

**Comment by ferhas** [comment]
一、skip虽然可以排除不执行的test，但调试时，经常是只执行某个test。而不是全部的test。建议加UnSkip
二、report把返回HTML的结果转码了，可以先判断如果是大段的HTML，点击链接后以WEB输出。
三、建议集中输出variable、extract的值，方便观察。

**Comment by holysor** [comment]
parameters：目前具体取值方式有哪些？目前只看到这些。
取自定义数组:
![image](https://user-images.githubusercontent.com/17400810/39227337-b5a47adc-488a-11e8-87f9-ba5ae1ace075.png)
取函数返回值：
![image](https://user-images.githubusercontent.com/17400810/39227455-45017446-488b-11e8-8f60-13b459d419e2.png)
![image](https://user-images.githubusercontent.com/17400810/39227531-cb97442c-488b-11e8-8e7a-d8a4d542aca2.png)
如果返回值里面每组数据里面多个key那么在parameters 也是命名：key1-key2-key3-...这样感觉会不太合理，而且在测试的时候会出错。还有可以直接将包含字典的数值直接放在yml中存放在parameters中可以吗？

**Comment by fakegeeker** [comment]
@JacobHZ @holysor 的确不能直接将包含字典的数据直接放到parameters中，但是可以取折中的办法。
方法1，将该字典拆分成小的数据，然后在api中拼凑成字典，这些小的数据从parameters中传入。
方法2，将包含字典的数据用json.dumps()方法转成字符串，放在parameters中，然后在相应的teststep中增加setup_hook，传入request参数，如果该请求除了有该字典还有其他参数一起构成json字符串，则在钩子函数中将该字典转成的字符串再loads成字典。这样最终传入的数据就正确了
