### ISSUE TITLE
1.3.9URL拼接存在问题

### ISSUE THREAD

**Issue by JacobHZ** [HttpRunner/HttpRunner#196]
base_url: http://xxxx/dubhe/api/v1
url: /task/get

请求时url：http://xxxx/task/get

**Comment by debugtalk** [comment]
@JacobHZ 感谢反馈，这的确是个 [bug](https://github.com/HttpRunner/HttpRunner/commit/84ea7c84eadb780368480f043a400e2edecb3891)。
