### ISSUE TITLE
如果需要在validate环节做一些加减运算？

### ISSUE THREAD

**Issue by EthenQ** [HttpRunner/HttpRunner#202]
我在Context类 eval_check_item方法中找到以下注释：
check_item should only be in 4 types: 
....
4 dict or list, maybe containing variables reference, e.g. {"var": "$abc"}

所以在buildin中加入一个方法：
def eval_add(a, b):
    return a+b
在用例文件中使用
validate:
      - eq:
        - opresult:
            ${eval_add($hehe,2)}
        - opresult:
            202
之后可以正常运行，请问还有否其他的方法

**Comment by debugtalk** [comment]
没必要加到 buildin.py 中，加到项目的 debugtalk.py 中就可以了。
