### ISSUE TITLE
base_url 使用变量引用时，生成的 locustfile.py 中没有实现 host 替换

### ISSUE THREAD

**Issue by holysor** [HttpRunner/HttpRunner#203]
![s q7h j f ol5up2oxm66or](https://user-images.githubusercontent.com/17400810/39289817-269b24e0-4960-11e8-922c-9dcb541b2ad9.png)

**Comment by JacobHZ** [comment]
应该是目录名称中文导致的

**Comment by holysor** [comment]
生成locustfile.py 文件：
![image](https://user-images.githubusercontent.com/17400810/39290595-ba3caf50-4962-11e8-8ba5-ac41ea2986ee.png)

然后依旧出错

**Comment by JacobHZ** [comment]
试一下 locust -f locustfile.py
我是没在windows环境上用过

**Comment by JacobHZ** [comment]
这个是locustfile.py里的host配置出问题了，把下图的host改了就行
<img width="680" alt="image" src="https://user-images.githubusercontent.com/15662990/39291676-606d6420-4966-11e8-8b3d-a9b19c3f4d12.png">

**Comment by holysor** [comment]
ok了，谢谢你的帮助
