### ISSUE TITLE
响应json的key当中包含点时无法提取字段

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#204]
返回json：
{"status": 200, "message": "", "body": {"simpleShipperOrderService.getOrderListByStatus":[{"consignerAddress":"AAA"}]}}
怎么取到里面的consignerAddress的值，貌似没法取到，大神的代码可以兼容下不

**Comment by debugtalk** [comment]
@wuyajun2016 因为你的key当中包含了点，`simpleShipperOrderService.getOrderListByStatus`，所以根据层级去写的时候，`content.body.simpleShipperOrderService.getOrderListByStatus.consignerAddress`，会匹配异常。

**Comment by debugtalk** [comment]
@wuyajun2016 你使用正则匹配的方式再试下吧。

```yaml
extract:
    - consignerAddress: "consignerAddress\":\"(.*)\""
```
