### ISSUE TITLE
用例分层后执行错误 api login not found!

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#207]
分层后：
testcases文件夹下，有一个smoketest.yml，里面内容如下：
- config:
    name: smoketest
    variables:
        - userid: "XXX"
        - password: "XXX"
    request: $default_request
    
- test:
    name: test.
    api: login($userid, $password)

api文件夹下，有一个basic.yml，里面内容如下：
- api:
    def: login($userid, $password) 
    request:
      url: '/odin/servlet/gate/single'
      headers: {}
      method: POST
      data:
        simpleAccountService.login: |-
          {
            "areaCode" : "86",
            "password" : "$password",
            "userid" : $userid,
            "loginMode" : "1",
            "role" : 3,
            "clientInfo" : {
              "vender" : "APPLE",
              "appVersion" : "1.0.1.9.2",
              "osVersion" : "11.2.2",
            }
          }
    validate:
    - eq: [status_code, 200]
    - eq: [content.status, 200]

然后cmd进入testcases文件夹下,执行hrun smoketest.yml
提示了：httprunner.exception.ApiNotFound: api login not found!
这个是啥意思啊，请问下大神，不是这么用的么？文档中没有说明

**Comment by JacobHZ** [comment]
https://github.com/HttpRunner/HttpRunner/issues/167

**Comment by wuyajun2016** [comment]
可以了，原来用例分层跟单个执行路径不一样的！
