### ISSUE TITLE
testcase 引用suite，suite引用 api，yml中定义参数变量，运行返回错误log，很难定位问题原因

### ISSUE THREAD

**Issue by holysor** [HttpRunner/HttpRunner#208]
![image](https://user-images.githubusercontent.com/17400810/39393208-070110a4-4af5-11e8-801f-34ee1f5ae8cf.png)
![image](https://user-images.githubusercontent.com/17400810/39393210-0aad488a-4af5-11e8-9429-40a72a912d55.png)

**Comment by debugtalk** [comment]
@holysor 麻烦再提供下详细堆栈日志。
