### ISSUE TITLE
请教个extract token问题 

### ISSUE THREAD

**Issue by BensonMax** [HttpRunner/HttpRunner#212]
![image](https://user-images.githubusercontent.com/31434954/39518482-a6e3f6fc-4e35-11e8-8f56-89defbb1cafe.png)
请问如何用extract 将accesstoken 带到下一个请求
尝试使用 
![image](https://user-images.githubusercontent.com/31434954/39518581-140d909e-4e36-11e8-8670-6e393ffa889e.png)
但是报错
![image](https://user-images.githubusercontent.com/31434954/39518606-2e7a8b62-4e36-11e8-9786-0a905a8cd1b7.png)

**Comment by BensonMax** [comment]
已经解决

**Comment by wangtesting** [comment]
> 已经解决

解决的也不说下嘛。。
