### ISSUE TITLE
使用teardown_hooks报错 'Response' object is not subscriptable

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#215]
想使用teardown_hooks 对response_object进行一些修改再extract value。
不知道是不是修改方式有问题报错。
![image](https://user-images.githubusercontent.com/13954003/39743761-8c9f1fe4-52d4-11e8-869d-ad33a535c60f.png)
 
这是我的response_object: 
![image](https://user-images.githubusercontent.com/13954003/39744199-08eae050-52d6-11e8-86bf-8912d63a8ede.png)

这是teardown_hook 函数：
![image](https://user-images.githubusercontent.com/13954003/39744353-8d8e00d0-52d6-11e8-89ae-f73d0c753540.png)

**Comment by debugtalk** [comment]
@Renyqin resp_obj 是一个实例，对应的是 Response object；因此你的写法应该是：

`for device in resp_obj.json()["data"]["list"]`

**Comment by Renyqin** [comment]
![image](https://user-images.githubusercontent.com/13954003/39794530-5da33082-537d-11e8-9b0c-24ad59d18c90.png)
现在代码更改如上， 可是从extract field 来看，response object 内部的值并没有被更改

![image](https://user-images.githubusercontent.com/13954003/39794786-b5adb59e-537e-11e8-8589-175d70b443f9.png)
@debugtalk

**Comment by debugtalk** [comment]
@Renyqin 抱歉，是我之前搞错了，response object 本身是不能修改的。

**Comment by debugtalk** [comment]
已更新：http://cn.httprunner.org/advanced/request-hook/

**Comment by Renyqin** [comment]
新的hook 机制仍然没有找到方法来解决该问题， response object 仍然无法更改
尝试了一下另一种方法，有以下几点问题：
思路是在variable 或parameters 定义一个变量，将这个变量传入tear_down
只有变量是mutable的才能够在另一个function 里面被更改，所以只能在parameters定义该变量， 因为parameters 支持list。
可是又遇到一个问题，没办法将parameters 的变量放进extract

**Comment by debugtalk** [comment]
response object 本来就是没法修改的。

**Comment by Renyqin** [comment]
@debugtalk 对，所以有没有办法使用tear_down对response object内部的值进行筛选然后extract?

**Comment by debugtalk** [comment]
@Renyqin 为什么要进行筛选？直接 extract 不行么？

**Comment by Renyqin** [comment]
比如说我想要extract一个特定的设备类型的设备在设备列表中, 因为后续的一些接口是针对于这种设备类型的，我现在的做法就是直接extract 整个设备列表。 再当需要筛选时使用setup_hooks对请求参数（设备列表）进行处理。可是这种做法就是需要在每一个需要用到该特定设备的test都添加setup_hook，显得非常臃肿，而且当两个接口需要同一种设备的时候，这种方法有很小的几率会造成两个setup_hook处理出来的不是同一种设备。

**Comment by debugtalk** [comment]
@Renyqin extract 的时候，是可以通过 点 运算符定位到响应结果中的具体元素的。http://cn.httprunner.org/quickstart/#_8

**Comment by Renyqin** [comment]
@debugtalk 可是在使用的时候比如说设备列表我无法知道自己想要指定的设备类型具体在列表的哪个位置，所以才用setup_hook function对列表进行loop来筛选

**Comment by debugtalk** [comment]
@Renyqin 现在可以在 teardown_hooks 中修改 response object 了。
