### ISSUE TITLE
suite config 中的 variables, parameters, hooks 不会执行

### ISSUE THREAD

**Issue by Renyqin** [httprunner/httprunner#216]
suite config的功能
suite config 能否使用 variables, parameters 还有hooks？
感觉好像往suite里面放这些东西都没有被执行

**Comment by steven-xgt** [comment]
试过，
suite config 应该是可以使用 variables, parameters 还有hooks，但是suite config里面的 base_url修改后好像没用，依然会被test case里面的base_url给覆盖。

**Comment by debugtalk** [comment]
在 suite config 中的 variables, parameters 和 hooks 的确都还不会执行，暂且记录为 bug 吧。
