### ISSUE TITLE
pipenv install Python 3.7 --dev  执行失败

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#218]
D:\HttpRunner>pipenv install Python 3.7 --dev
Installing Python…
Looking in indexes: https://pypi.org/simple
Collecting Python

Error:  An error occurred while installing Python!
  Could not find a version that satisfies the requirement Python (from versions: )
No matching distribution found for Python
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

D:\HttpRunner>pipenv install  meinheld==0.6.1
Installing meinheld==0.6.1…
Looking in indexes: https://pypi.org/simple
Collecting meinheld==0.6.1
  Using cached https://files.pythonhosted.org/packages/6c/b7/0a6f03ba8e12862c71a7acc0c051f902f952f13be2a48878ebd2bc198562/meinheld-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Are you really running a posix compliant OS ?
    Be posix compliant is mandatory

    ----------------------------------------

Error:  An error occurred while installing meinheld==0.6.1!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\10066611\AppData\Local\Temp\pip-install-ry2guzqw\meinheld\
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

第一次执行的时候是正常的，后来删除了工程，重新git clone了一下，再执行pipenv install Python 3.7 --dev就失败了

**Comment by debugtalk** [comment]
pipenv 安装  python3.7 ？没这操作吧
