### ISSUE TITLE
如何使用数据驱动的方式编写用例

### ISSUE THREAD

**Issue by YanQinYuan** [HttpRunner/HttpRunner#22]
同一个url，数据不同会产生不同结果；能否像Robotframework那样用data-driven编写用例？

**Comment by debugtalk** [comment]
@YanQinYuan 当前可以采用的做法：
第一种：将测试用例复制一份，在里面赋值不同的参数；
第二种：写一个生成数据参数的函数，在测试用例里面调用。

**Comment by debugtalk** [comment]
测试用例已经支持参数化数据驱动机制。
设计文档：http://debugtalk.com/post/httprunner-data-driven/
使用文档：http://cn.httprunner.org/data-driven/
