### ISSUE TITLE
建议将测试报告生成的信息打印到标准输出里，而非日志中

### ISSUE THREAD

**Issue by Kewings** [HttpRunner/HttpRunner#221]
这样方便调用subprocess的时候获取标准输出里测试报告名称做发邮件或其他等操作。

目前打印在日志里，获取不到呀

**Comment by Kewings** [comment]
-_-#
我以前就是通过调用ate里的task, pyunit.report这样来调用并生成报告的。。。（所以当时没有提过意见）
更新httprunner最新版本后就不能用了，所以这次重新组织框架的时候就是用subprocess来直接调用hrun.exe了

我怕如果调用你里面的函数，以后又不能用了。。。。

**Comment by Kewings** [comment]
个人认为，HttpRunner执行的结果应该是报告的输出，所以将报告名称作为最终的输出或者打印到stdout，这是符合逻辑
毕竟现在执行的结果是case名称和0/1，这毕竟不是产出。

**Comment by zhengxiansen** [comment]
@Kewings 不是已经给你意见了吗？而且 httprunner 已经提供了脚本调用的能力啊

```python
import sys
from httprunner import HttpRunner

# 参考 unittest.TextTestRunner
runner = HttpRunner(stream=sys.stdout, failfast=False, verbosity=2)

# 执行测试用例
runner.run(['./tests'])

# 获取测试结果
result = runner.summary

print(result)

# 你自己写的测试报告为什么要输出？
runner.gen_html_report(
    html_report_name="测试报告名称"
)
```

**Comment by Kewings** [comment]
可能有点较真哈，但本意是本着探讨的原则，希望能将一个好的Project往更好的方向去改进。
@debugtalk @zhengxiansen 
HttpRunner的初衷是什么呢？定位是什么呢？

是一个提供unittest 调用方法的应用，仅供他人参考？还是提供一个http API test的服务？（SaaS?)

如果是前者，那么就请忽略我下面的话。
如果是后者，那么我认为HttpRunner是一个，我只要扔进去我的Case，然后输出给我Test Report的Service，并不需要我去过多的了解HttpRunner内部逻辑是如何实现的。

HttpRunner应该是整个项目中的一环，将自己定位于整个大框架中的一个符合模块化设计的Service，就是提供一个http API的Test Service，目前hrun.exe提供的各种参数的输入，我可以认为他就是一个API，这个接口在未来是可以不断被丰富的，例如提供Label Case的执行等等。

所以，我觉得HttpRunner本身的执行结果就可以考虑为一个类似Json的输出，此次执行了多少Case，多少Pass，多少Fail，报告在哪里。。。。。。

题外话：
当然，我也是因为懒，不想未来需要去给以后用的人做代码的维护（怕有些脚本发生改变，就不得不再次做修改），想直接调用hrun来得到结果输出。
目前已经通过其他的方法将report找到后发出了。

**Comment by zhengxiansen** [comment]
其实我是不明白你的意思，你说的这两个是两个东西，但是互相之间不冲突的，
httprunner 可以认为是一个运行测试用例的容器，
它提供两种方式运行 你编写好的测试用例，一种就是 cli 的方式，一种是编程的方式运行。


而你说的服务，这个应该是基于 httprunner 拓展的，它可以是任何的http服务，
甚至可以是非python编写的，只要后台执行 httprunner，
如果是 python 那只是更加灵活的调用而已，但是 服务 本身和 httprunner 无关。

**Comment by zhengxiansen** [comment]
举个例子：

```python
# 假设未来 httprunner 提供了 run_tests 和 run_files 作为接口供外部使用
# 假设未来 httprunner 分离了 loader，builder 和 runner
def run_files(paths,
              variables=None,
              loaders=(
                  FileSystemLoader(YAMLBuilder, JSONBuilder),  # 本地文件加载，支持 yaml 和 json 数据格式
                  HTTPLoaders(YAMLBuilder, JSONBuilder)  # 远程文件加载，支持 yaml 和 json 数据格式
              ),
              **kwargs):
    """ 运行测试文件

    :param paths: 文件或文件夹,支持多个
    :param variables: 全局变量
    :param loaders: 加载器列表，默认支持 文件 和 http(s) 数据的加载
    :return:
    """

    # 创建一个链式的加载器
    loader = ChainLoader(loaders)

    # 加载测试用例
    task_suite = loader.load_targets(paths)

    # 调用 run_tests
    return run_tests(task_suite, variables, **kwargs)


def run_tests(task_suite, variables, **kwargs):
    """ 运行测试用例

    :param task_suite: 已经构建好的测试用例
    :param variables: 全局变量
    :return:
    """
    # TestSuite 实现了 __iter__ 方法
    if task_suite is None or len(task_suite) == 0:
        debug("No test loading attempts succeeded.  Created an empty test suite.")
        exit(1)

    runner = HTTPRunner(resultclass=HtmlTestResult, **kwargs)

    # 运行测试用例
    result = runner.run(task_suite, variables)

    # 处理测试结果
    summary = get_summary(result)
    summary.setdefault('output', [task.output for task in task_suite.tasks])

    # 格式化数据
    return summary
```

那么你就可以这样创建一个 http service：

```pyhton
from .plugins import celery
from httprunner import run_tests, run_files

# celery 是一个定时器框架。专门给后端跑定时任务的

@celery.task(bind=True)
def run_tests_for_file(paths, variables):
    # 文件可以是远程的 url 也可以是上传上来的文件
    result = run_files(paths, variables)
    # 写入结果到数据库
    # 发送邮件等等
    return result


@celery.task(bind=True)
def run_tests_for_file(datas, variables):
    # datas 的数据可以是从数据库中加载
    # 也可以是任意地方拼接出来的 json 数据
    result = run_tests(datas, variables)
    # 写入结果到数据库
    # 发送邮件等等
    return result

# 后面只要 http server 调用这两个方法就可以，那么一个 接口测试网站就可以对外使用了
```

**Comment by zhengxiansen** [comment]
至于你说的输出到标准流，这个目前就可以处理了，unittest 的 TextTestRunner 默认就是输出到标准流的，如果仅仅是输出的内容，可以自己自定义的

http://cn.httprunner.org/development/

**Comment by Kewings** [comment]
1 testcase --> case翻译器 --> HttpRunner --> test report
2 testcase --> Http Test Service( base on HttpRunner & other functions ) -->test report

@zhengxiansen 
要达到目标总是有多种多样的方式，
如你所言，在HttpRunner上做一次封装，将自己所需的所有功能组合并生成一个test service是一种方式，如2
也可以如1一样，将HttpRunner做为一个工具/模块/服务，仅完成我希望他完成的任务

1中的HttpRunner就仅仅是个服务，我如果想做webui的测试了，同样的框架，换个webui的工具来执行我输入的Case即可
2中的Http Test Service是需要维护的，未来需要任何新的功能都需要在这个服务上做扩展，这里的HttpRunner更像是个库，他是服务的一个部分，属于强耦合

其实问题的焦点在于我需不需要在HttpRunner外层再包装一段强耦合且需要维护的代码来生成一个新的Service
我经历了HttpRunner从最初的ATE到现在的HttpRunner，架构上有发生过一段较大的改变，原来我也是调用ate(HttpRunner)内部方法来实现我Case的执行和报告的输出，但更新到HttpRunner最新版本后，部分原来的调用方法失效了，所以，这次才会重新整理框架，将强耦合变成低耦合。

因为我相信，随着Python库的越来越丰富，以及需求越来越多，HttpRunner也会进一步改变一些自身现有的方法来达到更高的效率和更好的功能输出，所以我不敢确定现有的内部方法的调用方式是不是在未来一定有效，如果不能，那么未来就一定存在这部分代码的维护工作，因为我同样不确定未来（我公司里）接手这块的人能不能看懂我现在使用的方法或逻辑。。。因为我也不确定我是不是会一直在这家公司工作^,^，那样的话，我将无法跟他做一堆的解释。。。

仅作讨论，没有完美的方案，两种方式肯定是各有利弊的，取决于愿意接受什么样的利，放弃什么样的弊，仅仅是角度问题。

**Comment by zhengxiansen** [comment]
@Kewings 嗯，你说的问题的确都是存在的，不过这种问题都没有什么比较好的解决办法，除非你是这个项目的发起人，或者公司内部开发，依赖外部或者说依赖开源的本来就是这样，如果你希望稳定，只能基于某个框架 或者 某个项目进行 二次开发。

其实这种我个人感觉没必要特别纠结，你看 前端框架，年年出新品，年年各不同，可是还是这么多人用。

而且 httprunner 毕竟出来的不算久，api 经常变动也是可以理解的，不像 py.test 这样比较老牌的测试框架，已经趋于成熟稳定了。

办法总比困难多，提出一个解决一个，有问题说明需求还是存在的，你可以一起参与这个项目，也可以基于实现自己的想法，慢慢的总会出一款成熟的框架出来

**Comment by debugtalk** [comment]
@Kewings HttpRunner 还处于开发中，之前的想法可能也有许多不成熟的地方，所以也会存在一些改动。
如果你不想被改动影响，你完全可以固定使用某一版本就好了。当有你需要的新特性时你再考虑升级就行了。

**Comment by Kewings** [comment]
目前从日志中读取report的路径，可以暂时解决该问题
