### ISSUE TITLE
httprunner 升级后显示版本1.4.2而不是1.4.3

### ISSUE THREAD

**Issue by Renyqin** [HttpRunner/HttpRunner#223]
![image](https://user-images.githubusercontent.com/13954003/39904236-816f6fac-5509-11e8-86f8-dc958ba96165.png)

![image](https://user-images.githubusercontent.com/13954003/39904282-b8740328-5509-11e8-9563-608ef22565e3.png)

**Comment by debugtalk** [comment]
@Renyqin 代码提交了，但还没有发布版本。

你可以通过这个方式更新：
pip install -U git+https://github.com/httprunner/httprunner.git
