### ISSUE TITLE
1.4.4版本测试报告中Detail的log直接转到我本地磁盘了

### ISSUE THREAD

**Issue by 360kevin** [httprunner/httprunner#232]
下载的hrun的1.4.4版本，测试完case后，pass的报告中的Detail列log字段有问题。
report -----》Detail ----》 log：
file:///J:/#popup_log_1    
导致直接显示的是我的本地磁盘J的list

如果是失败的case的话，报告中的log就可以正常显示“Request and Response data”

**Comment by debugtalk** [comment]
可否上传你生成的报告看下？

**Comment by 360kevin** [comment]
生成的报告：
![image](https://user-images.githubusercontent.com/31471395/40159000-f1726a00-59d9-11e8-9a84-748892080860.png)
点log后：
![image](https://user-images.githubusercontent.com/31471395/40159022-0748051a-59da-11e8-843d-7b64166272a9.png)

**Comment by 360kevin** [comment]
我用get baidu.com试验了一下，发现还是有问题，之后我排查了一下浏览器，chrome打开会有问题，IE可以正常显示“Request and Response data”；
我的chrome版本： 66.0.3359.139（正式版本） （32 位） 这个版本会有问题；

**Comment by debugtalk** [comment]
1.x 版本已经没有维护，若在 2.x 最新版本下还有问题，可再进行反馈。
