### ISSUE TITLE
在debugtalk.py中如何引用其他包

### ISSUE THREAD

**Issue by smigoYu** [HttpRunner/HttpRunner#233]
在debugtalk.py文件中引用其他包会报错：No module named xxx，请问如何引用其他包？否则debugtalk.py文件内容可能很多，不方便维护。

**Comment by debugtalk** [comment]
可否贴下你的代码？

**Comment by smigoYu** [comment]
hook配置如下：
![image](https://user-images.githubusercontent.com/8230325/40152976-25e06dde-59ba-11e8-822a-1e67c32c5479.png)
代码如下：
import sys
from urllib import unquote
from exceptions import Exception

from qalib.dragnet import DragnetDB

sys.path.append(r'C:\tools\qatools\qalib')

def hook_print(msg):
    print(msg)

def delete_evaluate_consultant_opportunity_record_by_oid(oid):
    dragnetdb = DragnetDB()
    .....

报错如下：
ImportError: No module named qalib.dragnet
Exception AttributeError: "'Runner' object has no attribute 'testset_teardown_hooks'" in <bound method Runner.__del__ of <httprunner.runner.Runner object at 0x057C31F0>> ignored

**Comment by debugtalk** [comment]
@smigoYu 你先确保 debugtalk.py 中的代码可正常执行吧。

**Comment by xmj-png** [comment]
我也遇到了，debugtalk中可以正常执行，运行用例就报错，提示ImportError: No module named xxx    这是为啥怎么解决？

**Comment by xmj-png** [comment]
> @smigoYu 你先确保 debugtalk.py 中的代码可正常执行吧。

请问怎么解决了？
