### ISSUE TITLE
现在按以下方式还能发邮件吗，试了下没成功

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#234]
$ httprunner filepath/testcase.yml --report-name ${BUILD_NUMBER} \
    --mailgun-smtp-username "qa@debugtalk.com" \
    --mailgun-smtp-password "12345678" \
    --email-sender excited@samples.mailgun.org \
    --email-recepients ${MAIL_RECEPIENTS} \
    --jenkins-job-name ${JOB_NAME} \
    --jenkins-job-url ${JOB_URL} \
    --jenkins-build-number ${BUILD_NUMBER}

提示：
hrun: error: unrecognized arguments: --report-name 46 --mailgun-smtp-username xxx@qq.com --mailgun-smtp-password xxx --email-sender excited@samples.mailgun.org --email-recepients --jenkins-job-name

**Comment by debugtalk** [comment]
@wuyajun2016 已经将发邮件的功能剥离出来了。
https://github.com/debugtalk/jenkins-mail-py
