### ISSUE TITLE
请教下，为什么为我的脚本运行后，获取不到body和head值，运行后显示body值都为none

### ISSUE THREAD

**Issue by wuwanglove** [httprunner/httprunner#236]
请教下，为什么为我的脚本运行后，获取不到body和head值，运行后显示body值都为none
![image](https://user-images.githubusercontent.com/38805309/40169497-b7511db6-59f8-11e8-9bd4-c1ed455392c9.png)

**Comment by steven-xgt** [comment]
没有跑起来，一般都是格式问题或者传值的问题

**Comment by debugtalk** [comment]
@wuwanglove 运行成功了么？你可以开启 debug 模式，在终端中看下实际的请求和响应。
