### ISSUE TITLE
运行单元测试 ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by strayberry** [HttpRunner/HttpRunner#237]
安装后运行单元测试
$ pipenv run python -m unittest discover

----------------------------------------------------------------------
Ran 134 tests in 7.163s

FAILED (errors=20)

ValueError: not enough values to unpack (expected 2, got 1)

请问是环境的原因吗

**Comment by debugtalk** [comment]
你可以参考下项目的travis运行情况。
https://travis-ci.org/HttpRunner/HttpRunner
