### ISSUE TITLE
version-1.4.4，post接口测试报告没有request_body显示

### ISSUE THREAD

**Issue by JacobHZ** [HttpRunner/HttpRunner#238]
![image](https://user-images.githubusercontent.com/15662990/40211662-6f8e6c1e-5a7e-11e8-98c7-53eb9fe68c0f.png)

**Comment by JacobHZ** [comment]
report模板里针对POST\PUT做了判断，如果写用例时用了小写的post就无法显示request_body

**Comment by debugtalk** [comment]
升级到最新版本后不再存在该问题。
