### ISSUE TITLE
一个case内上传多个文件的问题

### ISSUE THREAD

**Issue by strayberry** [HttpRunner/HttpRunner#245]
参考requests_toolbelt 自定义了下列函数在debugyalk.py中

```
from requests_toolbelt import MultipartEncoder

def multi_encoder(field=[], file_headers=None):
	fields = {}
	for i in range (0,len(field)):
		field_name = field[i][0]
		file_path = field[i][1]
		file_type = field[i][2]
		if not os.path.isabs(file_path):
			file_path = os.path.join(os.getcwd(), file_path)
		filename = os.path.basename(file_path)
		with open(file_path, 'rb') as f:
			fields[str(i)] = (filename, f.read(), file_type)
	return MultipartEncoder(fields)

def multi_content_type(multi_encoder):
    return multi_encoder.content_type`
```

    {
        "test": {
            "name": "上传多个文件",
            "variables": [
                {"field_name": "uploadfile"},
                {"file_path1": "$uploadfile_dir/08-01.cfg"},
                {"file_path2": "$uploadfile_dir/08-02.cfg"},
                {"file_type": "text/plain"},
                {"multi_encoder": "${multi_encoder([$field_name,$file_path1,$file_type])}"},
            ],
            "request": {
                "url": "$url",
                "method": "POST",
                "headers": {
                    "Content-Type": "${multi_content_type($multi_encoder)}"
                },
                "data": "$multi_encoder"
            },
            "validate": [
                {"eq": ["status_code", 200]}
            ]
        }
    },   

返回结果为
----------------------------------------------------------------------
Traceback (most recent call last):
AttributeError: 'str' object has no attribute 'content_type'

----------------------------------------------------------------------

**Comment by strayberry** [comment]
若把 content_type放在multi_encoder函数中一起返回，即返回两个参数，json文件中如何接收呢

**Comment by debugtalk** [comment]
@strayberry 传参不支持中括号。你可以将`[$field_name,$file_path1,$file_type]`赋值给一个变量，然后再将变量传给函数`multi_encoder`。
