### ISSUE TITLE
参考 httprunner 做了个简易的实现，感觉 httprunner 的部分实现过于复杂了

### ISSUE THREAD

**Issue by zhengxiansen** [HttpRunner/HttpRunner#249]
因为对部分项目引入了 httprunner，可是使用过程发现还是有很多不便之处，比如参数化的字段定义过长，传参不太方便等。

所以本着学习的目的，阅读了 httprunner 的源码，可是过于复杂，头痛了好几天。

这几天刚好有时间，就动手实现了一遍，思路稍微清晰了点。

这时项目地址：[simple-apitest](https://github.com/zhengxiansen/simple-apitest)

希望能对于@debugtalk 有所帮助 

![image](https://user-images.githubusercontent.com/7506913/40426393-8c71f424-5ecd-11e8-9a0f-323041680ea0.png)

![image](https://user-images.githubusercontent.com/7506913/40426369-7a222e1a-5ecd-11e8-8872-8c5ba5c8cfcb.png)

![image](https://user-images.githubusercontent.com/7506913/40426349-6ab623fa-5ecd-11e8-89e8-9900bbb02613.png)

**Comment by zhengxiansen** [comment]
接口的分层定义比较容易实现，可以测试模块的定义还是没有弄明白这么处理，看了源码看的头都痛了，还是没有想到这么处理，期望后期能出比较好的方式实现， 目前的实现拓展能力还是比较欠缺的，不过已经可以完成大部分的测试场景，希望 httprunner 后期能越做越好

**Comment by debugtalk** [comment]
@zhengxiansen 感谢反馈。如果要通读源码，建议结合我的[开发笔记](http://debugtalk.com/tags/HttpRunner/)一起看。

后面我也看下你的源码学习下。

**Comment by zhengxiansen** [comment]
嗯，你的笔记看了点，第一次参照你的思路实现了下，可是后面因为工作原因没时间继续下去，后来重温了下 unittest 的源码，突然有了新的思路，所以几乎就用了一天的时间实现出来了，不过这个非常简陋，估计也就看看的地步，只是希望能对你有用吧
