### ISSUE TITLE
测试报告中展现接口响应时间

### ISSUE THREAD

**Issue by Junho2010** [HttpRunner/HttpRunner#25]
如果需要对测试报告进行定制，如将每一个接口的响应时间添加到测试报告中，应该如何实现？

**Comment by debugtalk** [comment]
@Junho2010 测试报告这部分的实现在另外一个项目中 [`PyUnitReport`](https://github.com/debugtalk/PyUnitReport)，我已将该需求加入需求资源池。

https://github.com/debugtalk/PyUnitReport/projects/1#card-4313741

**Comment by debugtalk** [comment]
新版测试报告中已经包含了响应时间。

http://cn.httprunner.org/report/
