### ISSUE TITLE
http 返回中包含中文, 多处报错UnicodeDecodeError: 'ascii' codec can't decode 

### ISSUE THREAD

**Issue by xinyang128** [HttpRunner/HttpRunner#250]
第一处是 logging 模块
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 1443: ordinal not in range(128)

第二处是
HttpRunner-1.4.4/httprunner/runner.py", line 199, in run_test
    err_resp_msg += "body: {}\n".format(resp.text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 956-957: ordinal not in range(128)

第三处是
  File "/Library/Python/2.7/site-packages/markupsafe/__init__.py", line 75, in __new__
    return text_type.__new__(cls, base)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 956: ordinal not in range(128)
DEBUG    call hook: ${restore_kt($EDGE,1916,$DOMAIN)}

**Comment by debugtalk** [comment]
@xinyang128 感谢反馈，后面我修复下。

推荐使用 Python 3，可以避免很多编码性的问题。

**Comment by debugtalk** [comment]
@xinyang128 已经修复，升级到 1.4.5 以后再试下。

**Comment by Hyvi** [comment]
升级到1.4.6版本还是出现此问题

**Comment by debugtalk** [comment]
@Hyvi 更新到 1.5.6 后再试下？
