### ISSUE TITLE
重复请求一个接口，获得返回数据，形成数据集，请问如何实现？

### ISSUE THREAD

**Issue by ztwo** [HttpRunner/HttpRunner#253]
感谢开发者
问题：重复请求一个接口，获得每次的返回数据，形成数据集，传入下一个接口请问如何实现？

**Comment by debugtalk** [comment]
@ztwo 可以参考下这个：http://cn.httprunner.org/development/

**Comment by ztwo** [comment]
@debugtalk 明白了，感谢！
