### ISSUE TITLE
httprunner.exception.ParamsError: len-eq is not defined in bind functions!

### ISSUE THREAD

**Issue by master-walker** [HttpRunner/HttpRunner#254]
httprunner 1.4.4 , 接口响应校验不支持len-eq这个了吗？出现以下错误：httprunner.exception.ParamsError: len-eq is not defined in bind functions!

**Comment by debugtalk** [comment]
@master-walker 是`len_eq`。

**Comment by master-walker** [comment]
好的，我再试试，谢谢
