### ISSUE TITLE
validate 里面的自定义函数,当参数不含$时,不生效.

### ISSUE THREAD

**Issue by xinyang128** [HttpRunner/HttpRunner#255]
如:
- eq: ["${is_backsource(SOURCE,randmon_str)}",false],is_backsource不运行
- eq: ["${is_backsource($SOURCE,randmon_str)}",false], is_backsource运行
centext 文件196行的判断,找到了$variables才执行eval_content,行为有些不一致,应该把 ${}也算上

![image](https://user-images.githubusercontent.com/16026054/40594428-bc9bd38a-6261-11e8-8e61-3e729d0c753a.png)

**Comment by debugtalk** [comment]
@xinyang128 问题已经修复了，感谢反馈。
