### ISSUE TITLE
测试执行结果将Fail和Error的结果进行区分

### ISSUE THREAD

**Issue by Junho2010** [HttpRunner/HttpRunner#26]
在执行的测试之后的结果中，只有成功和错误两种结果，没有失败这种结果。check的结果不一致的时候，直接就抛出异常，然后在报告中显示为Error了。是否能够将Fail和Error的结果区分开？

**Comment by debugtalk** [comment]
@Junho2010 你说的测试执行结果，是在测试报告中，还是推送的邮件中？

**Comment by Junho2010** [comment]
@debugtalk 测试报告中，我看了一下你的源码，不会走到Fail去，结果只会有Pass和Error

**Comment by lionel126** [comment]
我也感觉好难受 不能从报告中直观地看出是我的case写得有问题(error)还是case验证fail了

**Comment by debugtalk** [comment]
@lionel126 如果你的 testcase 写的有问题，运行时会报错，也不会生成测试报告了。
