### ISSUE TITLE
分层的API是否支持可变参数

### ISSUE THREAD

**Issue by steven-xgt** [HttpRunner/HttpRunner#261]
分层的API是否支持可变参数？

**Comment by debugtalk** [comment]
@steven-xgt 支持。

**Comment by steven-xgt** [comment]
我试了下面的方式：
def（$username,$password,*args）
好像不行，请问你那边有没有使用该方式的模板？

**Comment by debugtalk** [comment]
当时没有理解你说的可变参数的含义。
`*args`这种是不支持的。
