### ISSUE TITLE
config里面的base_url不能遵从变量的作用域

### ISSUE THREAD

**Issue by steven-xgt** [HttpRunner/HttpRunner#263]
可以在config里面设置一个变量，然后test再次设置那个变量时，运行test时会使用test里面设置的变量；但是base_url不能这样做。请问有没有改进这个的后续操作？

**Comment by debugtalk** [comment]
base_url 除了在 config 中设置，没有在 test 中设置的必要吧。

**Comment by steven-xgt** [comment]
有时候跨服务的时候，不同test的端口可能会不一样

**Comment by debugtalk** [comment]
@steven-xgt 如果单个test的host和端口不一样，直接使用完整的url就行了，没必要再设置 base_url
