### ISSUE TITLE
teardown_hook函数能否支持传入参数？

### ISSUE THREAD

**Issue by chenhuahuan** [HttpRunner/HttpRunner#264]
需求：
需要在teardown_hook之后调用一个自定义的函数，该函数要求的动态输入参数较多，但teardown_hook只支持response一个参数，是否有一个更好的办法实现？
因为我们请求完之后，在校验时发现找不到一个很好的地方去执行这种自定义输入的函数。

**Comment by debugtalk** [comment]
已经支持了的。
http://cn.httprunner.org/advanced/request-hook/#teardown_hooks
