### ISSUE TITLE
有2个接口，第二个接口地址引用了某个函数，如果函数报错，执行出来的结果是2个用例为同一个url

### ISSUE THREAD

**Issue by pencil1** [HttpRunner/HttpRunner#269]
接口一：/captcha/$phone
接口二：/sms/$phone/${GetValidcode($phone)}
假如接口二调用函数时报错了，那么最后生成的报告，接口二的url会是接口一的/captcha/$phone

**Comment by steven-xgt** [comment]
遇到同样的问题

**Comment by debugtalk** [comment]
感谢反馈，已经修复了，升级至 1.4.8 版本即可。
