### ISSUE TITLE
能否通过teardown来判断接口是否成功

### ISSUE THREAD

**Issue by steven-xgt** [HttpRunner/HttpRunner#270]
场景：
接口A创建一个实例，但是时异步的，每次接收到请求自动返回200，然后异步去处理，只能通过teardown来调查询接口B查看是否创建成功。但是接口A每次都是200.能否通过teardown来判断接口是否成功？

**Comment by debugtalk** [comment]
你处理的方式不对。
按照你的场景：

- 请求A接口，发起请求；
- 请求B接口，查看结果。

这个场景本来就应该拆开为两个接口来看待，因此写两个测试就好了。
