### ISSUE TITLE
test里的parameters  引用不到 config 下variables 里定义的变量

### ISSUE THREAD

**Issue by zhaoyinggang** [HttpRunner/HttpRunner#271]
![image](https://user-images.githubusercontent.com/40195868/41275555-d53a4888-6e53-11e8-85cb-0fe613aa8660.png)

**Comment by steven-xgt** [comment]
建议把parameter里面的函数直接放到上面的variable里面

**Comment by zhaoyinggang** [comment]
这样的话，test的parameter:[fieldIsEdit:$fieldIsEdit]  还是引用不到 $fieldIsEdit

**Comment by debugtalk** [comment]
在 test 中引入支持 parameters 后，框架逻辑变得更加复杂了，个人不建议在 test 中使用 parameters。

**Comment by debugtalk** [comment]
从 1.5.11 起，已经去除 test 中的 parameters 功能。
