### ISSUE TITLE
Windows环境下无法实践入门教程（httpbin的gunicorn依赖无法安装） 

### ISSUE THREAD

**Issue by gitdachong** [HttpRunner/HttpRunner#279]
base.py  引用了 httpbin （from httpbin import app as httpbin_app），httpbin 使用了 gunicorn 模块，gunicorn 不支持windows ，导致运行例程时，直接报ModuleNotFoundError: No module named 'fcntl'，手工导入此模块，还会报其pwd模块等一系列模块不存在，本小菜已解决，建议大神处理一下兼容性，不要把入门新手给难到

**Comment by debugtalk** [comment]
httpbin 依赖于 Gunicorn 和 meinheld，这两个库都不支持 Windows 平台。
因此当前在Windows平台下无法运行 HttpRunner 的单元测试用例。
