### ISSUE TITLE
测试用例参数化后，用同一个文件进行性能测试时，怎么能只用一个正确的参数测试性能？

### ISSUE THREAD

**Issue by wcycxp** [HttpRunner/HttpRunner#280]
在测试用例中使用参数化，比如登录接口，用正确的账号和密码，还有正确账号和错误密码。但是用locusts进行性能测试时，也会使用错误密码的账号进行测试，其实只需要用一个正确账号和密码进行性能测试。这样就不能做到接口和性能统一脚本了，需要额外再编写一套性能的脚本。这个有什么解决办法么？

**Comment by debugtalk** [comment]
按照你的描述，自动化测试时是需要使用数据驱动，驱动的数据包括正常的数据和模拟异常的数据。
那么你在压测的时候，可以只使用包含正确数据的文件即可，脚本并不需要改变。
