### ISSUE TITLE
单个测试用例中 setup_hooks 和 variables 的顺序问题

### ISSUE THREAD

**Issue by happyMeiyo** [HttpRunner/HttpRunner#281]
你好@debugtalk，
在debugtalk.py文件中定义了2个函数，`connect_database()`和`close_connection()`
![image](https://user-images.githubusercontent.com/22342835/41589237-8beaec80-73e6-11e8-9d59-7c807c441c1c.png)

在用例集的config中定义的hooks可执行，用例执行正常。
![image](https://user-images.githubusercontent.com/22342835/41589523-48cb5560-73e7-11e8-86b2-2821e090c479.png)

但是，在单个测试用例中定义的hooks未执行，导致执行get_first_coupon_code函数时报错。
![image](https://user-images.githubusercontent.com/22342835/41589349-e2d2de9a-73e6-11e8-9b7c-d57bb4aab345.png)

**Comment by happyMeiyo** [comment]
@debugtalk 
定位出问题出现的原因：因为`coupons_code: ${get_first_coupon_code($vipCardNo)}`获取值的前提是`${connect_database()}`已执行。

但是目前的实现是，现获取变量值，再执行`setup_hooks`，即A -> B;
![image](https://user-images.githubusercontent.com/22342835/41807357-a1358bc8-7700-11e8-89b8-f64eac33296e.png)
**请问：是否可以先执行`setup_hooks`，再获取变量值，即B -> A**

**Comment by debugtalk** [comment]
@happyMeiyo 感谢反馈！

仔细看了下，setup_hooks 还不能直接移动到 prepare 前面，因为在 setup_hooks 中也可能会引用变量，而变量都是在 prepare 中加载。

针对你的问题，是否可以将 `${connect_database()}` 放置到 config 的 setup_hooks 中？

**Comment by happyMeiyo** [comment]
@debugtalk 目前已将将 ${connect_database()} 放置到 config 的 setup_hooks 中
