### ISSUE TITLE
Windows环境下无法实践开发者模式（httpbin的meinheld依赖无法安装）

### ISSUE THREAD

**Issue by berrycam** [HttpRunner/HttpRunner#288]
安装环境：win10+python3.6
安装时出现下面的提示，安装版本与我的环境不匹配

asus@DESKTOP-RD8H9JK MINGW64 ~/HttpRunner (master)
$ pipenv install --dev
Creating a virtualenv for this project...
Pipfile: C:\Users\asus\HttpRunner\Pipfile
Using d:\python\python36\python.exe (3.6.5) to create virtualenv...
Already using interpreter d:\python\python36\python.exe
Using base prefix 'd:\\python\\python36'
New python executable in C:\Users\asus\.virtualenvs\HttpRunner-gHQkxH18\Scripts\python.e                                              xe
Installing setuptools, pip, wheel...done.
Setting project for HttpRunner-gHQkxH18 to C:\Users\asus\HttpRunner

Virtualenv location: C:\Users\asus\.virtualenvs\HttpRunner-gHQkxH18
Installing dependencies from Pipfile.lock (64c12a)...
Ignoring enum34: markers 'python_version < "3"' don't match your environment
Ignoring ipaddress: markers 'python_version < "3"' don't match your environment
An error occurred while installing meinheld==0.6.1! Will try again.
Ignoring ruamel.ordereddict: markers 'platform_python_implementation == "cpython" and py                                              thon_version <= "2.7"' don't match your environment
Installing initially failed dependencies...
Collecting meinheld==0.6.1
  Using cached https://files.pythonhosted.org/packages/6c/b7/0a6f03ba8e12862c71a7acc0c05                                              1f902f952f13be2a48878ebd2bc198562/meinheld-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Are you really running a posix compliant OS ?
    Be posix compliant is mandatory

**Comment by berrycam** [comment]
在win10 64bit上（Microsoft Windows [版本 10.0.16299.492]）手动把上述几个无法安装的依赖包，如enum34、ipaddress，这两个安装成功了，但是meinheld无法正常安装。请问meinheld目前只有linux下才能安装吗，如果是win10如何处理呢？


提示信息为：
$ pip install meinheld
Collecting meinheld
  Downloading https://files.pythonhosted.org/packages/6c                      /b7/0a6f03ba8e12862c71a7acc0c051f902f952f13be2a48878ebd2                      bc198562/meinheld-0.6.1.tar.gz (79kB)
    Complete output from command python setup.py egg_inf                      o:
    Are you really running a posix compliant OS ?
    Be posix compliant is mandatory
    ----------------------------------------
Command "python setup.py egg_info" failed with error cod                      e 1 in C:\Users\asus\AppData\Local\Temp\pip-install-bvf8                      n1ni\meinheld\

**Comment by berrycam** [comment]
在https://pypi.org/project/meinheld/好看到
Requirements
meinheld requires Python 2.x >= 2.6 or Python 3.x >= 3.2 . and greenlet >= 0.4.5.
meinheld supports Linux, FreeBSD, Mac OS X.
没有提示支持windows呢

**Comment by forgetzxy** [comment]
是的，同样遇到这个问题了。meinheld的setup.py里有判断操作系统：
def check_platform():
    if "posix" not in os.name:
        print("Are you really running a posix compliant OS ?")
        print("Be posix compliant is mandatory")
        sys.exit(1)

折腾了好久，现在放弃在windows上安装开发者模式了。。。

**Comment by debugtalk** [comment]
刚看了下 meinheld 的项目描述，的确是不支持 Windows。

![image](https://user-images.githubusercontent.com/3657070/42017659-6b9fc98e-7ae2-11e8-9ea2-cbd7f8ad8d81.png)

**Comment by debugtalk** [comment]
@berrycam
HttpRunner并没有不再支持 Windows，只是当前 HttpRunner 的单元测试使用了 httpbin，而 httpbin 又依赖了 meinheld。
所以在 Windows 下，HttpRunner 还是可以使用的，只是无法正常运行单元测试而已。

**Comment by debugtalk** [comment]
duplicate with #279

**Comment by berrycam** [comment]
@debugtalk 好的，谢谢，辛苦了~
