### ISSUE TITLE
mac+python3.6 开发者模式问题

### ISSUE THREAD

**Issue by jianjian12138** [HttpRunner/HttpRunner#289]
gfd178deMacBook-Pro:~ gongfudou$ pipenv run python -m unittest discover

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
gfd178deMacBook-Pro:~ gongfudou$ pipenv graph

这是什么情况

**Comment by berrycam** [comment]
你没有进入httprunner这个主干目录去

**Comment by debugtalk** [comment]
@berrycam 正解。
