### ISSUE TITLE
接口响应的结果检查

### ISSUE THREAD

**Issue by Junho2010** [HttpRunner/HttpRunner#29]
一个建议：目前的检查结果的方式只有check一种，是否可以新增通过函数对结果进行检查，通过函数返回的结果（True,False,Error等）标记结果？

**Comment by debugtalk** [comment]
@Junho2010 麻烦后面在提issue的时候，标题和正文分开，不要把内容全写到标题里面。

**Comment by debugtalk** [comment]
@Junho2010 检查结果的方式并非只有一种，而是实现了很多[`comparator`](https://github.com/debugtalk/ApiTestEngine/blob/master/docs/comparator.md)，可以实现指定响应字段与预期结果之间各种复杂的比较方式。

**Comment by Junho2010** [comment]
@debugtalk 
这个我看过，对应的源码也看了一些。但是对于一些比较复杂的，比较比较困难。我目前的遇到的有以下一些情况：
1.发送请求时的数据使用了随机生成，然后需要比较结果中的数据是否是和这个相关（通过某个算法转换）。比如我输入的是321，我的结果是（3+2+1）*avg(3+2+1)这种转化，目前的comparator是比较难于实现的。但是如果通过函数去比较，则很容易实现。

2.判断响应是否符合某个规范（可以通过comparator实现，但是比较的步骤会比较麻烦）

**Comment by debugtalk** [comment]
@Junho2010 
1、这种情况的确比较复杂；除此之外，有些情况例如加密转码的情况，也得通过你说的这种方式来做；
2、判断是否符合规范，如果只是文本字符串，可以用正则表达式来匹配。

总的来说，这个需求可以考虑做，你有兴趣提PR么？

**Comment by Junho2010** [comment]
@debugtalk 半路出家的，现在水平还比较差。目前还在研究你的代码，准备自己改造改造着用，目前计划是使用你的核心部分，把测试报告生成和结果检查部分重新弄下。

**Comment by yileye** [comment]
@debugtalk 测试报告建议使用allure这个测试报告框架

**Comment by migismile** [comment]
如果返回的数据是 {
“data":[{
limits:{
"max":30000
}
}]
}这种格式，想检查max的值是否匹配，那么用例的validators应该怎么写，我试了data.limits.max报没有data这个属性

**Comment by debugtalk** [comment]
@migismile 

```yaml
validators:
    - {"check": "content.data.0.limits.max", "expected": 30000}
```

**Comment by debugtalk** [comment]
已经支持在validator中使用自定义函数进行结果判断。
