### ISSUE TITLE
无法extract抽取Set-Cookie中的字段值

### ISSUE THREAD

**Issue by chenchengyuan** [HttpRunner/HttpRunner#292]
```yaml
extract:
        - mmsession: headers.Set-Cookie.PHPSESSID
```

这样抽取时会失败
我直接用request的请求中的 response.cookies[PHPSESSID]是可以取出的，看大佬能不能优化一下

![20180629_006](https://user-images.githubusercontent.com/29788128/42078405-ea854ae0-7bae-11e8-9b78-c019afc5642e.png)
![20180629_008](https://user-images.githubusercontent.com/29788128/42078406-eaeac8fc-7bae-11e8-9dca-9831137c26f3.png)

**Comment by debugtalk** [comment]
@chenchengyuan 试下 `cookies. PHPSESSID`
