### ISSUE TITLE
版本问题导致用例运行失败

### ISSUE THREAD

**Issue by 605799788** [HttpRunner/HttpRunner#297]
我在 1.3.几   版本运行的json用例正常，  现在更新到1.4.6之后运行用例  抛出了
httprunner.exception.par:  ResponseObject does have no attributes: body   这个异常  请问是怎么回事

**Comment by debugtalk** [comment]
@605799788 body 是 requests.Response 中没有的 body 这个属性的，所以后面就去掉了。你将 body 替换成 content 应该就可以了。
