### ISSUE TITLE
运行快速上手中带函数的用例，总是报错

### ISSUE THREAD

**Issue by SongChao1123** [HttpRunner/HttpRunner#298]
运行快速上手中的用例demo-quickstart-5.json，总是报错
ERROR: runTest (httprunner.task.TestCase)
/api/get-token
----------------------------------------------------------------------
Traceback (most recent call last):
httprunner.exception.FunctionNotFound: get_sign not found in recursive upward path!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
httprunner.exception.ParamsError: get_sign is not defined in bind functions!

======================================================================
ERROR: runTest (httprunner.task.TestCase)
/api/users/1000
----------------------------------------------------------------------
Traceback (most recent call last):
httprunner.exception.VariableNotFound: token not found in recursive upward path!

----------------------------------------------------------------------
Ran 2 tests in 0.007s

FAILED (errors=2)
INFO     Start to render Html report ...
INFO     Generated Html report: E:\reports\2018-07-06-14-13-42.html

**Comment by fukuale** [comment]
问题解决了，
把
from httprunner import exception, logger utils
改成了
from httprunner import exception, logger
from httprunner.utils import *

**Comment by SongChao1123** [comment]
thk
