### ISSUE TITLE
测试用例分层：suite模块中定义的全局变量无法引用

### ISSUE THREAD

**Issue by holysor** [HttpRunner/HttpRunner#299]
![image](https://user-images.githubusercontent.com/17400810/42405775-77a93ba0-81ce-11e8-971a-1fb8a0bb418d.png)
![image](https://user-images.githubusercontent.com/17400810/42405784-8f2123f6-81ce-11e8-8e3b-c8e460efad42.png)

**Comment by guoweichen** [comment]
遇到同样的问题，将variables里面的数据写出来就没有问题 例如app_id ： [ {'a' : 1},{ 'b' : 2} ]，但是引用debugtalk数据就会报错

**Comment by holysor** [comment]
@debugtalk suite 中定义的全局变量，在testcase调用suite执行时报错VariableNotFound，是一定要传参数吗？

**Comment by RongshanZhang** [comment]
最近也遇上这个问题。关注一波

**Comment by debugtalk** [comment]
HttpRunner 2.0 版本测试用例分层机制：https://cn.httprunner.org/advanced/testcase-layer/
