### ISSUE TITLE
validate expected引用变量bug

### ISSUE THREAD

**Issue by yinquanwang** [HttpRunner/HttpRunner#300]
假设接口返回{"respCode":"0000"}

在variables定义变量code: content.respCode

在validate expected引用$code

expected替换为了content.respCode 但是不会去抽取接口返回值了，如果不用变量形式，直接写content.respCode是可以的

**Comment by debugtalk** [comment]
@yinquanwang 定义变量的时候，你指定`content.respCode`，只会将其作为一个字符串。你如果需要引用 respCode，要么在 extract 中赋值给变量，要不就在 validate 中直接写 `content.respCode`
