### ISSUE TITLE
example中的分层执行提示suite/api not found

### ISSUE THREAD

**Issue by mecgrandy** [HttpRunner/HttpRunner#301]
![225](https://user-images.githubusercontent.com/41147719/42625120-98a93696-85f9-11e8-8b33-7b3d48228c14.png)
大家没碰到过这个问题吗，求教，我就是在\testcases 目录下直接 hrun 运行样例yml

**Comment by debugtalk** [comment]
@mecgrandy 你需要在 tests 的同级目录下运行：

```
$ hrun tests/testcases/xxx.json
```
