### ISSUE TITLE
关于summary.records的status和skip的问题

### ISSUE THREAD

**Issue by xglh** [HttpRunner/HttpRunner#303]
问题描述：在testcase中validate失败时，summary.records的status为error，但在TestReport中使用stat.errors作为failed失败条数。

请问status中error和failed的状态有什么区别？
====================================================================
问题描述：在testcase中添加skip，summary.records中这条记录的url是上一个case的url，不是本case的url

**Comment by debugtalk** [comment]
@xglh 

> 在testcase中添加skip，summary.records中这条记录的url是上一个case的url，不是本case的url

使用 skip 的时候，并不会去展示 url，正常的情况展示如下：

![image](https://user-images.githubusercontent.com/3657070/42929553-ef1a3318-8b6c-11e8-889c-5b025224baf0.png)
![image](https://user-images.githubusercontent.com/3657070/42929567-f9ec38fe-8b6c-11e8-914b-489208735cc3.png)

可否将你的使用方式（脚本）和实际展示截图发出来看下？

**Comment by xglh** [comment]
summary = runner.summary
print summary

我是直接打印summary的，我提的那个问题是在1.4.4版本上出现的，升级到1.4.8版本就跟你这边表现是一样的了

我这边还有个问题：
validate失败时，执行结果是error，什么情况下的执行结果是failed？

**Comment by debugtalk** [comment]
@xglh 之前没有正确区分 error 和fail，现在已经修复了，升级到 1.5.7 及以后就可以了。

**Comment by debugtalk** [comment]
#26
