### ISSUE TITLE
skip 用例后，应该跳过该用例不执行

### ISSUE THREAD

**Issue by songxiang321** [HttpRunner/HttpRunner#304]
在满足skip条件的测试用例不应该执行

**Comment by debugtalk** [comment]
![image](https://user-images.githubusercontent.com/3657070/42930301-2ec4981c-8b6f-11e8-867d-e8ad1f762ab1.png)

**Comment by debugtalk** [comment]
@songxiang321 我这边无法复现你的问题，如果你升级到最新版还存在该问题，可再提供完整的信息。
