### ISSUE TITLE
关于数据驱动的断言

### ISSUE THREAD

**Issue by hhyo** [HttpRunner/HttpRunner#305]
对于数据驱动在接口测试中的使用，目前主要遇到过两种场景

1. 测试接口健壮性，模拟特殊数据和边界数据，测试接口在针对异常情况下的处理逻辑
2. 测试接口功能， 如登录接口中，测试用户名不存在、密码错误等场景下的处理逻辑

第一种一般比较好处理，因为异常情况下给用户的反馈大体相同，断言仅需要检查接口没有报错，正常提示信息即可，这也是HttpRunner目前可以支持的，而第二种往往就需要针对不同的数据做不同的断言，实际上也就是一条数据对应一个CASE，不知HttpRunner是否有其他方式可以解决类似的测试场景

**Comment by ruby1045** [comment]
同求

**Comment by debugtalk** [comment]
在下个版本会考虑加入。
