### ISSUE TITLE
没有生成html报告

### ISSUE THREAD

**Issue by jeremy8250** [HttpRunner/HttpRunner#312]
升级到1.5.5版本后，运行完了，没有生成测试报告

**Comment by debugtalk** [comment]
@jeremy8250 麻烦贴下报错的堆栈

**Comment by jeremy8250** [comment]
没有Report方面的报错信息，运行完后就是ok，后面跟了一个attributeerror，没有Report文件夹生成

----------------------------------------------------------------------
Ran 2 tests in 0.328s

OK
AttributeError: 'str' object has no attribute 'get'

d:\git\user-service>

**Comment by guoweichen** [comment]
遇到同样的问题，升级更新报告的新版本后出现问题

**Comment by debugtalk** [comment]
运行的时候加上 `--log-level debug`，就可以看到堆栈信息了。

**Comment by jeremy8250** [comment]
----------------------------------------------------------------------
Ran 4 tests in 1.217s

FAILED (errors=1)
Traceback (most recent call last):
  File "d:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python3\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "d:\python3\lib\site-packages\httprunner\cli.py", line 81, in main_hrun
    runner = HttpRunner(failfast=args.failfast, dot_env_path=args.dot_env_path).run(args.testset_paths)
  File "d:\python3\lib\site-packages\httprunner\task.py", line 269, in run
    test_suite_summary["base_url"] = test_suite.config.get("request", {}).get("base_url", "")
AttributeError: 'str' object has no attribute 'get'

d:\git\user-service>

**Comment by debugtalk** [comment]
与 #309 是相同的问题，近期会修复。

**Comment by debugtalk** [comment]
已修复，最新版本 1.5.11。
