### ISSUE TITLE
结果验证器的check字段能否支持函数调用

### ISSUE THREAD

**Issue by ruujoa** [HttpRunner/HttpRunner#314]
某一个业务接口响应内容只返回一个标识成功和失败整数(0成功，非0失败)，并不能验证业务操作是否符合预期。
目前我的需求是要check数据库有没有成功写入记录，check字段这里需要调用一个返回数据库查询结果的自定义函数，而不是目前跟响应信息相关的字段，不知可否实现

**Comment by debugtalk** [comment]
支持。http://debugtalk.com/post/HttpRunner-validator-optimization/
