### ISSUE TITLE
httprunner参数化使用时  在调用csv 文件中的参数空与响应中的某个字段的空作对比 对比报错

### ISSUE THREAD

**Issue by 530073295** [HttpRunner/HttpRunner#320]
1.在使用参数化传参时，使用的是csv 文本保存的参数空
场景：登陆成功后 响应body中的info 返回为 空 ，   预期参数传空
使用- eq:[“content.info”，$预期参数值]  进行对比
报错如下：
httprunner.exception.ValidationError:
        check item name: content.info;
        check item value: None (NoneType);
        comparator: equals;
        expected value:    (str).

**Comment by debugtalk** [comment]
你的响应结果为 None，而预期值为空字符串，两者不相等报错是正常的啊。

**Comment by 530073295** [comment]
问题是我在cvs 中填写什么才能在预期值中显示成none   ,在cvs 中写none 或null  返回的预期值都不能喝结果响应的none值对比成功，果断放弃，  换了个实现的方法      已成功实现参数化  解决了none 值对比
