### ISSUE TITLE
这里判断key为text之后才判断value为image ，导致判断image永远进不去

### ISSUE THREAD

**Issue by yinquanwang** [HttpRunner/HttpRunner#332]
![image](https://user-images.githubusercontent.com/32924136/43623595-9dfc8a18-9714-11e8-89e2-56e02a4db373.png)

**Comment by debugtalk** [comment]
![image](https://user-images.githubusercontent.com/3657070/43651670-98ad6c92-9775-11e8-89f1-d75c25f89fd8.png)
