### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by 781412862** [HttpRunner/HttpRunner#333]
这们工具能不能用Jenkins持续集成啊，有没有好的方案推荐一下

**Comment by laimeifeng** [comment]
执行方式采用 CLI 调用，可与 Jenkins 等持续集成工具完美结合。

**Comment by hansonjack** [comment]
请问如何CLI调用，能给个例子吗

**Comment by laimeifeng** [comment]
你怎么样执行cmd里面的hrun命令，在jenkins里面也是一样的呀，建议先看下jenkins是怎么样运行的。

**Comment by debugtalk** [comment]
详细使用方法请查看 Jenkins 的 Shell 使用方法。
