### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by meihaoyidian** [HttpRunner/HttpRunner#340]
Traceback (most recent call last):
httprunner.exceptions.FunctionNotFound: get_sign not found in recursive upward path!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
httprunner.exceptions.ParamsError: get_sign is not defined in bind functions!

**Comment by debugtalk** [comment]
Please try again in 1.5.11+.
