### ISSUE TITLE
想问一下，调试debugtalk.py ，如何在终端输出自己定义的日志，比如print(“debug”)终端并没有debug的输出

### ISSUE THREAD

**Issue by junjunsay** [HttpRunner/HttpRunner#341]
debugtalk.py 输出日志

**Comment by debugtalk** [comment]
@junjunsay 你写在 debugtalk.py 中的 print 语句，只要是执行到了，肯定会有打印的。

你没有看到打印，只可能是你将 print 写在某个函数里，而该函数并未在 YAMl/JSON 里面进行调用。
