### ISSUE TITLE
传入标准的测试用例结构体 报错：TypeError: expected str, bytes or os.PathLike object, not dict

### ISSUE THREAD

**Issue by angek2046** [HttpRunner/HttpRunner#345]
尝试在代码中使用标准用例体  报错：TypeError: expected str, bytes or os.PathLike object, not dict
标准用例体，复制的http://cn.httprunner.org/development/里面提供的样例
![image](https://user-images.githubusercontent.com/42505780/44304996-39d22100-a39f-11e8-95e5-20336e563d68.png)
![image](https://user-images.githubusercontent.com/42505780/44304997-4d7d8780-a39f-11e8-9796-42738839e283.png)

**Comment by debugtalk** [comment]
@angek2046 近期在做比较大的重构，数据结构有变化，我还没有更新文档。

**Comment by angek2046** [comment]
哦，这样么，我的版本是1.5.9确定也是因为重构影响的是吧

**Comment by angek2046** [comment]
重构的方向是什么呢，很感兴趣

**Comment by debugtalk** [comment]
@angek2046 pipline 吧
可以参考下这个图：
https://www.processon.com/view/link/5b263148e4b0c383b07bde17

**Comment by angek2046** [comment]
问一下，重构后的代码，可以支持以标准用例结构体来使用API分层么，之前看你的测试用例分层的文章，好像关于怎么使用讲的太少了，最后想问下，测试用例分层时，可以支持测试验证逻辑（提取器，验证器）与API分离么，我个人觉得这样会不会更灵活呢

**Comment by 363883636** [comment]
同样遇到此问题。

**Comment by debugtalk** [comment]
@angek2046 支持的。分层这块儿使用说明文档在补充了，不过现在还没完成。另外就是个别细节我还没想清楚，所以分层这块儿还没有完成优化。

**Comment by angek2046** [comment]
@debugtalk    yaml用例 可以分块么，像loadrunner那样，用例可以分为init,aciton,end三块，然后也可以分别对三块区域进行统一的迭代，这样的话，比如登录等操作可以放到init里面，只调用一次，大部分业务执行动作，可以放到action里面，可以进行迭代，然后又可以使用到requests的session,简化获取cookie难度，现在把登录，获取cookie放到函数里面执行，没办法和用例一起使用session特性，如果登陆做成一个case，又会多次执行

**Comment by debugtalk** [comment]
@angek2046 感谢反馈，我提取了一个优化点，后续会在 1.6 版本中实现。 #377

**Comment by angek2046** [comment]
@debugtalk   嗯，之前我试过，debugtalk和yaml是隔离的，无法共用session，你提取的的优化点，确实比我想的要好，另外我提到的，迭代控制的，目前httprunner在这块是比较弱的，为了有好的计划么

**Comment by debugtalk** [comment]
文档已更新： http://cn.httprunner.org/development/
