### ISSUE TITLE
关于加载api目录

### ISSUE THREAD

**Issue by whiteCcinn** [HttpRunner/HttpRunner#354]
你好，httprunner是1.5.10版本的的api文件加载的路径，被你写死了。

![image](https://user-images.githubusercontent.com/13690966/44537923-88cade00-a732-11e8-91e5-a0977733bc55.png)

这样子的话，就不太方便扩展框架了。。

希望这一部分实现得灵活一点，其实可以通过配置文件来指定对应文件的路径。

**Comment by whiteCcinn** [comment]
![image](https://user-images.githubusercontent.com/13690966/44538914-48b92a80-a735-11e8-920b-5bc794690c9f.png)

为了使用这个特性，强行加入了tests目录。有点难受。还是希望作者可以好好发挥配置文件的作用。晚点我pr一些代码，有机会的话一起维护一下

**Comment by debugtalk** [comment]
@whiteCcinn 你先升级到 1.5.11 试用下。

**Comment by debugtalk** [comment]
HttpRunner 遵循 “约定大于配置” 的原则，并不建议增加配置项。
