### ISSUE TITLE
[1.5.11] get "FileNotFoundError" error when run the test case via command “hrun xxx.yml”

### ISSUE THREAD

**Issue by HoferZhang** [HttpRunner/HttpRunner#357]
此问题发生的1.5.11
1.5.9版本上没问题

项目结构如下，其中，1.yml引用了1.csv

![image](https://user-images.githubusercontent.com/17896691/44655986-b4e3a900-aa29-11e8-9038-66ff9f34f7de.png)

当在project目录下运行 
```bash
hrun folder_A/folder_a1/1.ym
```
命令时，得到错误如下错误:
```bash
FileNotFoundError: [Errno 2] No such file or directory: '1.csv'
```

**Comment by cindy0403** [comment]
@debugtalk 
上面csv的路径写法是1.5.11的变更的地方吗。在1.5.10的时候好像不用完整路径也可以执行

**Comment by debugtalk** [comment]
@cindy0403 是的，1.5.11版本做了比较大的重构，文件加载机制做了调整。

**Comment by cindy0403** [comment]
@debugtalk 
感谢bug的快速解决，最近刚开始学习使用httprunner，发现版本更新的时候之前的一些特性可能也发生了改变（如1.5.11上改变了之前的热加载机制的相关用法），伴随版本更新有一点期待。
能否将版本的新特性和变更的地方集中总结个list，类似于每次发布新版本的时候能有一个记录更新内容的build note之类的。

**Comment by debugtalk** [comment]
@cindy0403 这个是有的：https://github.com/HttpRunner/HttpRunner/releases

不过现在 HttpRunner 还处于早期，功能还不够稳定，等到 1.6 以后应该就可以比较稳定和按照节奏更新发布了。
