### ISSUE TITLE
raise ApiNotFound when upgrading to 1.5.11

### ISSUE THREAD

**Issue by mikasaakaman** [HttpRunner/HttpRunner#358]
![default](https://user-images.githubusercontent.com/42764726/44711322-adcba200-aae0-11e8-8316-b8a98cca41bc.png)

**Comment by debugtalk** [comment]
@mikasaakaman 麻烦提供下你的项目目录结构，和你运行用例的方式。

**Comment by mikasaakaman** [comment]
![default](https://user-images.githubusercontent.com/42764726/44761451-c1751800-ab75-11e8-80cb-77198ae4d214.jpg)
运行方式：httprunner tests\testcases\folderA\demo1.yml  @debugtalk

**Comment by debugtalk** [comment]
@mikasaakaman 

HttpRunner 在 1.5.11 中逻辑进行了调整：

1、一个项目只能有一个 debugtalk.py 文件‘
2、运行时，首先定位 debugtalk.py，将其所在目录作为项目的根目录；
3、加载 api 时，api 文件夹的路径应该在项目根目录中。

因此，对于你这种情况，需要做的调整：

1、将多个 debugtalk.py 中的内容合并到一个 debugtalk.py
2、将 debugtalk.py 放置到 与 api 同级的目录下。
