### ISSUE TITLE
在大量并发下DNS解析会出问题。

### ISSUE THREAD

**Issue by junjunsay** [httprunner/httprunner#360]
Traceback (most recent call last):
ConnectionError: HTTPConnectionPool(host='ip', port=端口号): Max retries exceeded with url: url路径 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106831310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
网上解决方法：不使用python的DNS解析标准库，使用gevent内置的取代标准库的DNS解析模块.

**Comment by debugtalk** [comment]
@junjunsay 你有验证过么？是如何实现的？

**Comment by junjunsay** [comment]
我有验证过，数据存储到yml中，然后通过代码生成csv文件（只生成一列），testcase获取csv文件数据，然后传到suite中，suite通过testcase的数据去获取yml中的数据进行便利，大约进行到第605case的时候就会出现上面的错误。

**Comment by junjunsay** [comment]
@debugtalk

**Comment by junjunsay** [comment]
当大量的数据写入，等待一次次调用接口，请求接口，返回数据，在进行到一定阶段就会出现连接失败的现象，导致用例直接error，而不是fail

**Comment by 363883636** [comment]
同样遇到此问题。

**Comment by junjunsay** [comment]
我有验证过，数据存储到yml中(这个是自己定义的yml文件用于存储该接口的字段的各种情况的参数)，然后通过代码生成csv文件（只生成一列用于存储yml文件的名字），testcase获取csv文件数据，然后传到suite中，suite通过testcase的数据（yml文件的名字）通过代码去获取yml中的数据进行遍历，大约进行到第605case的时候就会出现上面的错误。

**Comment by junjunsay** [comment]
@debugtalk

**Comment by yucuifang** [comment]
请问最后解决了吗？ @debugtalk

**Comment by yucuifang** [comment]
遇到同样的问题+1
