### ISSUE TITLE
发送的请求默认把headers转为小写，导致无法识别到准确的头信息

### ISSUE THREAD

**Issue by XianyueQi** [HttpRunner/HttpRunner#373]
headers:
            Content-Type: application/json
            X-Tsign-Open-App-Id: "1111563841"
            X-Tsign-Open-App-Secret: "753b9f6acafcbba300315838be3374c1"

抓包后： 
x-tsign-open-app-id: 1111563841
x-tsign-open-app-secret: 753b9f6acafcbba300315838be3374c1

请问该如何解决，目前接口识别不了准确的头信息数据，抛异常

**Comment by debugtalk** [comment]
@XianyueQi 在之前的实现中，会将请求体中的 keys 转换为小写，目的是防止用户写错，例如将 url 写成 Url；

转换内容包括：

```
convert key in config dict to lower case, convertion will occur in three places:
1, all keys in config dict;
2, all keys in config["request"]
3, all keys in config["request"]["headers"]
```

其中，request headers 的确是没有必要进行转换，因此我在本次修复中将第 3 类转换去除了。

**Comment by 15652915156** [comment]
为啥我抓包看到headers里面的参数还是被转换成小写了啊？不是已经fix了吗？

**Comment by 15652915156** [comment]
原来是我的版本没更新
