### ISSUE TITLE
1.5.13版本引用csv文件，提示变量找不到

### ISSUE THREAD

**Issue by master-walker** [httprunner/httprunner#376]
![image](https://user-images.githubusercontent.com/28424626/45023117-67d68700-b068-11e8-9735-2eabee3d61ab.png)

![image](https://user-images.githubusercontent.com/28424626/45023292-b126d680-b068-11e8-889d-51af298213fa.png)

实际我在csv文件中是有这个字段的，在1.4.8版本运行就没有问题

**Comment by debugtalk** [comment]
@master-walker 

HttpRunner 在 1.5.11 中逻辑进行了调整：

1、一个项目只能有一个 debugtalk.py 文件；
2、运行时，首先定位 debugtalk.py，将其所在目录作为项目的根目录；
3、在用例中指定 CSV 时，CSV 文件的路径应该是相对于项目根目录的相对路径。

因此，在你升级到 1.5.11+ 后，需要在用例中对 csv 文件的路径进行修改。

**Comment by master-walker** [comment]
@debugtalk 我的csv文件放在 debugtalk.py同级目录下，也就是在项目根目录tests文件夹下的目录里，不行吗？ 要在用例中指定csv文件的相对路径？

**Comment by master-walker** [comment]
@debugtalk 试了下不论路径是tests/data/csvfile.csv ，还是data/csvfile.csv，还是报找不到
![image](https://user-images.githubusercontent.com/28424626/45027838-2d271b80-b075-11e8-9232-eb70db0411e9.png)

**Comment by debugtalk** [comment]
@master-walker 可否看下你的目录结构。

**Comment by debugtalk** [comment]
@master-walker 如果按照你的描述，应该是没有问题才对。你的用例文件方便传给我定位看下问题么？

**Comment by master-walker** [comment]
@debugtalk 邮件已发

**Comment by chenchengyuan** [comment]
是不是1.5.13版本更改了取变量方式，前两天换了台电脑，我安装了最新版跑原来用例也报错，应该是用$取不到值，后来我又降到了1.5.10版本就可以了
