### ISSUE TITLE
httprunner extract参数提取是否可以提取更多层的参数？

### ISSUE THREAD

**Issue by WuCh1k1n** [HttpRunner/HttpRunner#378]
如下的接口返回格式：

{
    'code': 0, 
    'msg': 'success', 
    'data': {
        'userID': '123', 
        'sdkUid': 111, 
        'token': '123', 
        'extension': []
        }
}
我需要提取token，那么需要如何书写用例？

**Comment by vilian00** [comment]
extract:
  - token: content.data.token

**Comment by WuCh1k1n** [comment]
刚发现可以这么点出来了。。多谢
