### ISSUE TITLE
Jenkins上运行hrun xxx.yml 提示编码错误

### ISSUE THREAD

**Issue by XianyueQi** [httprunner/httprunner#382]
Jenkins部署在Linux环境下，使用的是Python3.7
在Jenkins构建时运行 hrun xxx,yml，
返回：nicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
试了网上很多种方法都不行，求解，谢谢

**Comment by debugtalk** [comment]
@XianyueQi 提供下报错时的堆栈信息。
