### ISSUE TITLE
提供更加有效的错误信息

### ISSUE THREAD

**Issue by vonhng** [HttpRunner/HttpRunner#384]
### 简要描述

![image](https://user-images.githubusercontent.com/27840855/45206861-bed29b00-b2b8-11e8-84a0-a5d9186941dc.png)

如果开发者不是path输入，但是在json中未写入name或testcases字段，如果校验name和testcases不存在时返回False, 就又认为是path了，那么程序走进path逻辑部分报错，误导了开发者，我觉得在这里raise keyerror较好

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos]
 - Python 版本 [3.6]
 - HttpRunner 版本 [1.5.6]

**Comment by debugtalk** [comment]
@vonhng 感谢反馈。后续对测试用例格式的校验会使用 JSON Schema 替代，到时候这个问题也就一并解决了。 #326
