### ISSUE TITLE
测试用例分层相关文档问题

### ISSUE THREAD

**Issue by coreywei** [HttpRunner/HttpRunner#385]
1. 没看到文档对最新版本的测试用例/api/suite/testcases四种文件结构有严格定义。测试用例的结构，在http://cn.httprunner.org/testcase/structure/ 有一个，但应该也比较老了，比如，看了源码中的例子才知道，原来validate里面除了eq，还可以用len_eq，contains等。希望有一个严格的定义。
2. 在tests目录里面分层结构是api/suite/testcases，用hrun --startproject生成的结构是api/testsuites/testcases。到底以哪个为准
3. 概念不统一，见过的名词包括测试用例/测试用例集/api/suite/testsuite/testcase/testset/teststep，文档中使用有点混淆。同一个名词，在不同场景又可能代表不同的意义，比如用例分层/不分层时。

希望文档能跟代码同步更新，做得更严谨一些。

**Comment by debugtalk** [comment]
@coreywei 框架重构升级后，文档还没有完成更新。近期会集中更新下文档。

**Comment by coreywei** [comment]
还有一个问题就是测试用例分层页面是空的 http://cn.httprunner.org/advanced/testcase-layer/
@debugtalk

**Comment by XianyueQi** [comment]
@coreywei 我在使用测试分层的时候也碰到一些疑问，能加个qq交流下吗？我的：870463079

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/

**Comment by asdf2014** [comment]
@debugtalk 哇，真给力！！

**Comment by asdf2014** [comment]
@debugtalk 最近我写了一篇力荐 HttpRunner 的文章，可能用得比较粗浅，有不妥的地方，欢迎提 comment，随时更正 :smile:

https://yuzhouwan.com/posts/190413#HttpRunner
