### ISSUE TITLE
https的接口请求发送不成功

### ISSUE THREAD

**Issue by youshuchang** [httprunner/httprunner#394]
## 问题描述

https的接口请求发送不成功

## 版本信息

 - Windows
 - Python 2.7.9
- HttpRunner 1.5.13

## 报错如下图：

因为涉及私人信息，做了个马赛克
![image](https://user-images.githubusercontent.com/10020516/45877675-3df3c300-bdd1-11e8-96f0-d9086b12aeb7.png)

## 项目文件结构
用例在G:\004-Study\httprunner 下
![image](https://user-images.githubusercontent.com/10020516/45877837-beb2bf00-bdd1-11e8-9721-b40872d4d974.png)

**Comment by youshuchang** [comment]
@debugtalk 好的，谢谢您的回答~~~~

**Comment by coreywei** [comment]
@debugtalk 这个知识点可以写进文档里，估计很多人都不知道

**Comment by youshuchang** [comment]
@coreywei 同意~~当时查资料是说要把 verify改成 False，但是不知道去哪里设置这个东西~~~还以为要去改源码，哈哈哈~~~

**Comment by debugtalk** [comment]
嗯好的。

**Comment by maxiaoqian** [comment]
> 嗯好的。

为什么我加了verify=False还是这样
![image](https://user-images.githubusercontent.com/12823798/71799865-66b8ce00-3091-11ea-9a34-119720f91698.png)

系统：Linux ，python3.7，httprunner2.5.2

**Comment by Linxi-brave** [comment]
> 请求 HTTPS 接口时，若本地开启了代理软件（Charles/Fiddler），由于 HTTPS 证书的原因，会导致 SSLError 的报错。
> 
> 解决的方式是，在 config 中增加 `verify: False`，原理见 requests 的 [`SSL Cert Verification`](https://requests.kennethreitz.org/en/master/user/advanced/#ssl-cert-verification) 部分。
> 
> ```yaml
> config:
>     name: XXX
>     base_url: XXX
>     verify: False
> ```

我也出现提示：(Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)')))
然后把所有的代理软件都关闭了，并且在config中也有设置 .verify(False)，但是还是出现一样的错误。

**Comment by youshuchang** [comment]
> > 嗯好的。
> 
> 为什么我加了verify=False还是报错
> ![image](https://user-images.githubusercontent.com/12823798/71799865-66b8ce00-3091-11ea-9a34-119720f91698.png)
> 
> #### 版本信息：
> * Linux
> * python 3.7
> * httprunner 2.5.2

你的报错不是证书验证不通过，是SSL moule is not available

**Comment by youshuchang** [comment]
> > 请求 HTTPS 接口时，若本地开启了代理软件（Charles/Fiddler），由于 HTTPS 证书的原因，会导致 SSLError 的报错。
> > 解决的方式是，在 config 中增加 `verify: False`，原理见 requests 的 [`SSL Cert Verification`](https://requests.kennethreitz.org/en/master/user/advanced/#ssl-cert-verification) 部分。
> > ```yaml
> > config:
> >     name: XXX
> >     base_url: XXX
> >     verify: False
> > ```
> 
> 我也出现提示：(Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)')))
> 然后把所有的代理软件都关闭了，并且在config中也有设置 .verify(False)，但是还是出现一样的错误。

因为你的这个报错和我那个报错不一样，不是证书验证的问题，你可以用你的报错信息查下资料
