### ISSUE TITLE
多线程调用出错

### ISSUE THREAD

**Issue by 18618295211** [httprunner/httprunner#400]
## Describe the bug

用多线程方式调用httprunner, 某个线程会出现exception，返回的head,body为空。如果另一个线程执行完，出问题的线程就可以正常工作。非必现（有时多个线程都是正常的）。
是不支持多线程吗？

## Versions

 - OS: [ Windows]
 - Python [e.g. 3.6]
 - HttpRunner [e.g. 1.4.5]

**Comment by Xweirdo** [comment]
大佬，可以请问你是如何实现多线程的吗？我的测试用例也特别多，不知道该在哪里实现多线程。

**Comment by 18618295211** [comment]
是 自己在外面包的方法，httprunner支持传入（testsets）结构。
def test():
    #multi thread
    runner=HttpRunner.run(testsets)

**Comment by xiaomanyaoer** [comment]
这样会生成多个报告吧？

> 是 自己在外面包的方法，httprunner支持传入（testsets）结构。
> def test():
> #multi thread
> runner=HttpRunner.run(testsets)

这样会生成多个报告吧？
