### ISSUE TITLE
中文编码问题

### ISSUE THREAD

**Issue by doudou-china** [HttpRunner/HttpRunner#404]
python 2.7.3
httprunner 1.5.13
linux
校验中文时，报这个错误:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)

**Comment by debugtalk** [comment]
@doudou-china 要定位问题需要提供堆栈信息。

另外，建议使用 Python 3，Python 2.7 版本后续将不再维护。
