### ISSUE TITLE
locust提示‘global name 'loader' is not defined“

### ISSUE THREAD

**Issue by WhereTo** [HttpRunner/HttpRunner#408]
原因定位是其中有两个文件，在import的时候采用：from loader import XX
但是调用的时候，采用 loader.XX去调用

解决方法：搜索到两个文件，将loader.XX改成XX

**Comment by lk236225128** [comment]
我在ubuntu中搭建后，也出現了一個類似的問題，在執行locusts -f xxx.yml執行性能壓測，會提示“NameError: name 'loader' is not defined”。
有查看到生成的locustfile.py中引入from httprunner.loader import load_tests；
但調用時使用了self.testcases = loader.load_tests(self.locust.file_path)。

原也以為改了就可以了，但執行locusts -f xxx.yml的CLI每次都會重新生成locustfile.py。。。

**Comment by debugtalk** [comment]
@WhereTo 你是在运行 locusts 的时候遇到的问题么？可否按照 issue 指引文档再详细描述下？

**Comment by lk236225128** [comment]
謝謝解答，我把httprunner/templates/locustfile_template也改了，但不知為何，執行命令時生成的locustfile.py沒有套用修改后的template。

**Comment by debugtalk** [comment]
升级到 2.0 版本，在 locustfile 中不会再涉及到 `loader` 的引用。
