### ISSUE TITLE
extract取接口返回的多个参数怎么取？

### ISSUE THREAD

**Issue by fuersher** [HttpRunner/HttpRunner#409]
1.接口返回信息如下：
{
	"code": 200,
	"result": {
		"count": 4,
		"list": [{
			"answer": "你很好",
			"contentId": "d2b3a808977c44edb39eecb0395a041f",
			"contentType": 4,
			"id": 10170,
			"question": "你还呀修改一下"
		}, {
			"answer": "你很好",
			"contentId": "eb0f8441422c46c48d4c5db5c9bb44d6",
			"contentType": 4,
			"id": 10175,
			"question": "你还呀"
		}]
	},
	"success": true
2.想用extract同时取2个id的值

**Comment by linglingfa1212** [comment]
"extract" :[
                { "id1" :"content.data.0.id"}，
                { "id2" :"content.data.1.id"}
            ],

**Comment by fuersher** [comment]
> “extract”：[ 
> {“id1”：“content.data.0.list [0] [”id“]”}，
> {“id2”：“content.data.1.list [1] [”id“] “} 
> ]，
谢谢你的回答，但是我想是只用 "id1"同时取list中的[0]和[1]，可以实现吗？

**Comment by linglingfa1212** [comment]
做不到，你可以把response传到debugtalk里面去，进行数据提取，然后在放到list中

**Comment by fuersher** [comment]
@linglingfa1212 好的~ 谢谢你(*^▽^*)

**Comment by wangtesting** [comment]
> 把response传到debugtalk里面去，进行数据提取，成功解决了问题ヾ(◍°∇°◍)ﾉﾞ
> 
> * test:
>   name: Robotchannel_chooselist
>   variables:
>   - name:
>   - pageNo: 1
>   - pageSize: 10
>   - type:
>   api: api_v1_Robotchannel_choose_POST($name, $pageNo, $pageSize, $robotId, $type)
>   extract:
>   
>   * rep: content
> * test:
>   name: Robotchannel_add
>   variables:
>   - channelIdList: ${channel_list($rep)}
>   api: api_v1_Robotchannel_add_POST($channelIdList, $robotId)

给力啊，老哥
