### ISSUE TITLE
异常断言报告不展示

### ISSUE THREAD

**Issue by yinquanwang** [HttpRunner/HttpRunner#411]
## 问题描述

测试报告只展示成功断言，异常不会展示

## 版本信息

 - 操作系统类型: [Windows10
 - Python 版本 3.5
 - HttpRunner 版本 1.5.14

## 用例
![image](https://user-images.githubusercontent.com/32924136/47192272-c89ef200-d37e-11e8-9596-39363bda4957.png)

## 报告
![image](https://user-images.githubusercontent.com/32924136/47192282-d9e7fe80-d37e-11e8-9b67-97ae2c7981a8.png)

**Comment by debugtalk** [comment]
已修复。
