### ISSUE TITLE
teardown_hook对response的修改体现在测试报告上

### ISSUE THREAD

**Issue by jcuan** [httprunner/httprunner#430]
## 问题描述

涉及到加密和解密的接口，最终测试报告展示的是hook修改前的，想在报告查看一下hook修改后的内容

## 版本信息

 - 操作系统类型: Windows 10
 - Python 版本 3.7.1
 - HttpRunner 版本 1.5.14

## 详细

在渲染报告前，我调试查看了一下runner返回的summary里边的response信息，这和hook修改的对象应该不是同一个，修改是没用的，新加一个属性也没用。
```python
def apiReceiveHook(response,m2):
    response.xxxxxx = apiDecrypt(response.text,m2)
    response.text = apiDecrypt(response.text,m2)
```
能不能支持将hook对response的修改体现在summary上，这样报告可以展示更多自定义的内容

**Comment by sirfengyu** [comment]
- $request为原始用例数据，为dict
```
    request['headers']['Content-Type'] = "html/text"
```

- $response 为response.ResponseObject,修改报告中展示的request，需修改此对象的值
```
    response.headers["Content-Type"] = "html/text"
    response.request.headers["Content-Type"] = "html/text"
```
