### ISSUE TITLE
debugtalk.py 如何变成一个 自定义模块呢？

### ISSUE THREAD

**Issue by hhuwc** [HttpRunner/HttpRunner#439]
有木有想过 不是一个 debugtalk.py 文件 而是一个 debugtalk 包  而且可以是多个 包  还可以 通过 debugtalk path  来配置

**Comment by debugtalk** [comment]
debugtalk.py 本来就是一个 Python module。
在最开始的版本中，HttpRunner 是支持多个 debugtalk.py 文件的，后面去掉了，因为一个文件就够了。
