### ISSUE TITLE
${} 一切皆表达式的想法

### ISSUE THREAD

**Issue by hhuwc** [HttpRunner/HttpRunner#442]
我看到 现在 有区分 变量 $var   和  函数 ${func()} 类型 ,  有没有想过一切皆表达式的概念 就是
${ }  这种 我都看作是个 表达式 ，其实函数返回的也是一个值 ，在这个基础上还可以做些其他的操作 比如
a = {"b":True}   我们可以  ${a["b"]}  函数的返回结果我们也可以 进行 运算   ${ get(${abc}) +  get2(${var})}
甚至于 还可以做一些 简单的运算  ${ [i for i in range(10) if i % 2 == 0]  }

-------------------------------------------------------------------------------------------------------------------
我想了下  觉得上面的解析存在 一定难度 于是 我想到了 另一种 方法  模仿 vue  模板绑定方式 
vue 中 绑定 一个   变量可以  <\a v-bind:href="url">...</a> 
我们在 json  文件中  也使用 这种绑定方式 绑定   变量  函数   凡是 以  wc:   开头的 就是 自定义函数  或者 就是 自定义变量 
${   }  仍然代表一个 表达式    所以  我们的语法  变为   ${  [ i   for i  in  wc:getlist( wc:var  )  ] } 这样
${   wc:a if  wc:a > 10 else 9}

------------------------------------------------------------------------------------------------------------------
今天粗略做出了原型 希望有空跟  作者你能交流下

**Comment by hhuwc** [comment]
![image](https://user-images.githubusercontent.com/20037388/48886504-34391b00-ee67-11e8-90d4-5fa2948d7221.png)
今天修改后支持 表达式语法

**Comment by hhuwc** [comment]
TODO 兼容原有 ${  }   $ 语法

**Comment by hhuwc** [comment]
对于 content  headers 的提取也可以使用 表达式方式    ${ resp.headers['content-type'] }

**Comment by debugtalk** [comment]
@hhuwc 非常感谢你的建议。

关于替换 $var 的表达方式，我的确有考虑过在 2.0 版本中进行调整，因为 $var 的方式只限定了左边界，而没有右边界，例如在遇到 "abc$var123" 的时候，本来变量名时 var，但实际解析会认为变量名称为 abc123。

近期也在研究 Jinja2 的模板语法，要在 YAML/JSON 中新增实现一套模板语言也是可行的。但这也可能带来更大的问题，就是将脚本复杂化了，并且极大地增加了脚本的灵活性。而对于测试用例这类对象来说，工程化和规范化应该更重要，而提供了太灵活的特性后，可能就达不到规范和统一的目标。

所以，在 HttpRunner 中实现类型 Vue 模板语法的功能不会考虑去实现，但对于变量和函数的引用方式是可以进行优化和调整的。

**Comment by hhuwc** [comment]
@debugtalk 目前公司内部使用的 被我改成了这样的语法 ${   test().subtest( v-bind:var1 )  +  test3(10 ) }
${  v-bind:var2["key1"]}
其实想出这个的主要原因在  函数 ，或者变量的简单运算 很不方便，没法做到 多个函数 基本的加减，没法针对变量做 简单操作 甚至于 访问操作都不行，后来发现 所谓的提取 ，校验其实也是 针对变量操作
所以就统一了语法 ，

**Comment by debugtalk** [comment]
从 2.1.2 开始，HttpRunner 已支持使用 ${var} 的方式来引用变量，之前 $var 的引用方式同时也保留。

**Comment by hhuwc** [comment]
很6啊 ，没想到你真的采纳了，我之前还魔改了一版本，
