### ISSUE TITLE
HttpRunner项目打包

### ISSUE THREAD

**Issue by linglingfa1212** [HttpRunner/HttpRunner#454]
## 问题描述

如何将HttpRunner项目打包，类似于使用pyinstaller打包成一个exe文件，然后复制到其他机器，可以点击exe文件，直接运行test cases？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Windows]
 - Python 版本 [3.6]
 - HttpRunner 版本 [1.5.11]

**Comment by debugtalk** [comment]
@linglingfa1212 当前没有直接实现该功能。

你可以自己写个 bat/bash 脚本，在里面配置好你要运行的用例，然后在执行测试时运行该脚本。
