### ISSUE TITLE
1.5.15运行case无法读取到.env中的数据

### ISSUE THREAD

**Issue by zlychelsea** [HttpRunner/HttpRunner#465]
![image](https://user-images.githubusercontent.com/14027546/49919911-3846de80-fee3-11e8-9250-a1871729d95d.png)

**Comment by debugtalk** [comment]
使用 ENV 内置方法获取在 .env 中定义的环境变量。

**Comment by Wangmin362** [comment]
我去，还有内置变量这种东西啊，看了官方文档里面也没说，希望有空还是完善下文档   @debugtalk
