### ISSUE TITLE
测试报告中，failure的案例validators值不正确

### ISSUE THREAD

**Issue by yurenjie1990** [HttpRunner/HttpRunner#471]
## 问题描述
在案例执行成功时，runner.summary中的结果是正确的，失败时，失败案例的validators内容为上一个成功案例的validators的值。

## 版本信息

请提供如下版本信息：
 - 操作系统类型: Windows 10
 - Python 版本 3.7
 - HttpRunner 版本 1.5.15

## 项目文件内容（非必须）
**执行成功的案例record：**
![image](https://user-images.githubusercontent.com/36318439/50269755-4d36eb00-046a-11e9-8caf-c671d0455286.png)

**失败的案例record：**
![image](https://user-images.githubusercontent.com/36318439/50269777-6049bb00-046a-11e9-8ba0-6433709b2e5d.png)

**而两个案例的validate配置并不一样，**
![image](https://user-images.githubusercontent.com/36318439/50269936-ea921f00-046a-11e9-95fd-0fdf21fad2cf.png)

**Comment by FlagSir** [comment]
目前我的暂时解决办法是：
1.  context.py新增了validate_failSituation()
![image](https://user-images.githubusercontent.com/32131326/50331477-c0f3f900-0539-11e9-8991-8fb430c029fe.png)
2.在 runner.py修改了run_test()
![image](https://user-images.githubusercontent.com/32131326/50331524-e97bf300-0539-11e9-875f-18f5b0defbb3.png)

目前这个是我的临时解决方案，编程小白能力有限，如果各位有更好的方案麻烦分享一下，期待作者看看这个问题

**Comment by yurenjie1990** [comment]
> 目前我的暂时解决办法是：
> 
> 1. context.py新增了validate_failSituation()
>    ![image](https://user-images.githubusercontent.com/32131326/50331477-c0f3f900-0539-11e9-8991-8fb430c029fe.png)
>    2.在 runner.py修改了run_test()
>    ![image](https://user-images.githubusercontent.com/32131326/50331524-e97bf300-0539-11e9-875f-18f5b0defbb3.png)
> 
> 目前这个是我的临时解决方案，编程小白能力有限，如果各位有更好的方案麻烦分享一下，期待作者看看这个问题

赞！感谢提供解决方案。

**Comment by yurenjie1990** [comment]
> 目前我的暂时解决办法是：
> 
> 1. context.py新增了validate_failSituation()
>    ![image](https://user-images.githubusercontent.com/32131326/50331477-c0f3f900-0539-11e9-8991-8fb430c029fe.png)
>    2.在 runner.py修改了run_test()
>    ![image](https://user-images.githubusercontent.com/32131326/50331524-e97bf300-0539-11e9-875f-18f5b0defbb3.png)
> 
> 目前这个是我的临时解决方案，编程小白能力有限，如果各位有更好的方案麻烦分享一下，期待作者看看这个问题

我是这样修改的：
context.py中：
![image](https://user-images.githubusercontent.com/36318439/50392647-20951300-078b-11e9-9740-b39d76635309.png)
runner.py中
![image](https://user-images.githubusercontent.com/36318439/50392672-491d0d00-078b-11e9-8c6e-3aa047307e9b.png)

**Comment by FlagSir** [comment]
嗯。这样的确是简洁了很多，赞！

**Comment by debugtalk** [comment]
该问题已经在 2.X 版本中完成修复。
