### ISSUE TITLE
loader.py中，使用import_module加载debugtalk.py时有问题

### ISSUE THREAD

**Issue by wuyajun2016** [HttpRunner/HttpRunner#473]
我的需要实现的功能是：
1、调用httprunner里面的run方法运行以下结构的用例
![image](https://user-images.githubusercontent.com/19677714/50394061-a4ec9380-0795-11e9-9d88-08a26092d8ac.png)
2、每次run完成后，我就把上面1中的用例给删掉
3、当前有A、B两份用例，分别依赖于两个不同的debugtalk.py，而且debugtalk.py中都有一个test_url函数，A-debugtalk.py下面的test_url返回X，B-debugtalk.py下面的test_url返回Y
4、最后，执行A时调用了A的debugtalk.py；再执行B的时候也调用了A的debugtalk.py，这是咋回事呢？是不是loader.py中的importlib.import_module("debugtalk")方法有问题？请指教

**Comment by zhenyuStudy** [comment]
@wuyajun2016 你好，请问后来解决了么？我们在使用过程中也遇到这个问题！

**Comment by zhenyuStudy** [comment]
> @zhenyuStudy
> 修改了loader.py的部分源码
> ![image](https://user-images.githubusercontent.com/19677714/50955609-8fe16580-14f4-11e9-9470-4b33c023b5a4.png)
> ![image](https://user-images.githubusercontent.com/19677714/50955646-a7205300-14f4-11e9-9d13-ec78540264ae.png)
> 你参考下

@wuyajun2016 非常感谢，完美解决！

**Comment by debugtalk** [comment]
@wuyajun2016 @zhenyuStudy 
在最新的 HttpRunner 版本中，运行测试用例时会定位 debugtalk.py 并将其作为项目的根目录，因此一个项目中应该只有一个 debugtalk.py 文件。
