### ISSUE TITLE
graphQL类型的请求提示httprunner.exceptions.VariableNotFound: mobile is not found.

### ISSUE THREAD

**Issue by wallaceok** [HttpRunner/HttpRunner#474]
## 问题描述

graphQL类型的请求提示httprunner.exceptions.VariableNotFound: mobile is not found.
是不是目前不支持这种参数型请求？请求是json型如下：

```json
{
    "query": "\n        mutation Login($mobile: String!, $password: String!,$remember_me: Boolean) {\n          login:supplierLogin(mobile: $mobile, password: $password,remember_me: $remember_me)\n        }\n      ",
    "variables": {
        "mobile": "13500001111",
        "password": "000000",
        "remember_me": true
    }
}
```

每次执行都报这个错，尝试各种解决方法无果。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.15]

**Comment by debugtalk** [comment]
@wallaceok graphQL类型的请求我没接触过，你可以看下使用 requests 库可以直接写不，如果不行的话那就是不行。

**Comment by feiminjie** [comment]
@debugtalk  您好，我也遇到相同的问题，graphql请求类型大概会在什么时候有更新？
一、httprunner请求，请求报错httprunner.exceptions.VariableNotFound: input
      json:
        operationName: "signin"
        query: "mutation signin($input: SignInUserInput!){\n  signInUser(input: $input){\n   access_token {\n      id\n    }\n    success\n  }\n}"
        variables:
          input:
            email: "minjie@123122.com"
            password: "111111"

二、requests请求，请求通过
{
  "operationName": "signin",
  "query": " mutation signin($input: SignInUserInput!){\n  signInUser(input: $input){\n    access_token {\n      id\n    }\n    success\n  }\n}",
  "variables" : {
    "input":
    {
      "email": "minjie@1223123.com",
      "password": "111111"
    }
  }
}

**Comment by debugtalk** [comment]
如果 request 内容中包含 $ 符号，可使用 $$ 进行转义。
