### ISSUE TITLE
提个设计上的问题，httprunner是一直打算专注http协议的api测试么？

### ISSUE THREAD

**Issue by angek44** [HttpRunner/HttpRunner#477]
提个设计上的问题，httprunner是一直打算专注http协议的api测试么？
还是说有基于rpc的支持，比如thrift的，有打算基于你的做二次开发，看看能不能支持不同协议的测试

**Comment by debugtalk** [comment]
@angek44 HttpRunner 底层是基于 Requests，因此其适用性很大程度上取决于 Requests。

**Comment by debugtalk** [comment]
@angek44 HttpRunner v4.0 发布了，新增支持了多协议扩展，不再局限于 HTTP 协议了。
https://httprunner.com/blog/release-v4/
