### ISSUE TITLE
求助帖：在线等，急！ 找不到HttpRunner类

### ISSUE THREAD

**Issue by invisibleDesigner** [HttpRunner/HttpRunner#480]
## 问题描述
在2.x文档中的开发扩展里，我在python脚本里写入
from httprunner import HttpRunner
但是httprunner下没有HttpRunner类，Ctrl点进去，发现__init__.py文件为空，请问
这是不是一个bug？还是我哪里没有配置好呢？
## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. Win10 Pro]
 - Python 版本 [e.g. 3.7.2]
 - HttpRunner 版本 [e.g.  2.0]

## 堆栈信息

无堆栈信息

## 项目文件结构

直接在一个空包文件下，写了一个test.py文件

## 项目文件内容（非必须）

from httprunner import HttpRunner

<img width="257" alt="httprunner" src="https://user-images.githubusercontent.com/21983419/50746086-5f859700-1268-11e9-878d-76b94065fb8f.png">

**Comment by guolong123** [comment]
![image](https://user-images.githubusercontent.com/22833963/50746508-5b5a7900-126a-11e9-8c82-45c2a4db6562.png)

**Comment by invisibleDesigner** [comment]
晕，文档没更新的问题。。。还好遇到了大神，非常感谢

**Comment by invisibleDesigner** [comment]
还想问一下，是不是windows系统下，执行pipenv run python -m unittest discover，本就会出错啊？这句话出现在2.x文档下的安装说明下的，开发者模式。

**Comment by guolong123** [comment]
@invisibleDesigner 这个我没用过，我调试都是直接在pycharm里面debug的。
