### ISSUE TITLE
parameters定义后，提示未找到keyname

### ISSUE THREAD

**Issue by liu-walker** [HttpRunner/HttpRunner#483]
"test": {
			"name": "模糊查询",
			"parameters": [
                {"man_name": ["李白","王安石"]}
            ],
			"request": {
				"url": "https://api.apiopen.top/likePoetry",
				"params": {
					"name": "$man_name"
				},
				"method": "GET"
			}

提示：httprunner.exceptions.VariableNotFound: man_name is not found.
parameters放在config全局中也同样提示

**Comment by invisibleDesigner** [comment]
parameters现在改版了，新版文档还没更新

**Comment by invisibleDesigner** [comment]
要使用的话，得使用testcases，具体参考作者的tests文档

**Comment by liu-walker** [comment]
> 
> 
> 要使用的话，得使用testcases，具体参考作者的tests文档

好的，谢谢
