### ISSUE TITLE
httprunner.exceptions.ApiNotFound

### ISSUE THREAD

**Issue by mpc2008cn** [HttpRunner/HttpRunner#484]
## 问题描述
尝试在各种路径下执行,均报api not found

## 版本信息
 - 操作系统类型: Win10
 - Python 版本: 3.7.2
 - HttpRunner 版本 2.0.0

## 堆栈信息
![image](https://user-images.githubusercontent.com/11917818/50827224-e164e580-1378-11e9-8d47-43bba2849571.png)

## 项目文件结构
![image](https://user-images.githubusercontent.com/11917818/50827292-06f1ef00-1379-11e9-84da-b7090d74c374.png)

## PS
打印的`tests_def_mapping["api"]`值为
```
{'D:\\AutoTestProject\\TestScript\\PublicApi\\api\\v1\\Ticker.yml': {'api': {'def': 'api_v1_ticker($symbol)', 'request': {'url': '/v1/ticker', 'method': 'GET', 'params': {'symbol': '$symbol'}}, 'validators': [{'eq': ['status_code', 200]}]}}}
```

**Comment by guolong123** [comment]
2.0.0的语法变了。可以参考作者项目中test目录下的demo

**Comment by mpc2008cn** [comment]
> 2.0.0的语法变了。可以参考作者项目中test目录下的demo

谢谢,可以了~
