### ISSUE TITLE
多个测试用例实现变量共享

### ISSUE THREAD

**Issue by YanwuWang** [httprunner/httprunner#485]
目前的实现思路是：先抽取响应中的值， 然后调用函数，将该值保存在一个自定义的配置文件中, 其他用例文件通过调用函数，获取该全局变量。

 目前遇到的问题有： 
方式1，在用例的validate中调用函数，保存该值，但设置多个全局变量（多次调用）时，出现问题，只能保存最后一个。

 方式2，在用例的teardown_hooks中调用函数，但不能引用extract中的变量 

 目前，postman 中可以方便的设置全局变量，使用：pm.environment.set("token", token);就可以了。
  想问下httprunner有没有什么方式可以方便的设置全局变量？

**Comment by YanwuWang** [comment]
问题已经解决。 使用方式1，可以设置全局变量。之前设置多个全局变量，只能保存一个的原因已经找到。

**Comment by YanwuWang** [comment]
@debugtalk  在validate中调用函数设置全局变量总觉得不是太优雅， 可不可以考虑下方式2，让teardown_hooks中调用函数时，可以引用extract中的变量。谢谢

**Comment by YanwuWang** [comment]
![image](https://user-images.githubusercontent.com/19180238/50898768-15a8d680-144b-11e9-841d-687c632bdd92.png)

**Comment by YanwuWang** [comment]
![image](https://user-images.githubusercontent.com/19180238/50898814-3a04b300-144b-11e9-94a3-a670d66b0367.png)
![image](https://user-images.githubusercontent.com/19180238/50898859-5bfe3580-144b-11e9-9ec8-dc8148e000d7.png)

**Comment by debugtalk** [comment]
@YanwuWang validate 是作为校验结果响应使用的，本不应该用于做其它处理。
你调用 teardown_hooks 的时候，可以使用 $response 将整个响应结果传入 hook 函数，你再在 hook 函数中操作即可。

**Comment by wangtesting** [comment]
> 另外，测试用例本身应该是相互独立的，需要避免相互依赖的情况。
> 假如需要引用其它测试用例的执行结果，则可以在测试用例中进行引用，可参考：
> https://github.com/HttpRunner/HttpRunner/blob/master/tests/testcases/create_and_check.yml

但是有复用用例的情况就会有这种情况了
