### ISSUE TITLE
为什么运行这个参数化的例子没有跑到所有的case？

### ISSUE THREAD

**Issue by bolt163** [httprunner/httprunner#487]
## 问题描述

请对遇到的 bug 进行简要描述。
运行这里提交的参数化例子，https://cn.httprunner.org/advanced/parameters/
**只跑完1个就没有往下面运行其他的case。。。** 这是为何？？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.11]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

【用例yml文件】
“
- config:
    name: "user management testcase."
    parameters:
        - user_agent: ["iOS/10.1", "iOS/10.2", "iOS/10.3"]
        - app_version: ${P(app_version.csv)}
        - os_platform: ${get_os_platform()}
    variables:
        - user_agent: 'iOS/10.3'
        - device_sn: ${gen_random_string(15)}
        - os_platform: 'ios'
        - app_version: '2.8.6'
    request:
        base_url: http://127.0.0.1:5000
        headers:
            Content-Type: application/json
            device_sn: $device_sn

- test:
    name: get token with $user_agent, $os_platform, $app_version
    request:
        url: /api/get-token
        method: POST
        headers:
            app_version: $app_version
            os_platform: $os_platform
            user_agent: $user_agent
        json:
            sign: ${get_sign($user_agent, $device_sn, $os_platform, $app_version)}
    extract:
        - token: content.token
    validate:
        - eq: [status_code, 200]
        - eq: [headers.Content-Type, application/json]
        - eq: [content.success, true]
------------------------------
【运行结果】

ZOU-MC1:speeddemo tvprojtest$ python3 ../main-debug.py hrun --dot-env-path /Users/tvprojtest/Desktop/HttpRunner/speeddemo  data/demo_parameters.yml --log-level debug
INFO     Start to run testcase: user management testcase.
get token with iOS/10.3, ios, 2.8.6
cc4a82996a92bf96e5c2e2cfeca5b5e19327d5f3
INFO     POST /api/get-token
DEBUG    request kwargs(raw): {'headers': {'app_version': '2.8.6', 'os_platform': 'ios', 'user_agent': 'iOS/10.3'}, 'json': {'sign': 'cc4a82996a92bf96e5c2e2cfeca5b5e19327d5f3'}, 'verify': True}
E

======================================================================
ERROR: test_0000_000 (httprunner.api.TestSequense)
get token with iOS/10.3, ios, 2.8.6
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tvprojtest/Desktop/HttpRunner/httprunner/api.py", line 54, in test
    test_runner.run_test(test_dict)
  File "/Users/tvprojtest/Desktop/HttpRunner/httprunner/runner.py", line 347, in run_test
    self._run_test(test_dict)
  File "/Users/tvprojtest/Desktop/HttpRunner/httprunner/runner.py", line 234, in _run_test
    **parsed_test_request
  File "/Users/tvprojtest/Desktop/HttpRunner/httprunner/client.py", line 181, in request
    url = build_url(self.base_url, url)
  File "/Users/tvprojtest/Desktop/HttpRunner/httprunner/utils.py", line 63, in build_url
    raise ParamsError("base url missed!")
httprunner.exceptions.ParamsError: base url missed!

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
DEBUG    
================== Variables & Output ==================
Type   | Variable         :  Value
------ | ---------------- :  ---------------------------

--------------------------------------------------------

DEBUG    No html report template specified, use default.
INFO     Start to render Html report ...

**Comment by TesterChen** [comment]
同样的问题，parameters参数配置无论如何配置，均无法正确遍历参数实现数据参数化执行
