### ISSUE TITLE
HttpRunner开发者模式下运行遇到的问题

### ISSUE THREAD

**Issue by cairuichun** [HttpRunner/HttpRunner#489]
## 问题描述
没有通过pip install等方式安装httprunner，而是直接开发者模式，将代码clone到本地，运行时有几个问题一直没搞明白：
1、怎样处理才能让我的项目放在我自定义的文件夹里，目前我只能放在HttpRunner下
2、我在HttpRunner目录下执行用例如下:
`pipenv run python /HttpRunner/main-debug.py hrun /HttpRunner/dist/testcases/xxx.yml`
发现存在两个问题：
（1）如果有调用.env时，会提示.env format error
（2）如果通过$var引用debugtalk.py中的变量时，会无法引用成功，如xx not found
3、怎样处理才能让我运行时只需要输入hrun path/xxx.yml就可以执行用例，目前都是要输入pipenv run python /HttpRunner/main-debug.py

我比较菜，也不知道是不是操作的问题，望大神指导下

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: ubuntu
 - Python 版本3.6
 - HttpRunner 版本2.0

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by cairuichun** [comment]
第2个问题解决了
   关于.env问题，我检查多遍还是觉得填写格式没问题，然后我删除了再重新写，之后就没报错了，懵~
   关于debugtalk.py问题，原来httprunner2.0中，用例中不能直接引用py文件中的变量，需要写个get_xxx()函数，然后通过函数调用就可以了

**Comment by TesterChen** [comment]
你数据参数化功能正常吗？配置了parameters并不生效，始终认为是一个参数，分不出多个参数来执行

**Comment by cairuichun** [comment]
> 你数据参数化功能正常吗？配置了parameters并不生效，始终认为是一个参数，分不出多个参数来执行

我这边试了，发现也是没生效，都是只能通过variables来进行传参

**Comment by 406722575** [comment]
> > 你数据参数化功能正常吗？配置了parameters并不生效，始终认为是一个参数，分不出多个参数来执行
> 
> 我这边试了，发现也是没生效，都是只能通过variables来进行传参

同遇到，不知道如何解决

**Comment by debugtalk** [comment]
@cairuichun 

1、如果你要正常使用，使用 pip 安装吧。
2、存在 .env 时，除了自己在 debugtalk.py 中写方法获取环境变量，还可以使用 ENV 内置方法直接获取在 .env 中定义的环境变量，省去定义方法的操作。
3、可以先执行 `pipenv shell` 进入虚拟环境，后续就可以不再每次输入 `pipenv run ` 了

**Comment by debugtalk** [comment]
@TesterChen @406722575 参数化 parameters 改为在 testsuite 中实现，可以参考项目的 demo：

https://github.com/HttpRunner/HttpRunner/blob/master/tests/testsuites/create_users_with_parameters.yml
