### ISSUE TITLE
ModuleNotFoundError: no module named 'tests.api_server' 如何解决

### ISSUE THREAD

**Issue by tingshine** [HttpRunner/HttpRunner#492]
## 问题描述
ModuleNotFoundError: no module named 'tests.api_server'
执行案例时报错

## 版本信息

    操作系统类型: Win10
    Python 版本: 3.7.1
    HttpRunner 版本: 2.0.0

## 堆栈信息
![default](https://user-images.githubusercontent.com/16952352/51187380-b816fd00-1916-11e9-9986-87b0f8dab2c0.png)
![default](https://user-images.githubusercontent.com/16952352/51187448-d67cf880-1916-11e9-9b97-ebb19e0e1b50.png)

## 项目文件内容（非必须）
![default](https://user-images.githubusercontent.com/16952352/51187273-6e2e1700-1916-11e9-975c-1556ec9731b7.png)

**Comment by tingshine** [comment]
已经处理了，拉取的新的源码api_server.py  中包名有问题。  不是很熟悉python

**Comment by fuersher** [comment]
> 已经处理了，拉取的新的源码api_server.py中包名有问题。不是很熟悉python

请问是怎么解决的啊(｡･∀･)ﾉﾞ

**Comment by wuhong1014** [comment]
该问题如何解决，大佬

**Comment by debugtalk** [comment]
>已经处理了，拉取的新的源码api_server.py  中包名有问题。  不是很熟悉python

@tingshine 你的问题在于，你将测试用例放到 httprunner 仓库的 tests 目录中了，执行用例时检测到了 debugtalk.py 了。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiaoping607** [comment]
> > 已经处理了，拉取的新的源码api_server.py中包名有问题。不是很熟悉python
> 
> 请问是怎么解决的啊(｡･∀･)ﾉﾞ

要执行的yml文件放在testcase里，命令行切换到该目录下，执行hrun **.yml文件就行了

**Comment by xlonga** [comment]
> > 已经处理了，拉取的新的源码api_server.py中包名有问题。不是很熟悉python
> 
> 请问是怎么解决的啊(｡･∀･)ﾉﾞ

在debugtalk.py目录下执行文件报错需要将该文件中第七行代码修改如下
from api_server import HTTPBIN_SERVER, gen_md5, get_sign
