### ISSUE TITLE
使用hook机制时将参数值放在yml中无法执行，将参数值放入debugtalk后可以执行

### ISSUE THREAD

**Issue by x1070757525** [HttpRunner/HttpRunner#493]
小白一只，各种 骚操作笑笑就好
错误：
![image](https://user-images.githubusercontent.com/38913412/51235706-27d6c780-19ab-11e9-8d5b-25137c25cfa2.png)
![image](https://user-images.githubusercontent.com/38913412/51235718-31f8c600-19ab-11e9-975c-9e8d0b225063.png)
无报错，但是SQL未执行！！
将SQL在debugtalk中赋值，将变量放入原SQL处，仍然无法执行（已加$）...

正常执行：
![image](https://user-images.githubusercontent.com/38913412/51235643-05dd4500-19ab-11e9-9d6a-b27fec6db9f9.png)
![image](https://user-images.githubusercontent.com/38913412/51235663-155c8e00-19ab-11e9-8513-36f93d56fca5.png)

**Comment by guolong123** [comment]
你可以看看是不是config中hook函数的原因，在test层去setup试试行不行

**Comment by JacobHZ** [comment]
还有一种方法你没试，把sql放variables里面
variables:
   - sql: 'DELETE FROM .....'
teardown_hooks:
  - ${run_mysql($sql)}

**Comment by debugtalk** [comment]
@JacobHZ 这种方式是正确的，也推荐使用这种方式。

@x1070757525 问题在于，在 YAML/JSON 中调用函数的时候，函数和参数识别完全是基于正则匹配，因此你传入的参数值 `"DELETE FROM page_strategy"` 字符串是包含引号的 `"`，如果你写为不带引号的就正常了。

```yaml
setup_hooks:
    - ${run_mysql(DELETE FROM page_strategy)}
```

**Comment by redvoilin** [comment]
sql中需要拼接参数怎么办，比如where id = ,这个id又是response中返回的
