### ISSUE TITLE
base url missed

### ISSUE THREAD

**Issue by zhanghuafei** [HttpRunner/HttpRunner#496]
## 问题描述

执行中文用户手册的demo-quickstart-4.json case时报“base url missed”错误

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7.2]
 - HttpRunner 版本 [2.0.1]

## 堆栈信息

C:\Users\zhinf\.virtualenvs\HttpRunner-DKg4rkC3\Scripts\python.exe K:/Python/HttpRunner/main-debug.py hrun K:\Python\demo-quickstart-4.json
/api/get-tokenINFO    
 Start to run testcase: testcase description

/api/users/1000
INFO    
 POST /api/get-token
EE
ERROR: test_0000_000 (httprunner.api.TestSequense)
/api/get-token

Traceback (most recent call last):
httprunner.exceptions.ParamsError: base url missed!

**Comment by debugtalk** [comment]
From version 2.0, request is no longer exist in config block, and base_url is located in the first level of config.

```yaml
- config:
    name: xxx
    base_url: xxx
```

**Comment by debugtalk** [comment]
Documents updated.
