### ISSUE TITLE
PyUnitReport堆栈信息的中文字符编码异常

### ISSUE THREAD

**Issue by yinquanwang** [HttpRunner/HttpRunner#50]
用例失败，trace堆栈信息，name是以十六进制输出，建议修复次bug

**Comment by yinquanwang** [comment]
麻烦尽快修复，调试的时候感觉太不方便了，还有给个建议，可以把请求数据，和返回数据记录在报告里么，有时想查下数据，没有记录 感觉不是很方便

**Comment by yanghuo662** [comment]
同样有这样的需求，能否把请求数据和返回数据记录在报告里，方便查看

**Comment by debugtalk** [comment]
PyUnitReport 这个测试报告框架比较简陋，后续计划集成 allure，实现更强大的测试报告展现。

**Comment by debugtalk** [comment]
@yanghuo662 已经有了，包含详细的请求响应数据，若有异常，还会包含traceback。

![image](https://user-images.githubusercontent.com/3657070/36664134-b6437f18-1b1e-11e8-9d22-b67eff17b0d4.png)
![image](https://user-images.githubusercontent.com/3657070/36664150-c224d9b2-1b1e-11e8-97f0-f83a043050a3.png)
![image](https://user-images.githubusercontent.com/3657070/36664165-ceb629f6-1b1e-11e8-85ac-36ff6fddf8c6.png)
