### ISSUE TITLE
[新需求]新增可以设置删除或新增请求字段的关键字

### ISSUE THREAD

**Issue by fuwuyong** [HttpRunner/HttpRunner#501]
版本:v2.0.0
原因:写接口异常用例时，比如有缺少某个必填字段，则需要新增一个yaml，会造成同一个接口有多个yaml文件
当前解决方案:修改源码，新增了delete关键字，在runner.py文件119行新增判断逻辑，如果存在delete关键字则删除请求中的该键
优点:解决了以上存在的问题
缺点:当前只支持删除json格式且只能删除test_dict["request"]["json"][delete_key]

**Comment by debugtalk** [comment]
@fuwuyong 缺少某个必填字段只是异常接口用例中的一种情况，为了这一种情况而单独设置一个关键字，增加框架的复杂度的同时，也并不能解决通用性的问题。
