### ISSUE TITLE
from httprunner.api import HttpRunner  中gen_html_report 方法不存在

### ISSUE THREAD

**Issue by junjunsay** [httprunner/httprunner#502]
直接调用api 中的gen_html_report 方法 提示不存在
 - 操作系统类型: macos
 - Python 版本 [2.7]
 - HttpRunner 版本 [2.0.0]
错误信息
    runner.gen_html_report(
AttributeError: 'HttpRunner' object has no attribute 'gen_html_report'
发现在api.py 中并无该方法，同时若要使用可以import httprunner.report 调用render_html_report 方法

**Comment by chenhengjie123** [comment]
感谢反馈。

确实如您所说，从 2.0.0 开始， `gen_html_report` 调整为了 httprunner.report 中的 `render_html_report  ` ，文档没做好对应的更新。

**Comment by debugtalk** [comment]
已更新文档：https://docs.httprunner.org/development/dev-api/#html
