### ISSUE TITLE
httprunner V2.0.2版本在config中配置headers，运行用例时，test中无法获取confing中设置的headers值

### ISSUE THREAD

**Issue by huiCSDN** [httprunner/httprunner#505]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.0.2]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
![image](https://user-images.githubusercontent.com/39902909/53063194-48d88e00-34fe-11e9-9557-7ea76c8fa905.png)

**Comment by Xweirdo** [comment]
同问这个问题。。

**Comment by LinForest** [comment]
request不能在config中配置了，在api或test中
