### ISSUE TITLE
对于测试用例分层的疑问 

### ISSUE THREAD

**Issue by huiCSDN** [HttpRunner/HttpRunner#510]
请教一下，如果使用测试用例分层，在api中定义接口的请求参数中有必填参数，也有非必填参数，那在api中该如何定义，还有就是在testcase中如果要引用api中定义的接口，那想要输入这个非必填参数该怎么填写呢

**Comment by maricoliu** [comment]
遇到同样的问题

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/
