### ISSUE TITLE
httprunner最新版本(v2.0.2)中的config下的parameters不起作用

### ISSUE THREAD

**Issue by cnhkzyy** [httprunner/httprunner#515]
## 问题描述

用yaml描述测试用例，config设置parameters为列表的形式，运行后发现报错httprunner.exceptions.VariableNotFound: phoneNumber is not found.
## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows10
 - Python 版本 3.4.4
 - HttpRunner 版本 2.0.2

## 堆栈信息

Traceback (most recent call last):
KeyError: 'phoneNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
httprunner.exceptions.VariableNotFound: phoneNumber is not found.

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
INFO     Start to render Html report ...
INFO     Generated Html report: D:\program\workshop\my_httprunner\reports\1550560399.html

## 项目文件内容（非必须）
![image](https://user-images.githubusercontent.com/29578918/52997066-69e7a300-345a-11e9-87f6-692c88b595ec.png)

备注：安装httprunner 1.5.15后发现可以正常运行

**Comment by FrankWangJQ** [comment]
遇到了同样的问题,目前除了回滚找到别的解决方案了吗?

**Comment by cnhkzyy** [comment]
> 遇到了同样的问题,目前除了回滚找到别的解决方案了吗?

你好，没有解决。。这个真是神奇了。。感觉httprunner更新到2.0之后，官网的文档并没有更新。我现在还在疑惑，测试集的顺序怎么指定以及测试集之间的接口关联怎么处理。

**Comment by FrankWangJQ** [comment]
> > 遇到了同样的问题,目前除了回滚找到别的解决方案了吗?
> 
> 你好，没有解决。。这个真是神奇了。。感觉httprunner更新到2.0之后，官网的文档并没有更新。我现在还在疑惑，测试集的顺序怎么指定以及测试集之间的接口关联怎么处理。

新版本参数化 parameters 改为在 testsuite 中实现，可以参考项目的 demo：
https://github.com/HttpRunner/HttpRunner/blob/master/tests/testsuites/create_users_with_parameters.yml
祝好!

**Comment by debugtalk** [comment]
2.0 版本的参数化说明文档将在下周补上。
#503
