### ISSUE TITLE
断言通过后还是提示用例失败，实际已经成功了

### ISSUE THREAD

**Issue by YYwind** [httprunner/httprunner#517]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [ 3.6]
 - HttpRunner 版本 [2.0.2]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。
![image](https://user-images.githubusercontent.com/15962362/53083363-bbb32a80-3539-11e9-836f-dad9fad274a5.png)

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）
![image](https://user-images.githubusercontent.com/15962362/53083516-0af95b00-353a-11e9-8d32-2932303663ed.png)

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by Xweirdo** [comment]
你提取的字段写错了，大哥。。。你的源码里是提取 error， 接口返回的是content.errno
