### ISSUE TITLE
测试分层机制文档为空？

### ISSUE THREAD

**Issue by scuwjw** [HttpRunner/HttpRunner#519]
## 问题描述

测试用例分层机制文档为空，麻烦看下？
https://cn.httprunner.org/advanced/testcase-layer/

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.11]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/
