### ISSUE TITLE
如何删除接口生成的数据？

### ISSUE THREAD

**Issue by testerSunshine** [HttpRunner/HttpRunner#520]
## 问题描述

场景是这样的：
1、测试注册用户的时候，我要先删除那个注册的用户，确保此用户没有在环境中注册
2、调用数据库sql语句
看了setup_hooks，但是不是很理解sql语句放在那里，是不是要在debugtalk.py单独写一个操作db的方法delete_user()？在setup_hooks 调用这个$delete_user()达到目的？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本: 3.6
 - HttpRunner 版本 1.5.11

**Comment by debugtalk** [comment]
@testerSunshine 是的，需要在  debugtalk.py 创建一个函数，实现操作 db 的方法，然后通过 setup_hooks 进行调用。

**Comment by sharonyao1127** [comment]
> @testerSunshine 是的，需要在 debugtalk.py 创建一个函数，实现操作 db 的方法，然后通过 setup_hooks 进行调用。

请问 Httprunner 3.0版本，不使用 setup_hooks，在哪调用操作数据库的方法呢？
