### ISSUE TITLE
对测试用例分层的疑问

### ISSUE THREAD

**Issue by erolce** [HttpRunner/HttpRunner#526]
目前使用1.4.4版本
用例结构是：
api：1.yml
suite：1+2.yml
testcases：调用api和suite
目前是可以正常运行的
但是升级到2.x后，无法使用，一直在报找不到debugtalk中的变量或找不到suite
请问该如何解决

**Comment by erolce** [comment]
能否补充2.x的测试用例分层文档？

**Comment by xiaomanyaoer** [comment]
suite能够直接访问api

**Comment by cyliu1991** [comment]
![image](https://user-images.githubusercontent.com/21175786/54578186-b9a99200-4a39-11e9-8f6a-ece7ac32b4b1.png)
翻看之前的问题回答看到的，不知道题主是否在不同目录下创建了多个debugtalk.py文件。

**Comment by erolce** [comment]
> ![image](https://user-images.githubusercontent.com/21175786/54578186-b9a99200-4a39-11e9-8f6a-ece7ac32b4b1.png)
> 翻看之前的问题回答看到的，不知道题主是否在不同目录下创建了多个debugtalk.py文件。

没有多个debugtalk文件的

**Comment by debugtalk** [comment]
测试用例分层机制已补充文档：
https://cn.httprunner.org/advanced/testcase-layer/
