### ISSUE TITLE
env中定义的环境变量找不到

### ISSUE THREAD

**Issue by vwin** [HttpRunner/HttpRunner#528]
1. 在.env文件中定义了几个变量
2. 在debugtalk.py中用os.environ获取变量并打印出来，是ok的
3. 执行case，无法获取到已定义的变量

**Comment by vwin** [comment]
通过看源码已解决：获取env中定义的变量，通过${ENV(username)}获取
![image](https://user-images.githubusercontent.com/5998089/53486006-9175e580-3ac2-11e9-83bf-75569c4e98dd.png)

**Comment by timeliuhuan** [comment]
@vwin 请问你定义的变量是在项目根目录下的.env文件吗，我在.env文件中定义的变量，在测试用例中通过${ENV(username)}方式可以获取，但是debugtalk.py中使用os.environ只能获取到系统的环境变量，无法获取项目中的.env文件的变量，根目录下的.env文件中定义的环境变量和系统环境变量是不同的变量吧？

**Comment by vwin** [comment]
> @vwin 请问你定义的变量是在项目根目录下的.env文件吗，我在.env文件中定义的变量，在测试用例中通过${ENV(username)}方式可以获取，但是debugtalk.py中使用os.environ只能获取到系统的环境变量，无法获取项目中的.env文件的变量，根目录下的.env文件中定义的环境变量和系统环境变量是不同的变量吧？

os.environ["username"] = "xxx" 是设置环境变量，然后在case中通过${ENV(username)}获取
