### ISSUE TITLE
如何提取接口返回值是html的内容？

### ISSUE THREAD

**Issue by qinghuazhu** [HttpRunner/HttpRunner#533]
![857281fd-8cc4-47f3-a590-3b9a2b87df02](https://user-images.githubusercontent.com/22891449/53733433-ebf4b480-3ebb-11e9-813f-9d6d1b15c402.png)
![image](https://user-images.githubusercontent.com/22891449/53733441-f57e1c80-3ebb-11e9-891f-38441f9c74f2.png)

**Comment by debugtalk** [comment]
@qinghuazhu 采用正则匹配的方式进行指定。

```
extract:
    baidu: <titile>(.*)</title>
```
