### ISSUE TITLE
默认报告名称为什么是时间戳，为什么不直接用yyyy-mm-dd-HH-MM-SS-timestamp.html命名？

### ISSUE THREAD

**Issue by vwin** [HttpRunner/HttpRunner#536]

**Comment by coreywei** [comment]
因为这样不能保证唯一

**Comment by vwin** [comment]
> 因为这样不能保证唯一

那可以用yyyy-mm-dd-HH-MM-SS-timestamp.html 如果只用时间戳的话对查找不太友好

**Comment by debugtalk** [comment]
@vwin 因为在系统中生成报告后，文件本身就有时间的属性。

![image](https://user-images.githubusercontent.com/3657070/54109929-fca4ad80-441a-11e9-9560-393b382c70df.png)

**Comment by phonix512** [comment]
> 
> 
> @vwin 因为在系统中生成报告后，文件本身就有时间的属性。
> 
> ![image](https://user-images.githubusercontent.com/3657070/54109929-fca4ad80-441a-11e9-9560-393b382c70df.png)

我想把报告名称写死在哪里修改了？

**Comment by debugtalk** [comment]
>>  ...

@phonix512 之前有实现过指定报告名称，后面去掉了。问到这个需求的还不少，我后面再加回去吧。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
