### ISSUE TITLE
希望能够增加等待时间的支持

### ISSUE THREAD

**Issue by huanghaopeng** [HttpRunner/HttpRunner#538]
大量的测试场景中的测试步骤之间，由于系统业务需求，都需要加入等待时间以便于后续测试步骤的顺利开展（例如：下单的2分钟以后触发开奖），建议在测试步骤中加入等待时间的支持以便于这类测试的进行。

**Comment by debugtalk** [comment]
在 teardown_hooks 中添加 sleep 即可。
