### ISSUE TITLE
如果函数返回一个字典，如何取出字典里面的字段。

### ISSUE THREAD

**Issue by rainy0824** [HttpRunner/HttpRunner#54]
a函数返回一个字典，比如：{"channelId":1,"firstCommentId":123,"replyCommentId":123,"replyUserId":9972,"commentId":10957,"creater":9972}

在testcase里面，我要取出这个函数里面多个不同字段的值，改怎么写呢。

**Comment by rainy0824** [comment]
现在的笨办法是，再写几个函数，让函数返回单个字段，然后再取出来

**Comment by testwangchao** [comment]
可以看下源码，path：HTTPRunner/httprunner/response.py    _extract_field_with_delimiter方法，

**Comment by rainy0824** [comment]
@testwangchao  我的不是responese返回的值，我自定义的方法返回这么一个字典，${a()}.

**Comment by HenryHo1033** [comment]
> @testwangchao 我的不是responese返回的值，我自定义的方法返回这么一个字典，${a()}.

请问找到解决方法吗？
