### ISSUE TITLE
运行多个yml文件时, 各个文件中的teardown_hooks是在所有文件运行结束执行的吗？

### ISSUE THREAD

**Issue by wenney1212** [httprunner/httprunner#543]
## 问题描述

当运行指定目录下的所有yml文件时，每个文件中config下的teardown_hooks，是在所有文件运行结束后执行的吗？
我觉得应该在各自文件运行结束后执行当前文件中的teardown_hooks。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本  3.6
 - HttpRunner 版本 1.5.14

**Comment by chenhengjie123** [comment]
请阅读 <https://v1.httprunner.org/advanced/request-hook/> 这个文档，您需要的答案里面有。此 issue 先关闭。

若文档内容不能满足您的需要，请另外建立 issue 提出。
