### ISSUE TITLE
testsuit 运行用例为空 ， 单个用例运行是成功的

### ISSUE THREAD

**Issue by Davie-Duan** [HttpRunner/HttpRunner#547]
## 问题描述

使用数据驱动的方法运行testsuit 但是Run的用例为零

## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows10
 - Python 版本 3.6
 - HttpRunner 版本 2.01

## 堆栈信息

无

## 项目文件结构
![image](https://user-images.githubusercontent.com/31070343/54733545-2ad17c80-4bd5-11e9-8d4c-96c058c0ea21.png)

## 项目文件内容（非必须）
![image](https://user-images.githubusercontent.com/31070343/54733578-4c326880-4bd5-11e9-9fbc-c789a17ff8e8.png)

![image](https://user-images.githubusercontent.com/31070343/54733592-5a808480-4bd5-11e9-8502-91f673a35494.png)

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by debugtalk** [comment]
@Davie-Duan 在第三章截图中，看你的意思应该是测试用例集，写错了三个地方。

1、config  和 testcases 前面没有短横线，因为是第一层级是字典结构；
2、是 testcases，不是 testcase；
3、parameters 拼写错误。

详见文档：https://cn.httprunner.org/advanced/testcase-layer/
