### ISSUE TITLE
参数及response的加解密

### ISSUE THREAD

**Issue by WardGong** [HttpRunner/HttpRunner#55]
post请求及响应 都加密

**Comment by debugtalk** [comment]
@WardGong 可否将问题描述再详细些？

**Comment by WardGong** [comment]
就是请求参数不是明文传给接口的，用aes加密，接口返回的结果也是经过加密的。

**Comment by debugtalk** [comment]
@WardGong 那就自己实现加解密函数，放置到 debugtalk.py 中，然后在测试用例中调用就好了

**Comment by sirfengyu** [comment]
也遇到类似的需求，由于请求和响应都是密文，操作起来比较麻烦。有两点需求：
- 可以对请求参数进行解密后替换，再加密请求；
- 在测试报告中请求体、响应体都展示对应的明文，方便查看；
@debugtalk

**Comment by lao-guan** [comment]
> 也遇到类似的需求，由于请求和响应都是密文，操作起来比较麻烦。有两点需求：
> * 在测试报告中请求体、响应体都展示对应的明文，方便查看； --teardown_hooks,传request、response可以解决我这个问题

你好，请问在 teardown_hooks 传 request/ response 是怎么传？ 可以实现在测试报告中请求体、响应体都展示对应的明文
