### ISSUE TITLE
$+参数名没法取到本地全局变量的值

### ISSUE THREAD

**Issue by linglingfa1212** [HttpRunner/HttpRunner#552]
V2.0.6
请提供如下版本信息：

操作系统类型: Windows
Python 版本 3.6.5
HttpRunner 版本 2.0.6

将一些参数放到globals()中，在2.0.6中测试用例无法取到，在1.4.3版本中可以取到值，在2.0版本中，$方法是否不再取全局变量的值了？

**Comment by idibmzjm** [comment]
httprunner:  2.1.1
mac
Python 版本 3.6.4
我也遇到了这个问题，写到.env文件中的变量，在debugTalk.py中取到了以后，用$params方式无法取到。
最后写成方法解决的
![Uploading image.png…
<img width="354" alt="图片" src="https://user-images.githubusercontent.com/38128024/56361479-05f31800-621a-11e9-8bc7-d62285ea204e.png">
]()

**Comment by idibmzjm** [comment]
httprunner/parser.py
835行，改成  override_variables = utils.deepcopy_dict(project_mapping.get("env", {}))
这样就可以去到  .env中定义的变量了

**Comment by debugtalk** [comment]
如果是在 `.env` 中定义的变量，需要显式地通过 `${ENV()}` 方式来调用。
