### ISSUE TITLE
源码中的tests示例代码，运行有误

### ISSUE THREAD

**Issue by tester20183450** [HttpRunner/HttpRunner#556]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [e.g. 3.7]
 - HttpRunner 版本 [e.g. 2.x]

## 堆栈信息
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
实例项目在HttpRunner-master\tests目录下，已启动。

HttpRunner-master\tests\testcases>hrun create_and_check.yml
在testcases目录下，执行该yml文件

提示下列信息：
c:\python37\lib\site-packages\httprunner\loader.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_content = yaml.load(stream)
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
httprunner.exceptions.FileNotFound: C:\Users\54275\Downloads\HttpRunner-master\tests\testcases\testcases\setup.yml does not exist.

麻烦老哥，把示例代码改下吧。。。

**Comment by debugtalk** [comment]
@tester20183450 你需要在测试用例的根目录执行测试，根目录为 debugtalk.py 所在的目录。

```
$ hrun testcases/create_and_check.yml
```
