### ISSUE TITLE
python的py文件放到哪里可以直接引用

### ISSUE THREAD

**Issue by loudDD** [HttpRunner/HttpRunner#559]

**Comment by armoour** [comment]
我试了一下，可以在用例同目录下引用；

**Comment by loudDD** [comment]
歇歇

**Comment by debugtalk** [comment]
按照约定大于配置的原则，debugtalk.py 文件放置到自动化测试项目根目录，在引用 api/testcase 时相对路径就是被引用文件相对于 debugtalk.py 的路径。

推荐创建项目时采用 --startproject 脚手架进行创建。
