### ISSUE TITLE
由于接口使用了重定向，比如登录后被重定向到新的页面去了，如何获取到新页面中的相关信息呢

### ISSUE THREAD

**Issue by ckl0804** [HttpRunner/HttpRunner#560]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 1.5.11]

## 堆栈信息

请提供出现 bug 时的详细堆栈内容。

## 项目文件结构

请提供测试用例的文件组织结构。比较好的方式是在项目根目录中执行`tree -a`命令。

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

**Comment by ckl0804** [comment]
有一个登录接口，在传完用户名和密码之后，原本是希望直接能够获取到token，但是由于页面返回302，被重定向到新的页面中去了，所以无法获取到这个token。在HTTPRUNNER里需要怎么处理呢？有些资料是说再发起一个请求？

**Comment by 406722575** [comment]
@ckl0804 在登录之前获取token

**Comment by wangwkcn** [comment]
在teardown_hooks中从response.request中提取到header中的Cookie，设置到response中，再通过extract从response中提取出来
```
"extract": [
	{"yunWebd_cookie": "Cookie"}
],
"teardown_hooks": [
	"${teardown_hooks_extract_cookie($response, $request)}"
],
```
debugtalk.py
```
def teardown_hooks_extract_cookie(response, request):
    response.Cookie = response.request.headers["Cookie"]
```

**Comment by debugtalk** [comment]
@ckl0804 对于 302 跳转的情况，通过 response.history 可以拿到中间过程。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jaychang1989** [comment]
> @ckl0804 对于 302 跳转的情况，通过 response.history 可以拿到中间过程。
> 
> Sent with [GitHawk](http://githawk.com)

response.history  有具体的使用方法示例么？

比如302 重定向之前status_code = 302 ，重定向之后 status_code = 200，我应该怎么使用response.history 获取重定向之前的status_code
