### ISSUE TITLE
参数化时，如何根据不同的参数，校验不同的结果

### ISSUE THREAD

**Issue by chazhongbao** [HttpRunner/HttpRunner#566]
比如用户名和密码进行组合登录时，如果输入不同信息，给出的提示语是不同的，怎么去校验它们

**Comment by debugtalk** [comment]
在参数化文件中，将你的校验参数和账号密码参数进行关联。

例如：

```csv
UserName, Password, Msg
test1,111111,success
test1,22222,failed
```

然后在测试用例中，对 UserName, Password, Msg 进行引用即可。
