### ISSUE TITLE
能否实现Charles中的Rewrite功能

### ISSUE THREAD

**Issue by 406722575** [httprunner/httprunner#567]
## 问题描述
Charles的Rewrite功能非常强大，可以重写接口所有元素的内容，例如：header、host、url、path、query param、response status、body。
例如，response返回内容是{'code': '3', 'msg'},想把code改成0，即{'code': '0'}
或者现有功能是否可以实现

**Comment by chenhengjie123** [comment]
charles 是一个 proxy ，相当于是一个中间人。因此具备在两个系统间传输时重写返回值的能力。

httprunner 是一个接口测试工具，相当于模拟了双系统间传输的其中一个系统。而接收的 response 仅为自己所用，因此不具备、也不需要具备您文中提到的能力。

若您是想寻找支持通过编程语言设定 rewrite 规则的工具，可以看看 anyproxy 。
