### ISSUE TITLE
求助！！！有快速的方法可以将testcase中extract提取的变量弄成全局变量吗(所有testcase都可以调用)

### ISSUE THREAD

**Issue by wangtesting** [HttpRunner/HttpRunner#568]
## 问题描述
因为不是可以testcase调用testcase么
为了避免重复调用，我有三个testcase，
第一个:准备前期数据(比如3个接口)
第二个:实现目标的小场景(又比如3个)
第三个:数据结束工作(又比如3个)

现象：第一个extract提取出多个变量在第二个、第三个的testtest中用到
(extract提取的变量只能在同一个testcase中共享，其他testcase调用找不到)
很急，拜托各位大佬了！
有人说要放在debugtalk里面，但是怎么放啊，写了个带参函数直接返回，但是其他testcase中涉及到的api还是拿不到这个提取变量

## 版本信息
请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]

- ``

- 

-

**Comment by fakegeeker** [comment]
@wangtesting 请问你解决了吗？

**Comment by wangtesting** [comment]
放在env环境变量里，或者将数据存在一个文件里再函数读出来
现在遇到一个问题，我提取出的变量，经函数处理后的结果想赋值给一个变量，后面别的再去调用它就找不到




| |
19924586610
|
|
邮箱19924586610@163.com
|

签名由 网易邮箱大师 定制

在2019年05月10日 10:58，liuxiao 写道：

@wangtesting 请问你解决了吗？

**Comment by debugtalk** [comment]
测试用例之间应该保持独立，不应该有参数依赖。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wangtesting** [comment]
额，不是为了避免重复描述，所以在这种场景下可以将testcase作为一个teststep描述，但这样自然就有依赖关系，如果无此需求的话自然就不必要。额，现在感觉没法直接进行设置全局变量（最高层的）
2 还有将extract提取的值经过debugtalk处理后得到的值，作为一个参数再传给debugtalk的另一个函数，在别的地方看到作者说暂不支持函数套函数，不知道现在有好的方式来解决了吗

在 2019-07-14 00:39:16，"debugtalk" <notifications@github.com> 写道：


测试用例之间应该保持独立，不应该有参数依赖。

Sent with GitHawk
