### ISSUE TITLE
这个校验contained_by目前是不是不支持了，经过验证，不生效

### ISSUE THREAD

**Issue by chazhongbao** [httprunner/httprunner#570]
## Versions

Please complete the following information:

 - OS: [e.g. macos, Linux, Windows]
 - Python [e.g. 3.6]
 - HttpRunner [e.g. 1.5.11]

## Traceback

Traceback when bug occurs.

## Project structure

File structure of your project. A good way is to run `tree -a` command.

## Project files (If possible)

Provide your project files to help locate and debug bugs faster. This is not mandatory.

NOTICE: Before uploading your project files, don't forget to remove sensitive data, e.g. IP, username and password, key info etc.

**Comment by bruceqiao** [comment]
debugtalk.py 里写个方法实现一下？😃
