### ISSUE TITLE
请问2.0是不是不支持直接引用debugtalk.py中的变量了？

### ISSUE THREAD

**Issue by erolce** [HttpRunner/HttpRunner#571]
之前的版本：
debugtalk.py中：
![image](https://user-images.githubusercontent.com/21331818/56561067-b5443c00-65d8-11e9-9aa6-89329667b46c.png)
api中：
![image](https://user-images.githubusercontent.com/21331818/56561088-c2612b00-65d8-11e9-8635-00159d207925.png)
是可以正常使用的，但升级2.0以后就不可以用了，是不是取消了这种用法？

**Comment by debugtalk** [comment]
@erolce 是的，不再支持引用 debugtalk.py 中的变量，只支持引用函数了。

如果你确实需要在 debugtalk.py 中定义变量并引用的话，那可以写个函数来获取，再引用函数。

```python
var_a = 123

def get_var_a():
    return var_a
```

调整的目的是希望能减少选择，否则按照之前的方式，在看到脚本中引用变量时，还需要分别去查看是在哪里定义的。
