### ISSUE TITLE
loader.py中的Line290处tests_def_mapping的 testcases在整个程序运行过程中一直为空

### ISSUE THREAD

**Issue by ArraysZhu** [HttpRunner/HttpRunner#572]
## 问题描述
个人看源码后感觉loader.py中的Line290处tests_def_mapping字典的testcases值在整个程序运行过程中一直为空，是不是Line336处修改为
`tests_def_mapping['testcases'][testcase_path] = testcase_dict`
会更好一点，仅为个人建议，才疏学浅可能看错了。
## 版本信息

请提供如下版本信息：
 - Python 3.7.2
 - HttpRunner 2.1.1

**Comment by debugtalk** [comment]
@ArraysZhu 感谢反馈，已修复。
