### ISSUE TITLE
parser.py Line1078处不应该有第二个形参function

### ISSUE THREAD

**Issue by ArraysZhu** [HttpRunner/HttpRunner#578]
## 问题描述

阅读源码感觉parser.py Line1078处不应该有第二个形参function，这样的话只要存在function变量找不到的错误就会被忽略

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本 3.7
 - HttpRunner 版本2.1.1

**Comment by debugtalk** [comment]
@ArraysZhu 感谢反馈，已经修复了。
