### ISSUE TITLE
validate中直接调用debugtalk.py函数格式无法解析

### ISSUE THREAD

**Issue by timeliuhuan** [HttpRunner/HttpRunner#583]
## Describe the bug

testcases中接口的断言值采用简写格式
<img width="605" alt="image" src="https://user-images.githubusercontent.com/44793132/56859593-d84b6300-69bf-11e9-9728-6cf54629c394.png">
会报错，报错如图：
<img width="567" alt="image" src="https://user-images.githubusercontent.com/44793132/56859616-1d6f9500-69c0-11e9-87cc-96f45fb2192f.png">
换下以下写法就正常
<img width="483" alt="image" src="https://user-images.githubusercontent.com/44793132/56859627-3b3cfa00-69c0-11e9-8ffe-073ec2c54406.png">

python版本：3.7
httprunner版本：2.1.2

**Comment by idibmzjm** [comment]
第二个加引号
"${XXXXX}"

**Comment by timeliuhuan** [comment]
谢谢，试了下确实可以
