### ISSUE TITLE
celery flower报错"No module named 'flower'"

### ISSUE THREAD

**Issue by caohairong** [HttpRunner/HttpRunner#584]
## 问题描述

在执行celery flower是出现错误

![image](https://user-images.githubusercontent.com/11405908/57057120-5f0e8180-6cd9-11e9-8017-291edd97f611.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Windows7]
 - Python 版本 3.6]
 - HttpRunner 版本 [1.5.8]

**Comment by debugtalk** [comment]
这是 HttpRunnerManager 的内容，该项目已停止维护。
