### ISSUE TITLE
使用httprunner执行用例报错，提示initialize HttpRunner

### ISSUE THREAD

**Issue by liao132512** [HttpRunner/HttpRunner#586]
请对遇到的 bug 进行简要描述。

 - 操作系统类型: [Windows7]
 - Python 版本 [3.6]
 - HttpRunner 版本 [ 2.1.2]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。
D:\test\apprun\testsuites>hrun testsuites/3rd.yml
ERROR    !!!!!!!!!! exception stage: initialize HttpRunner() !!!!!!!!!!
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\hrun.exe\__main__.py", line 9, in <module>
  File "d:\python\lib\site-packages\httprunner\cli.py", line 83, in main_hrun
    runner.run(path, dot_env_path=args.dot_env_path)
  File "d:\python\lib\site-packages\httprunner\api.py", line 268, in run
    raise exceptions.ParamsError("Invalid testcase path or testcases: {}".format
(path_or_tests))
httprunner.exceptions.ParamsError: Invalid testcase path or testcases: testsuite
s/3rd.yml

**Comment by liao132512** [comment]
重新安装Python+pip+httprunner环境后，仍然提示
![image](https://user-images.githubusercontent.com/50285540/57194324-1b857300-6f78-11e9-86fc-77de7144bbd5.png)
之前提示的.py文件行数报错暂时没有了。但是有提示testcases path 非法。

**Comment by liao132512** [comment]
同样的文件 mac OS运行成功，window7运行失败

**Comment by stephenlee622** [comment]
路径写法不同导致的吧  linux /  ，windows \\      
你试一下 hrun testsuites\\3rd.yml
