### ISSUE TITLE
新版httprunner如何运行测试用例后自动发邮件

### ISSUE THREAD

**Issue by timeliuhuan** [HttpRunner/HttpRunner#588]
## Describe the bug

想在每次运行测试用例后能自动发送邮件，将测试结果或者测试报告附上，看了最新的使用文档并没有对发送邮件这一块有说明，之前1.5老版本是自己写了一个mail.py（包含邮件服务器，邮箱等信息）放到httprunner的包下面，然后在report.py中调用该模块，但总觉得还是不好维护2.0以上的httprunner有没有更好的方式呢

## Versions

Please complete the following information:

 - OS: [macos]
 - Python [3.7]
 - HttpRunner [2.1.2]

**Comment by debugtalk** [comment]
HttpRunner 本身没有集成发送邮件的功能。
有考虑增强 pipeline 机制，测试运行完后执行别的操作。但更多的还是通用机制上，具体的邮件发送还是得自己实现。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
