### ISSUE TITLE
命令窗口运行hrun E:\testssq.yaml，报错

### ISSUE THREAD

**Issue by Kary0228** [HttpRunner/HttpRunner#589]
运行，hrun E:\testssq.yaml

报错：

ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
RecursionError: maximum recursion depth exceeded while calling a Python object
递归错误:调用Python对象时超过最大递归深度

运行的时候，报错，不能自动生成测试报告，如何解决？

**Comment by debugtalk** [comment]
报错提示加载用例阶段出现的问题，检查下测试用例格式吧。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
