### ISSUE TITLE
您好，我是一个httprunner得初学者我有几个问题如下testsuite里 config和 testcases前面需要 “-”吗

### ISSUE THREAD

**Issue by petersmile** [HttpRunner/HttpRunner#590]
![image](https://user-images.githubusercontent.com/45752791/57365291-59bca580-71b7-11e9-9ffa-c29920e12dec.png)

这样就不报错，但是执行这个testsuite时并没有执行测试用例时为什么呢
![image](https://user-images.githubusercontent.com/45752791/57365170-29750700-71b7-11e9-99c1-d5eabb61c1e7.png)

**Comment by debugtalk** [comment]
你格式写错了。
你可以升级到最新版，用脚手架功能新建一个项目，里面包含了模板格式。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
