### ISSUE TITLE
如果需要传的参数是HTML或者XML、TXT,在JSON文件中需要如何写的

### ISSUE THREAD

**Issue by ckl0804** [HttpRunner/HttpRunner#591]
```json
"test": {
    "request": {
        "headers": {
            "authorization": "bearer 6973e0b5-8401-42a5-88e2-9448e3cb6672"
        },
        "method": "POST",
        "json": {
            "password": "YWRtaW4",
            "username": "admin"
        },#这里如果是HTML/XML/TxT，需要如何写
        "url": "/oauth/login?5555=777777&77733=76777"
    },
    "extract": [],
    "validate": [{
        "eq": ["content.res", "2"]
    }],
    "name": "true-login"
}
```

**Comment by debugtalk** [comment]
@ckl0804 

```json
"test": {
    "request": {
        "headers": {
            "authorization": "bearer 6973e0b5-8401-42a5-88e2-9448e3cb6672"
        },
        "method": "POST",
        "data": "在这里传入数值",
        "url": "/oauth/login?5555=777777&77733=76777"
    },
    "extract": [],
    "validate": [{
        "eq": ["content.res", "2"]
    }],
    "name": "true-login"
}
```

具体的用法可以参考 requests 框架。

**Comment by lenmohanxing** [comment]
debugtalk:
def read_xml(file_path): #读取xml文件内容
    r = open(file=file_path,encoding="utf-8").read()
    r.encode(encoding="utf-8")
    return r

用例：
- config:
    name: xml请求
    variables:
      headers:
        {
          "Accept": "application/json",
          "Content-Type":"text/xml"
        }
    request:
    base_url:

- test:
    name: 读取文件内容放进body请求
    variables:
        #文件绝对路径
        - file_path:  c:\test.txt
    request:
        url: /recvmsg/rt
        method: POST
        headers: $headers
        data: ${read_xml($file_path)}

**Comment by lenmohanxing** [comment]
版本：2.4.1
函数：
def read_xml(file_path): #读取xml文件内容
    r = open(file=file_path,encoding="utf-8").read().encode(encoding="utf-8")
    return r
用例：
- test:
    name: 读取文件内容放进body请求
    variables:
        #文件绝对路径
        - file_path: C:\body\629.xml
    request:
        url: /test/rt
        method: POST
        headers: $headers
        data: ${read_xml($file_path)}
