### ISSUE TITLE
怎么能加入httprunner，成为一名contributor

### ISSUE THREAD

**Issue by idibmzjm** [HttpRunner/HttpRunner#595]
本人也在使用httprunner，在使用的过程中发现了一些问题，以及可以优化的地方，但现在都是在本地改动，看在issue上到有一些同学反馈的问题跟我遇到的差不多，我觉得可以处理一些问题，加入contributor

**Comment by debugtalk** [comment]
@idibmzjm 非常欢迎哈。

加入很简单，对于存在的问题，直接提交 PR 就可以了。
