### ISSUE TITLE
导入httprunner包，启动flask报错

### ISSUE THREAD

**Issue by stephenlee622** [HttpRunner/HttpRunner#596]
## 问题描述
基于flask下的项目里导入httprunner包后，启动flask报错。
如果不导入httprunner包就不报错，正常运行。
而且我看报错的信息，在flask包的app.py 的 
cli.show_server_banner(self.env, self.debug, self.name, False) 
注释掉的话也不会报错，两者版本兼容问题导致的

## 版本信息

 - 操作系统类型: Windows
 - Python 版本  3.7
 - HttpRunner  2.1.2
 - Flask  1.0.2
 - Flask-RESTful   0.3.7    

![image](https://user-images.githubusercontent.com/38908432/57761398-02c34d00-7730-11e9-8522-b0befc173501.png)

![Uploading image.png…]()

**Comment by stephenlee622** [comment]
![微信图片_20190515164256](https://user-images.githubusercontent.com/38908432/57761692-97c64600-7730-11e9-941c-4f2b9e80c2e8.png)

**Comment by debugtalk** [comment]
@stephenlee622 HttpRunner 对于你只是一个依赖包，你可以在 Python 脚本中导入进行试验，跟 flask 没关系。
