### ISSUE TITLE
debugtalk获取不到.env环境变量

### ISSUE THREAD

**Issue by xuxunxiong** [HttpRunner/HttpRunner#599]
## 问题描述

debugtalk获取不到.env环境变量

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.1.2]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
![image](https://user-images.githubusercontent.com/35294433/57919585-ab59e400-78cb-11e9-9fc7-bda05a29e679.png)
![image](https://user-images.githubusercontent.com/35294433/57919601-b280f200-78cb-11e9-86f1-6a9d8d829e3b.png)

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

C:\Users\ThinkPad\AppData\Local\Programs\Python\Python37\python.exe C:/Users/ThinkPad/PycharmProjects/HttpRunner/casetests/debugtalk.py
None

Process finished with exit code 0

**Comment by idibmzjm** [comment]
在debug.py中去定义一个方法取出来，
def getUserName():
  return os.environ.get("UserName")
取的时候用辅助方法获取
或者参照

**Comment by xuxunxiong** [comment]
> 在debug.py中去定义一个方法取出来，
> def getUserName():
> return os.environ.get("UserName")
> 取的时候用辅助方法获取
> 或者参照

不行呀，我的密钥放在.env里，想在debugtalk.py进行引用。不知怎么实现呢

**Comment by idibmzjm** [comment]
> > 在debug.py中去定义一个方法取出来，
> > def getUserName():
> > return os.environ.get("UserName")
> > 取的时候用辅助方法获取
> > 或者参照
> 
> 不行呀，我的密钥放在.env里，想在debugtalk.py进行引用。不知怎么实现呢

按照上面操作不行？
就是定义辅助方法取出来，然后在用例中引用辅助方法就可以了
或者
修改源文件：httprunner/parser.py
 835行：override_variables = utils.deepcopy_dict(project_mapping.get("env", {}))

**Comment by weirdohaibo** [comment]
os.environ["env"]  这种方式试一下

**Comment by grily** [comment]
我也遇到了从.env文件读取变量 读不出来的问题
![image](https://user-images.githubusercontent.com/19886445/61443567-4a857100-a939-11e9-8584-0bacaa6d2f0c.png)
调试的时候；发现 USERNAME已经在系统的环境变量里面了；（不知道什么时候加进去的）
![image](https://user-images.githubusercontent.com/19886445/61443768-ae0f9e80-a939-11e9-8033-cc083e251d86.png)
但是写在.env里面的变量就是取不出来
![image](https://user-images.githubusercontent.com/19886445/61443968-06df3700-a93a-11e9-81ea-89070059eeb4.png)
好困惑啊，有没有遇到过这个问题呢
