### ISSUE TITLE
多个case之间，session能传递吗

### ISSUE THREAD

**Issue by chenfei5201213** [HttpRunner/HttpRunner#60]
场景：每个接口必须登录才能访问，并且下一次访问要根据上次请求头header里某个字段，动态计算cookie和token。
现在动态计算cookie和token已经通过自定义函数实现了，无法基于登录后的session继续发起后续case的请求

**Comment by debugtalk** [comment]
@chenfei5201213 在同一个`JSON/YAML`文件里面，所有的testcase都是共用的一个`requests.Session`，所以session是能共用的。
但需要注意的是，如果你将登录部分放置到了`debugtalk.py`中，那么就相当于同时初始化了两个`requests.Session`，就没法共享session了。

**Comment by chenfei5201213** [comment]
@debugtalk  多谢，之前是由于header有个字段计算有误导致302了  这个问题可以关了
