### ISSUE TITLE
testcase config 实现公共 header

### ISSUE THREAD

**Issue by 406722575** [httprunner/httprunner#600]
## 问题描述

全局headers中加上Referer没有生效，需要每一个test中都要加上Referer才生效

![image](https://user-images.githubusercontent.com/39303693/57963763-1652fb80-795c-11e9-9c57-69019d84094c.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]

**Comment by debugtalk** [comment]
当前 testcase config 中不支持配置公共 header，这个特性后面再考虑加上。

**Comment by yuanJH88** [comment]
> 当前 testcase config 中不支持配置公共 header，这个特性后面再考虑加上。

如果现在需要配置公共Header的话有什么取巧的方法吗？

**Comment by debugtalk** [comment]
将公共 header 写在 debugtalk.py 中，封装在函数里。在所有需要该 header 的地方引用该函数。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by havenqi** [comment]
文档中的范例看起来貌似可以把headers的公共部分放在config里，可实际使用确实发现请求消息的headers里其实并未包含那些config里的。此处还未实现。

**Comment by debugtalk** [comment]
在 golang 版本中已实现该功能，在 pytest 版本中还需要同步支持下
