### ISSUE TITLE
httprunner如何使用mysql断言接口返回值

### ISSUE THREAD

**Issue by Yang369** [HttpRunner/HttpRunner#602]
python3.7的 httprunner是2.1.2的版本。
现在碰到一个问题，有一个下单接口需要断言返回值里对应的订单状态是否和数据库里的内容一致，谁做过类似的吗

**Comment by idibmzjm** [comment]
用辅助方法，查数据库，然后跟接口返回的值对比

**Comment by ouyangxueping** [comment]
用辅助方法，查数据库，然后跟接口返回的值对比，这个方式谁实现了嘛
