### ISSUE TITLE
extract执行发生在validate 之前是否合理？

### ISSUE THREAD

**Issue by diablowu** [HttpRunner/HttpRunner#604]
## 问题描述

extract执行发生在validate 之前是否合理？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Any
 - Python 版本 3.6
 - HttpRunner 版本 2.1.2

## 项目文件内容（非必须）

https://github.com/HttpRunner/HttpRunner/blob/v2.1.2/httprunner/runner.py#L264

按照实际的api开发的思路，一般都要先验证响应的合法性（validate）再去获取实际数据（extract），目前validate是发生在extract之前，也就是会造成提前提取到一些不合法的路径，

>Failed to extract! => a.b.c

是不是可以调整一下顺序？

**Comment by idibmzjm** [comment]
手动改，重新打包自己用

**Comment by debugtalk** [comment]
>## 问题描述 ...

@diablowu 这么设计的原因在于，很多时候需要将提取出的字段用于检验，因此 extract 必须在 validate 之前。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
