### ISSUE TITLE
对于httprunner2.0版本中CSV数据驱动的疑问

### ISSUE THREAD

**Issue by huiCSDN** [HttpRunner/HttpRunner#605]
你好，请问一下现在httprunenr2.0版本中对于CSV数据驱动是如何使用的呢，我根据文档教程进行操作，在api中维护了一个接口信息，在testcase中引用这个api接口，然后在testsuite中对这个用例进行CSV参数化设置，最后运行这个testcases时，会提示我引用的这个CSV中的参数不存在，在哪里能有可运行的示例进行参考呢

**Comment by weirdohaibo** [comment]
贴个你现在的代码图,我帮你看看

**Comment by huiCSDN** [comment]
> 贴个你现在的代码图,我帮你看看

谢谢，已经解决了，如果想向1.5版本那样，将公共的header放到config中，下面的test就不需要每个都写header了，在2.0版本中的config是怎么填写格式

**Comment by weirdohaibo** [comment]
作者文档里好像是有写的你去找找看


许海波
