### ISSUE TITLE
断言异常，用例里面第一个test有断言，第二个test没有断言，报告里面显示test都有断言了，

### ISSUE THREAD

**Issue by chenhuazhong** [HttpRunner/HttpRunner#606]
下面这个图片中detail是test2的详情，json文件中test2中是没有断言的，报告中detail显示断言失败，但是总览中显示测试是：success
![image](https://user-images.githubusercontent.com/37465292/58390278-06759e80-8063-11e9-9858-7982c021091d.png)
下面是.json用例文件
https://pan.baidu.com/s/1RAy99RWqGIPEpyeogQPVug 
提取码：cdji

**Comment by chenhuazhong** [comment]
test1有断言，test2没有断言，测试报告中显示test2也带上断言了，带上的是test1的断言，这应该是个bug

**Comment by debugtalk** [comment]
这个 bug 有修复过，确定升级到最新版后再试下。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
