### ISSUE TITLE
复杂用例的组织和数据规则的维护

### ISSUE THREAD

**Issue by Helen-Shen** [HttpRunner/HttpRunner#61]
1、业务场景中有这样的情况：有多个接口在涉及逻辑验证的时候会调用顺序不同。（例如我需要A-B-C-D、A-C-B-D、A-D-B-C等等多种顺序执行接口）如何组织这些接口才能减少代码的冗余和后续维护的成本呢?
2、由于业务中接口传入的数据很多，并不想在数据的维护上下大功夫，因为input一旦变动，我的expect也需要人工去检查和维护，所有现在的想法时想要维护的不是数据的本身，而是数据的一个规则，例如有一个test的字段，只要维护他在输入规范：5-10位的数字。那么我的测试数据时可以任意生成的，在数据符合规范的时候，那么我的期待值就是true或者时继续执行下一个接口，如果不符合规范的时候就会false，断言终短。想问一下，现在httprunner是否提供了这样的解决办法？
关于第二点，因为现在是支持变量传参的，那么我的期待值是否可以动态的通过方法去获取呢？如果可以的话，那么我调用一个校验参数的方法去动态的生成我的预期结果是否可行?当然这边还有点疑虑是规范的维护会不会需要大量的代码实现，能否简单的配置生成，在这方面想问下有什么好的建议和解决办法。

**Comment by debugtalk** [comment]
@Helen-Shen 
针对问题1，当前是已经支持了的，具体的使用方法我这两天会发文档出来，到时候更新博客后我再跟你说下；
针对问题2，你的这个需求与 #29 #52 类似，我近几天会实现下。

**Comment by Helen-Shen** [comment]
@debugtalk 嗯嗯，谢谢。

**Comment by Helen-Shen** [comment]
@debugtalk 
还想问一下，validate的期待值也参数化了，那么这个期待值值是针对我一个excel文件或者是csv文件读取到的呢，还是是和入参一样是支持一个自己写的方法计算出来的一个变量？（接口入参也是，支持从文本中读取么?）如果是需要计算出期待值的话，那么必然是要将当前接口传的那一套参数作为一个入参传到计算期待值的方法中再进行计算的，那接口参数变量有方法可以获取到传出来么？
如果选择不用excel而是内部方法计算来进行期待值的获取来比对结果，那么在项目的组织架构上有什么好的建议么？？对于维护参数的规则，采用什么形式维护比较好呢?现在的想法是采用配置文件的形式？另外，对于接口参数的数据的正确性可以用以上的形式去组织测试，但是我没有办法保证数据的有效性，但是往往要求测试这两个方面的，在组织上有什么建议么？？

**Comment by debugtalk** [comment]
@Helen-Shen [《HttpRunner 的测试用例分层机制》](http://debugtalk.com/post/HttpRunner-testcase-layer/)
