### ISSUE TITLE
如何对数组中的每一个元素做断言

### ISSUE THREAD

**Issue by lichengxun** [HttpRunner/HttpRunner#613]
对数组中的第一个元素做如下断言  
`- { "check": "content.data.0.id", "comparator": "len_gt", "expect": 0 }`
那么如果想对数组中的每一个元素统一断言，而不是一个个枚举应该如何做呢？

**Comment by lichengxun** [comment]
需要通过自定义结果校验器来处理吗

**Comment by debugtalk** [comment]
@lichengxun 是的，将整个数组传入自定义校验器，写函数实现校验。

**Comment by xhuihui** [comment]
> @lichengxun是的，将整个附上自定义校正器，写函数实现校正。

这里在报告上展现形式方便查看，例如 list 有100个数据， 其中一个断言异常。那么就会导致用例失败，报告中只有数组。不会展示具体哪个异常。
