### ISSUE TITLE
开发扩展时，设置log_file，发现日志中出现乱码

### ISSUE THREAD

**Issue by zhu-xiao-li** [httprunner/httprunner#616]
## 问题描述

我使用httprunner进行开发扩展，运行之后，查看log.txt，发现内容显示乱码，如下：
![image](https://user-images.githubusercontent.com/51776407/59409926-078c2700-8dea-11e9-90b0-77b072accaf0.png)

## 版本信息

请提供如下版本信息：

 - 操作系统类型：Windows
 - Python 版本：3.7
 - HttpRunner 版本：2.1.2

## 项目文件内容（非必须）

简单的代码如下：
**demo.py**
from httprunner.api import HttpRunner
runner = HttpRunner(log_level='DEBUG', log_file='./log.txt')
runner.run('./microPay.yaml')`

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ python demo.py
```

**Comment by debugtalk** [comment]
@zhu-xiao-li 这是因为在日志中添加了颜色标记，在终端中显示会有颜色，但在日志文件中就会有这些字符。
