### ISSUE TITLE
AssertionError: Failed to extract!（extract支持2级吗，三层结构就会报错）

### ISSUE THREAD

**Issue by huaxiaodao** [HttpRunner/HttpRunner#618]
## 问题描述

        extract:
            clueId: content.data.xxx.yyy   这样的结构是报错的？content.data.xxx是OK的。
           response里面返回的是列表，有多个yyy字段，这个需要怎么区别开来，只需要其中一个。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ macos]
 - Python 版本 [3.7.3]
 - HttpRunner 版本 [2.1.2]

请提供在命令行中运行测试时所在的目录和命令
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httprunner/api.py", line 56, in test
    self.fail(str(ex))
AssertionError: Failed to extract! => data.xxx.yyy

**Comment by debugtalk** [comment]
如果 content.data.xxx 是列表，那么再指定其中的元素时，需要用 index。
content.data.xxx.0，content.data.xxx.1

**Comment by lkx007** [comment]
@debugtalk 

不能使用一个自定义的方法进行过滤么？
类似于paramters里面调用自定义方法，写法大致如下：

        extract:
            clueId: ${filter_data(content.data, "yyy"}


然后filter_data是一个可以自定义的函数

**Comment by debugtalk** [comment]
@lkx007 你可以尝试下 teardown_hooks
