### ISSUE TITLE
关于报告里面response_time和elapsed时间为什么差别那么大

### ISSUE THREAD

**Issue by Pig-Hot** [HttpRunner/HttpRunner#619]
一次接口请求结果
response_time显示 3600ms+
elapsed显示500ms+

**Comment by debugtalk** [comment]
@Pig-Hot elapsed 是根据 response.elapsed 统计得到的。response_time 是使用发起请求前后的时间戳差值得到的。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
