### ISSUE TITLE
testcase中调用api中接口无法复写hearder内容

### ISSUE THREAD

**Issue by timeliuhuan** [HttpRunner/HttpRunner#622]
## 问题描述

在testcase中调用api接口时，需要复写api中header里面的某个参数，按照以下两种方式编写运行的时候接口的header参数还是调用的api接口中的header参数
<img width="537" alt="image" src="https://user-images.githubusercontent.com/44793132/59756837-1462bc00-92bd-11e9-9508-b28a73a38d1b.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/44793132/59756926-47a54b00-92bd-11e9-913a-353a8bfe9119.png">

## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.7
 - HttpRunner 版本  2.1.2

**Comment by timeliuhuan** [comment]
知道原因了，是因为testcase中teststep定义的变量并不能覆盖config中同名的变量所致，目前不知道框架是本来就是这样设计的还是有bug

**Comment by debugtalk** [comment]
@timeliuhuan 引用 api 时，不支持 headers 的覆盖。通过传参的方式同样能满足你的需求。
