### ISSUE TITLE
是否支持dubbo类型接口

### ISSUE THREAD

**Issue by mosquitolww** [HttpRunner/HttpRunner#627]
如何支持dubbo类型接口

**Comment by debugtalk** [comment]
不知道，当前只支持 HTTP(S)，近期的计划是会支持 thrift 和 Web Socket，dubbo 暂时没计划。

**Comment by debugtalk** [comment]
HttpRunner v4.0 发布了，新增支持了多协议扩展，不再局限于 HTTP 协议了。
https://httprunner.com/blog/release-v4/

dubbo 协议后续会安排上~
