### ISSUE TITLE
请问 httprunner可以批量执行用例吗

### ISSUE THREAD

**Issue by zwlloveyanyan** [HttpRunner/HttpRunner#63]
请问 httprunner可以批量执行用例吗，用例数量太多了，除非把执行每一个的用例名字写到脚本。但是内容也好多

**Comment by debugtalk** [comment]
@zwlloveyanyan 看[文档](http://httprunner.readthedocs.io/en/latest/run-testcases.html)。

If you want to run testsets of a whole project, you can achieve this goal by specifying the project folder path.

```bash
$ httprunner testcases_folder_path
```
