### ISSUE TITLE
在api的yml文件里面填入了参数，最后运行时发现没有带参数，想知道api目录下面的yml文件的参数读入是从哪个地方读入的，好进一步定位问题

### ISSUE THREAD

**Issue by sanderchen** [HttpRunner/HttpRunner#631]
在api的yml文件里面填入了参数，最后运行时发现没有带参数，想知道api目录下面的yml文件的参数读入是从哪个地方读入的，好进一步定位问题

**Comment by debugtalk** [comment]
@sanderchen 运行脚本时可以增加个 `--save-tests` 参数，在 loaded.json 和 parsed.json 中可以看下参数情况。
