### ISSUE TITLE
debutalk.py自定义函数自定义完后，无法立即调用？

### ISSUE THREAD

**Issue by kangliangtang** [HttpRunner/HttpRunner#633]
## Describe the bug

自定义函数定义完，无法立即调用，需要等待半个小时后才可以调用？
是否与热加载机制设置有关？？

## Versions

Please complete the following information:

 - OS: [e.g.  Linux]
 - Python [e.g. 3.5]
 - HttpRunner [e.g. 2.0.2]

**Comment by kangliangtang** [comment]
![11](https://user-images.githubusercontent.com/35226217/60265512-8029d200-9918-11e9-9965-b00c6a072ed9.jpg)

**Comment by debugtalk** [comment]
在 loader 阶段就会加载所有 functions，与热加载机制无关。
