### ISSUE TITLE
报告DURATION计算错误

### ISSUE THREAD

**Issue by ptzff** [httprunner/httprunner#637]
## 问题描述

报告的持续时间计算错误

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7.1]
 - HttpRunner 版本 [2.2.2]
报告显示1332.945 seconds，实际只有182.1689

**Comment by ptzff** [comment]
[1562119155.zip](https://github.com/HttpRunner/HttpRunner/files/3353022/1562119155.zip)

**Comment by debugtalk** [comment]
duplicate with #707
