### ISSUE TITLE
- test 中获取不到 - config 中的配置值

### ISSUE THREAD

**Issue by ohmydengzi** [HttpRunner/HttpRunner#64]
HttpRunner version: 0.8.5
window 7
python3.6

test 中有空的headers，config 中headers有值，但请求中kwargs 却没有这个值。图1
当 test 中的headers不为空时，就能正常。图2
图1
![image](https://user-images.githubusercontent.com/13642149/33972339-5ca7a16e-e0b8-11e7-893e-0499c345180e.png)
图2
![image](https://user-images.githubusercontent.com/13642149/33972531-35be6136-e0b9-11e7-9c62-aa646b9bd7c9.png)

**Comment by debugtalk** [comment]
@ohmydengzi 问题在于，你在test中指定了headers，虽然没有赋值，但相当于赋值为None，这就会覆盖config中的headers。你要是想继承config中的headers，正确的做法应该是在test中不指定headers。
