### ISSUE TITLE
你好，https://cn.httprunner.org/quickstart/ 这个上面的操作文档上的链接很多都失效了，麻烦更新一下，谢谢

### ISSUE THREAD

**Issue by evanliuyufeng** [HttpRunner/HttpRunner#640]
你好，https://cn.httprunner.org/quickstart/ 这个上面的操作文档上的链接很多都失效了，麻烦更新一下，谢谢
![image](https://user-images.githubusercontent.com/21999482/60725239-25712580-9f6b-11e9-836e-3f36ba6c40a0.png)

**Comment by debugtalk** [comment]
感谢反馈。
https://cn.httprunner.org/prepare/parameters/
