### ISSUE TITLE
extract提取的值用在下个请求json中使用变量会报错

### ISSUE THREAD

**Issue by 406722575** [httprunner/httprunner#648]
![image](https://user-images.githubusercontent.com/39303693/61265070-7251c900-a7c1-11e9-948c-3ba91cf5247e.png)

json提交的值是一段文字，想要把上一个extract提取的值，把其中的内容当作变量，如果是用函数是可以改变值，但是能不能直接把extract提取的值用作变量
报错：
![image](https://user-images.githubusercontent.com/39303693/61264949-e2138400-a7c0-11e9-8e6c-01025e63aef9.png)

**Comment by chenhengjie123** [comment]
这个是由于目前无法正确识别变量名在何处结束造成的。后续会增强对于参数的识别能力。

建议先通过把前一段文字和后一段文字，均保存到变量中，然后采用类似 $a$b$c 的方式拼接变量。

**Comment by wangtesting** [comment]
> 这个是由于目前无法正确识别变量名在何处结束造成的。后续会增强对于参数的识别能力。
> 
> 建议先通过把前一段文字和后一段文字，均保存到变量中，然后采用类似 $a$b$c 的方式拼接变量。

有个想法，extract提取的一个值，经过debugtalk处理后返回的新值，怎么存为一个全局变量啊。。因为想把它作为一个入参传给其他函数。但是debugtalk里面不是现在不支持函数调用函数吗

**Comment by debugtalk** [comment]
@wangtesting 这种情况在最新版本中应该已经不存在了。
