### ISSUE TITLE
validate 自定义函数支持多参数

### ISSUE THREAD

**Issue by rihkddd** [HttpRunner/HttpRunner#65]
validate终于支持自定义函数了~
然而发现只能传入两个参数，一个是校验字段，一个是期望值。
但是有时候业务逻辑比较复杂，需要从返回值中抽取多个字段，再经过自定义函数判断是否符合断言。
比如，返回值中有start_time，end_time，断言是判断中间的时间差是否小于指定值。
目前想到的办法就是正则匹配的时候把需要的参数都匹配进去，在自定义函数中实现字段抽取&断言。
这种方式不是很优雅。

**Comment by debugtalk** [comment]
@rihkddd 自定义校验函数的确是只能传入两个参数，但是通过灵活应用，同样能实现各种复杂的检测。
就拿你列举的案例来说，你希望检查返回值中的start_time和end_time差值是否小于指定值，那么你在编写自定义校验函数的时候，就可以在第一个参数中传入完整的返回值，第二个参数传入指定值。
然后在自定义校验函数中，先从完整的返回值中解析出start_time和end_time，然后再计算差值进行比较断言。

```python
def validate_time_interval(content, specified_time):
    # 1、从返回结果中提取出start_time和end_time
    start_time, end_time = parse(content)

    # 2、进行比较断言
    assert end_time - start_time < specified_time
```
