### ISSUE TITLE
读入yml文件报权限错误

### ISSUE THREAD

**Issue by rihkddd** [HttpRunner/HttpRunner#66]
报错：IOError: [Errno 13] Permission denied: 'demo.yml'
--------------------------------------------------------------------
原因是下面一行使用了r+，其实只是读文件，没有+的必要。
with codecs.open(yaml_file, 'r+', encoding='utf-8') as stream

**Comment by debugtalk** [comment]
@rihkddd 感谢反馈，已修复。
