### ISSUE TITLE
setup_hooks 或 teardown_hooks 下调用的函数的返回值无法传给变量

### ISSUE THREAD

**Issue by chenliangtang** [httprunner/httprunner#668]
### 当前环境
win10，httprunner 2.2.5，python 3.7.4

### 问题描述
在 setup_hooks 或 teardown_hooks 下定义的钩子函数只能是单纯的执行，无法 return 返回值给变量（不能像在 variables 下定义的参数一样可以传给变量）。这样一来就无法对钩子函数执行的情况（在钩子函数内部去校验真的很不方便）进行校验。

### 再说我的需求
在用 httprunner 进行接口测试的时候，测试步骤只能是调用接口而不能执行自定义的函数，而且自定义函数也无法传返回值给变量（**其实我希望的就是可以在自定义的 hook 函数之间传值，方便进行校验**）。这样单纯只对接口返回值作校验的自动化测试是不够充分的，比如在测试插入数据的接口时，接口返回都正确了，但是这个时候我想去校验数据库的数据是否真的有插入了，就需要用到钩子去调用自定义函数，通过校验函数的返回值来 assert 结果。

### 修改建议
setup_hooks 或 teardown_hooks 下的钩子函数做不做校验倒无所谓，毕竟还不是 teststep，只是希望在测试步骤中也可以调用自定义钩子函数，而且各个自定义函数可以传返回值给变量，方便对自定义测试步骤的校验。

**Comment by chenhengjie123** [comment]
像这个官方示例中的调用自定义函数 `${get_sign($device_sn, $os_platform, $app_version)}` ，是否满足你提出的需要？

<https://cn.httprunner.org/data/demo-quickstart-6.yml>

**Comment by chenliangtang** [comment]
现在就是采用类似这样的方式来解决了

**Comment by chenhengjie123** [comment]
OK，既然已解决，这个问题就先关闭了。

如果有其它问题，可以建立新的 issue 。
