### ISSUE TITLE
2.2.5版本csv文件无法读取

### ISSUE THREAD

**Issue by 876957458** [httprunner/httprunner#677]
## 问题描述

读取csv文件时一直报找不到参数

## 版本信息

请提供如下版本信息：

 - 操作系统类型: mac
 - Python 版本 3.7.2
 - HttpRunner 版本 2.2.5

http_run_csv.json 文件内容
[
    {
        "config": {
            "name": "testSheet",
            "parameters":[
                {
                    "postid":"${P(postid.csv)}"
                }
            ],
            "base_url": "http://127.0.0.1:8088"
        }
    },
    {
        "test": {
            "name": "creat_article",
            "request": {
                "url": "/api/create/",
                "method": "POST",
                "headers": {
                    "User-Agent": "python-requests/2.18.4",
                    "Content-Type": "application/json"
                },
                "json": {
                    "title": "${postid}",
                    "content":"发二娃发"  
                }
            },
            "extract":{
                "info":"content.id"
            },
            "validate": [
                {
                    "eq": ["status_code",200]
                },
                {
                    "eq": ["content.message","创建成功"]
                }
            ]
        }
    }
]

postid.csv 文件内容

postid
hello
world
debugtalk

目录结果：
---code
     ---http_run_csv.json
     ---debugtalk.py
     ---postid.csv

报错信息：
hrun http_runner_csv.json 
INFO     HttpRunner version: 2.2.5
!!!!!!!!!! exception stage: parse tests !!!!!!!!!!
httprunner.exceptions.VariableNotFound: postid

**Comment by bruceqiao** [comment]
"title":"${postid}" 不是这么写的，csv 里的列名要跟参数名一直，然后 title: ${P(postid.csv)} 这样，看看文档先
