### ISSUE TITLE
httprunner.exceptions.VariableNotFound: field_name

### ISSUE THREAD

**Issue by phonix512** [httprunner/httprunner#678]
httprunner.exceptions.VariableNotFound: field_name

## Versions

2.2.5

 - OS: win10
 - Python 3.7
 - HttpRunner 2.2.5

用例如下

- config:
        name: VerifyOrder
        verify: false
- test:
        name: VerifyOrder
        variable_binds:
           - field_name: "VerifyOrder.txt"
           - file_path: "D:\\Liuwei"
           - file_type: "text/xml"
           - multipart_encoder: ${multipart_encoder($field_name,$file_path,$file_type)}
        request:
            headers:
                Content-Type: ${multipart_content_type($multipart_encoder)}
            data: $multipart_encoder        
            method:  'POST'
            url:  http://fcloud.zshl.daxi51.com:9180/scenic-ota/ota/xinXin/rent034/VerifyOrder
        validate:
          - eq: [content.resultCode,'0000']
          - eq: [content.resultMessage,'验证成功']

**Comment by phonix512** [comment]
自己解决了，关了

**Comment by Arwayc** [comment]
@phonix512 hello 请问下是如何解决的

**Comment by phonix512** [comment]
我没用他这种方式，我在debugtalk.py自定义函数去读入一个文件





--
随风不去


在 2019-10-08 15:25:18，"陈威" <notifications@github.com> 写道：


@phonix512 hello 请问下是如何解决的

**Comment by Arwayc** [comment]
方便贴一下你的那种方式吗？谢谢啦 @phonix512
