### ISSUE TITLE
【建议在仓库中移除poety.lock，只保留pyproject.toml】poety.lock用于在单元测试锁死了版本，如果只编辑了pyproject.toml，会导致poety没及时更新，导致验证失败。

### ISSUE THREAD

**Issue by chenhuahuan** [httprunner/httprunner#680]
## 问题描述

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd
/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/tests
$ hrun testcases/setup.yml
INFO     Loading environment variables from /Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/tests/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
ModuleNotFoundError: No module named 'tests.api_server'
```

**Comment by chenhengjie123** [comment]
1、针对标题里提到问题的解答：
poety.lock 是为了锁死版本，避免不同时候获取到的依赖库版本不一样，导致一些莫名其妙的问题。如果不放到代码仓库，会导致失去锁版本效果。

更新了 pyproject.toml 后，请通过 `poetry update` 更新 poety.lock 文件，然后再一并提交。详细的可以参照 poetry 官方文档：<https://github.com/sdispater/poetry#update>

2、针对运行堆栈信息的解答：
单元测试运行姿势不大对，请参照 <https://cn.httprunner.org/Installation/> 底部开发者模式相关的文档说明运行单元测试。
