### ISSUE TITLE
测试用例中如何使用 $ 符号而不转义为变量

### ISSUE THREAD

**Issue by xtander** [httprunner/httprunner#682]
graphql 的query中会用到$符号和httprunner中表示变量的$冲突

想用httprunner来写graphql类型的api测试，但是发现graphql的query中本身它可能会用到$符号，这样就与httprunner中的变量有点冲突，用requests是可以写的，没什么问题，只是不知道如何在httprunner里面表示graphql中的$，下面附上graphql中的一个json
`json = {
	"operationName": "stockLocations",
	"variables": {
		"page": {
			"page": 0,
			"size": 25
		},
		"sort": [{
			"property": "id",
			"direction": "DESC"
		}],
		"filter": []
	},
	"query": "query stockLocations($filter: [SearchCriteria], $page: SearchPage, $sort: [SearchOrder]) {\n  lists: stockLocations(filter: $filter, page: $page, sort: $sort) {\n    content {\n      id\n      name\n      code\n      completeName\n      inboundingHandlingTime\n      outboundingHandlingTime\n      type\n      active\n      createdBy\n      updatedBy\n      createdAt\n      updatedAt\n      __typename\n    }\n    pageInformation {\n      totalElements\n      __typename\n    }\n    __typename\n  }\n}\n"
}`
这里的$filter, $page, $sort就不知道怎么在httprunner中表示了

 - 操作系统类型: macos
 - Python 版本 3,72
 - HttpRunner 版本 2.13

**Comment by debugtalk** [comment]
如果在 YAML/JSON 测试用例中，本身需要使用 $ 符号，那么可以使用 $$ 进行转义。

```
$$page => $page
```

**Comment by shi053051** [comment]
使用$$的方式只能解决变量以$开头的情形， 如果变量是a$b的形式，还是有问题：
这种情形你写成a$$b, 还是会报变量b找不到

**Comment by debugtalk** [comment]
关闭此 issue，`a$$b` 的问题将在 #728 中跟进。
