### ISSUE TITLE
问题： 关于locusts分布式压测 如何获取slave上的error信息

### ISSUE THREAD

**Issue by AntonioWYC** [httprunner/httprunner#683]
## 问题描述

使用locusts 分布式压力测试时（master和slave 不在同一台mac上），无法从master或者slave上找到出错的Api的request/response信息。

## 版本信息

 - 操作系统类型: [macos]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.2.5]

请各位大神帮忙看一下这个问题：
1. 首先我用第一台mac作为master：
locusts -f HTTPRUNNER/testsuites/profile_service_testsuite.yml --master --logfile=reports/test1.txt

2. 使用第二台mac作为slave：
locusts -f HTTPRUNNER/testsuites/profile_service_testsuite.yml --slave --master-host=10.141.18.236

压力测试执行本身是没有问题的，可以在locust界面上看到有错误的百分比，或者export csv文件。但是当某些API出错的时候，不能在master或者slave的控制台或者指定的report 文件内找到任何error log. 这样就无法定位到当时API的错误原因。

请问这种情况应该如何处理？如何获取到分布式压测模式的错误log？

**Comment by debugtalk** [comment]
@AntonioWYC HttpRunner 的 locusts 只是对 Locust 进行了简单封装。据我所知，Locust 好像也不支持你提的的这个功能，所以 locusts 也没法支持。你可以到 https://github.com/locustio/locust/issues 去问下。
