### ISSUE TITLE
关于连续参数分隔问题

### ISSUE THREAD

**Issue by Ai-yoo** [httprunner/httprunner#684]
## 问题描述

两个连续的参数想用下划线分隔一下，httprunner将第一个参数结合后面的下划线作为一个整体去找这个参数，报错没有找到
e.g：$name_$password
error：VariableNotFound：name_ is not found.

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows
 - Python 版本 2.7.16
 - HttpRunner 版本 2.0.6

**Comment by chenhengjie123** [comment]
httprunner 暂时没有支持下划线分隔两个连续参数这样的功能。

若需要实现此功能，可以设定一个变量（假设名称为 underline ），值为下划线，然后通过 $name$underline$password这样的形式实现。

**Comment by Ai-yoo** [comment]
> httprunner 暂时没有支持下划线分隔两个连续参数这样的功能。
> 
> 若需要实现此功能，可以设定一个变量（假设名称为 underline ），值为下划线，然后通过 $name$underline$password这样的形式实现。

感谢回复
