### ISSUE TITLE
如何对请求返回的内容做格式处理

### ISSUE THREAD

**Issue by phonix512** [httprunner/httprunner#685]
## 问题描述

如何对请求返回的内容做格式处理

## 版本信息

 - 操作系统类型: Linux, Windows
 - Python 2.7.5
 - HttpRunner 2.2.5

请返回是内容是json,但是显示的是字符串格式，我想在测试报告中以json串的方式显示该如何处理

**Comment by chenhengjie123** [comment]
不是很理解你提到的 `返回内容是 json ，但显示是字符串格式` 的具体含义。

能否把你的具体请求返回内容，以抓包软件截图的或者 Har 文件内容的形式提供？

**Comment by bruceqiao** [comment]
```python
import json
data = json.loads('json_str')
```
这样？

**Comment by debugtalk** [comment]
@phonix512 在生成 HTML 报告的时候，会对结果进行 dump 处理，并且会进行 escape 处理，避免 XSS 的问题。如果你想获取原始的响应 json，可以在运行时添加 `--save-tests` 参数，运行后会在 logs 目录中生成 JSON 文件。
