### ISSUE TITLE
win10 64位 启动flask 的api_server.py服务报错：d:\python37\python.exe: No module named D:\python37\Scripts\flask

### ISSUE THREAD

**Issue by huangshijiea** [httprunner/httprunner#688]
## 问题描述

win10 64位 启动flask 的api_server.py服务报错 d:\python37\python.exe: No module named D:\python37\Scripts\flask

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows10 64位]
 - Python 版本 [ 3.6]
 - HttpRunner 版本 [e.g. 2.2.5]

![image](https://user-images.githubusercontent.com/39993589/63678447-d97f8600-c821-11e9-9369-54e2ba069f7b.png)
![image](https://user-images.githubusercontent.com/39993589/63678502-ebf9bf80-c821-11e9-8171-73da88eea43d.png)

**Comment by chenhengjie123** [comment]
flask 版本信息提供下？或者把你搭建本地开发环境的完整步骤、使用的命令也提供下？

**Comment by debugtalk** [comment]
@huangshijiea 这是你本地 flask 环境的问题，api_server.py 只是一个简单的 flask 应用，建议你再排查下本地 flask 环境。
