### ISSUE TITLE
开发者模式运行找不到main-debug.py, 需要手动添加吗

### ISSUE THREAD

**Issue by liujingaaa** [httprunner/httprunner#695]
## 问题描述

 can't open file 'main-debug.py': [Errno 2] No such file or directory

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Windows 10]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.2.5]

## 运行命令 && 堆栈信息
(HttpRunner-7iYlK5I4) (HttpRunner) G:\codecoverage\httprunner\HttpRunner>pipenv run python main-debug.py hrun -h+
D:\Users\user\.virtualenvs\HttpRunner-7iYlK5I4\Scripts\python.exe: can't open file 'main-debug.py': [Errno 2] No such file or directory

**Comment by ljw8947** [comment]
give a try

```python
import sys

from httprunner.cli import main_hrun, main_locust
from httprunner.logger import color_print

cmd = sys.argv.pop(1)

if cmd in ["hrun", "httprunner", "ate"]:
    main_hrun()
elif cmd in ["locust", "locusts"]:
    main_locust()
else:
    color_print("Miss debugging type.", "RED")
    example = "\n".join([
        "e.g.",
        "python main-debug.py hrun /path/to/testcase_file",
        "python main-debug.py locusts -f /path/to/testcase_file"
    ])
    color_print(example, "yellow")
```

**Comment by liujingaaa** [comment]
可以用，多谢大神~

**Comment by debugtalk** [comment]
已经移除 main-debug.py，当前可用的方式为：

```bash
$ python -m httprunner.cli hrun -h
$ python -m httprunner.cli locusts -h
```
