### ISSUE TITLE
config里定义的参数会覆盖另一用例的config的参数

### ISSUE THREAD

**Issue by michaelWGR** [httprunner/httprunner#697]
## 问题描述

- testcases里两个测试用例a、b，a与b都在config里定义了variables且参数名相同
- testsuit里使用一个yaml文件调用这两个用例a、b
- a的variables里的参数会覆盖b的variables里的参数
## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Python 版本 3.7.3
 - HttpRunner 版本 2.2.5

**Comment by chenhengjie123** [comment]
config 是整个执行过程中的全局配置，同名变量是会相互覆盖的。

能否把你的具体场景说明下，以及说明下为何不能用不一样的参数名？

**Comment by michaelWGR** [comment]
因为项目是多人合作的，如果testcases文件夹里的用例的config定义的参数名会相互覆盖，这样会造成config定义变量变成整个项目只能是唯一的，定义时还要去查看其他用例用没有定义到同名参数，会比较麻烦
