### ISSUE TITLE
api分层后运行不了

### ISSUE THREAD

**Issue by Helen-Shen** [HttpRunner/HttpRunner#70]
httprunner.exception.ApiNotFound: api api_get_token not found!
想问下为什么总是提示找不到api？api也是在api目录下的，也以api_XXX来开头了，但是一直提示这个。

**Comment by Helen-Shen** [comment]
另外HelloWorld的例子没有找到在哪里。

**Comment by Archer456** [comment]
@Helen-Shen 
https://github.com/HttpRunner/HttpRunner/blob/master/tests/test_response.py   这个？

**Comment by Archer456** [comment]
@Helen-Shen 
https://testerhome.com/topics/11338
看这个吧  我知道你说的是什么了   那个api_server  要这样开启 才能访问的到demo里的 那个get_token 和users

**Comment by Helen-Shen** [comment]
cmd进入的目录太底层了，到tests的上一层就能成功调用了。

**Comment by Helen-Shen** [comment]
@Archer456 嗯嗯，谢谢，已经可以执行了~

**Comment by debugtalk** [comment]
这么看来，感觉设置tests这一层有些多余，后面看要不还是去除好了。
