### ISSUE TITLE
testsuit里面断言validate 好像没有效果

### ISSUE THREAD

**Issue by w770762632** [httprunner/httprunner#702]
## 问题描述

请对遇到的 bug 进行简要描述。
testsuit的的断言
   validate:
        - eq: ["content.resultCode", '0000']
        - eq: ["content.resultMsg", '系统错误']

testcase的断言
    validate:
        - eq: ["status_code", 200]
        - eq: ["content.resultCode", '9999']
测试报告里面的断言

check | comparator | expect value | actual value
-- | -- | -- | --
status_code | equals | 200 | 200
content.resultCode | equals | 9999 | 9999

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.1.2]

**Comment by debugtalk** [comment]
@w770762632 这是个之前版本的 bug，已经修复了，升级到最新版本再试下。
