### ISSUE TITLE
基础库的生成HTML报告异常,'HttpRunner' object has no attribute 'gen_html_report'

### ISSUE THREAD

**Issue by lk236225128** [httprunner/httprunner#706]
## 问题描述

基础库调用'生成HTML报告'方法异常.

代码为:
# generate html report
runner.gen_html_report(
    html_report_name="demo",
    html_report_template="/path/to/custom_report_template"
)

错误信息:'HttpRunner' object has no attribute 'gen_html_report'

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [e.g. macos, Linux, Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.2.5]

**Comment by debugtalk** [comment]
@lk236225128 HttpRunner 的基础库 API 发生了变更，对应文档没有更新。

当前可以这边调用：

```python
from httprunner.report import render_html_report
```

不过这部分的设计还有些问题，需要重新梳理下，后面应该还会再变。
