### ISSUE TITLE
统计结果summary中的time.duration不准确

### ISSUE THREAD

**Issue by plmmilove** [httprunner/httprunner#707]
通过目录跑多个测试用例，发现time.duration不准确（偏大很多），所有测试用例跑完在10s左右，time.duration的值却是60多s。
查看代码发现现在的实现是将各个测试用例的时间累加，但实际上执行完所有的测试用例的时间应该是所有测试用例中max(start_at + duration) - min(start_at)
**report.py 168行**
report.aggregate_stat(summary["time"], testcase_summary["time"])

**report.py 73行**
def aggregate_stat(origin_stat, new_stat):
    """ aggregate new_stat to origin_stat.

    Args:
        origin_stat (dict): origin stat dict, will be updated with new_stat dict.
        new_stat (dict): new stat dict.

    """
    for key in new_stat:
        if key not in origin_stat:
            origin_stat[key] = new_stat[key]
        elif key == "start_at":
            # start datetime
            origin_stat[key] = min(origin_stat[key], new_stat[key])
        else:
            origin_stat[key] += new_stat[key]

 - 操作系统类型: Linux, Windows
 - Python: 3.5
 - HttpRunner: 2.2.5

**Comment by lijuelijue** [comment]
httprunner 1.5.15一样有这样的问题。

**Comment by lijuelijue** [comment]
把函数改成以下代码即可解决了：   
 for key in new_stat:
        if key not in origin_stat:
            origin_stat[key] = new_stat[key]
        elif key == "duration":
            # start datetime

            origin_stat[key] = max(origin_stat["start_at"] + origin_stat["duration"],
                                   new_stat["start_at"] + new_stat["duration"]) - min(origin_stat["start_at"],
                                                                                      new_stat["start_at"])
        else:
            origin_stat[key] = min(origin_stat[key], new_stat[key])

**Comment by debugtalk** [comment]
@lijuelijue @plmmilove 欢迎提交 PR
