### ISSUE TITLE
关于日志记录的问题?

### ISSUE THREAD

**Issue by zwlloveyanyan** [HttpRunner/HttpRunner#71]
场景是 一次性执行完大概200个接口用例之后，对状态码返回2XX之外的进行错误的日志记录。但是看了下源码，发现只有把基本的status_code，response_time等输出到终端，也没有外部可以设置日志路径和日志存储内容的方式，作为个刚接触python的新手，我自己想的一个办法是在每个用例里面对返回值调用自定义函数，传入content和expect对应的status_code
然后新建filehander，logger.error根据status_code出错就存储content。这样我就可以愉快的记录错误的接口返回信息了，但是出现一个问题，我还要记录发送的内容和接口的url（这样才能能清楚知道什么输入导致了接口返回错误），但是自定义校验函数只能传两个参数，url和status_code是不被content包含的，如果用拼接的方式可以实现，但是很不优雅
所以，大神，我该咋整呢?谢谢您

**Comment by debugtalk** [comment]
@zwlloveyanyan 后续我再增加日志文件输出的功能吧

**Comment by debugtalk** [comment]
已经具备详细的运行日志记录，在测试报告中也包含了完整的请求、响应数据。
