### ISSUE TITLE
testcase添加skipIf无效，只在api里添加有效

### ISSUE THREAD

**Issue by luffy7272** [httprunner/httprunner#719]
## 问题描述

testcase添加skipIf无效，只在api里添加有效

## 版本信息

请提供如下版本信息：

 - 操作系统类型:  Windows
 - Python 版本:  3.6
 - HttpRunner 版本:  2.1.2

## 简单描述
```
-   test:
        name: 登录
        skipIf: 1      // 无效
        testcase: login.yml  

-   test:
        name: 登录
        skipIf: 1     // 有效
        api: login.yaml
```

**Comment by shi053051** [comment]
第一种情况， skipif应该放在testcase里面吧

**Comment by luffy7272** [comment]
> 第一种情况， skipif应该放在testcase里面吧

你的意思是放api层吧（第二个例子），但是有的testcase会引用其他的testcase（第一个例子），多处复用的，只想在引用的时候加skip，这样就不好操作了
