### ISSUE TITLE
如何定义接口的可选参数呢？

### ISSUE THREAD

**Issue by zwxk14** [HttpRunner/HttpRunner#72]
即某个接口有一个参数是可选的，如果该参数没有值时，就不需要传递该参数。

测试用例准备时，接口调用是同一个，但该可选参数是部分用例才会有的。

**Comment by debugtalk** [comment]
@zwxk14 

> 如果该参数没有值时，可以无需传递该参数。

此时虽然没有传递参数，但在接口定义处肯定是有一个默认值的。为了保证接口调用的统一，你可以显式地传入该默认值。

**Comment by zwxk14** [comment]
Thanks! 
目前实际使用时也是这么做的。只是如果支持optional的参数，测试用例的数据准备就可以和接口设计文档一致性更好了。

**Comment by wushenghang** [comment]
在版本迭代过中，如果api添加了新的入参，如果是这样，之前调用api的用例是不是就得全部重新修改

**Comment by debugtalk** [comment]
@wushenghang 接口新增参数字段后，如果调用的用例没有涉及到该字段，那么就不需要改动用例；如果有涉及到，那肯定就得修改了。
