### ISSUE TITLE
Testcase无法引用API的问题

### ISSUE THREAD

**Issue by LuanShiZhiJian** [httprunner/httprunner#725]
## 问题描述

在testcase脚本中，已引用API路径，运行testcase报错提示如下信息
!!!!!!!!!! exception stage: load tests !!!!!!!!!!
KeyError: 'api/demo_api.yml'

During handling of the above exception, another exception occurred:

httprunner.exceptions.ApiNotFound: api/demo_api.yml not found!”

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7]
 - HttpRunner 版本 [e.g. 2.2.6]

## 项目文件内容（非必须）
项目结构：
![image](https://user-images.githubusercontent.com/41558924/66796922-c8a6e300-ef3b-11e9-89e3-071af31773f9.png)

API代码：
![image](https://user-images.githubusercontent.com/41558924/66797099-44089480-ef3c-11e9-8db6-a78fb8d172c4.png)

testcase代码：
![image](https://user-images.githubusercontent.com/41558924/66797044-17ed1380-ef3c-11e9-98d0-888000f63513.png)

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```hrun demo_testcase.yml
INFO     HttpRunner version: 2.2.6
!!!!!!!!!! exception stage: load tests !!!!!!!!!!
KeyError: 'api/demo_api.yml'

During handling of the above exception, another exception occurred:

httprunner.exceptions.ApiNotFound: api/demo_api.yml not found!
```

**Comment by LuanShiZhiJian** [comment]
解决办法：将test改为teststeps，正常运行，但仍显示警告信息：

INFO     HttpRunner version: 2.2.6
WARNING  unexpected block key: teststeps. block key should only be 'config' or 'test'.
WARNING  unexpected block key: teststeps. block key should only be 'config' or 'test'.
INFO     Start to run testcase: demo testcase

**Comment by LuanShiZhiJian** [comment]
在项目根目录下运行即可

**Comment by wnzhangfeiyang** [comment]
如何解决的，我在项目根目录 会报api未定义
