### ISSUE TITLE
variables 中的参数变量类型int转string失败

### ISSUE THREAD

**Issue by kaceychow** [httprunner/httprunner#731]
## 问题描述
测试步骤编写如下：
![image](https://user-images.githubusercontent.com/44224385/67372789-0a293500-f5b1-11e9-9602-c58a9fb004be.png)

接口编写如下：
![image](https://user-images.githubusercontent.com/44224385/67372526-9d159f80-f5b0-11e9-824e-b288835f65bd.png)

执行用例后hrun XXX.yml
请求接口入参value依旧没有带引号。{"id": 29}

请对遇到的 bug 进行简要描述。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Windows 10
 - Python 版本：Python 3.6.5 :: Anaconda, Inc.
 - HttpRunner 版本：2.2.0

**Comment by debugtalk** [comment]
@kaceychow 在 YAML 中所有字段都是 string，"$id" 和 $id 的效果相同。若你需要实现类型转换，需要你在 python 代码中实现。
