### ISSUE TITLE
python2.7 中 unicode 异常

### ISSUE THREAD

**Issue by hazer491** [httprunner/httprunner#732]
if not isinstance(path, (str, list)):
        return False

python2.7 unicode不是str,
validator.py 这里过不去
除非改成
if not isinstance(path, (unicode, str, list)):
        return False

**Comment by debugtalk** [comment]
@shi053051 你反馈的可能的确是个 bug。不过还有两个多月 Python 2.7 就 EOF 了，后面 HttpRunner 也将不再支持 2.7，建议你使用 Python 3 哈。
