### ISSUE TITLE
HttpRunner().run() 传入 JSON 结构体的逻辑

### ISSUE THREAD

**Issue by hazer491** [httprunner/httprunner#736]
HttpRunner().run() 当传入case/suite 路径的时候：
全局的mapping文件（全局参数文件）可以当参数传入，case里面各种$function能自动被识别(load_test自动加载)：HttpRunner().run(case_path,mapping=mapping) 

为什么传入JSON 结构体不采用相同的方式，而要自己把mapping拼凑到project_mapping的variables里面。关键还要自己实现locate_debugtalk_py把debugtalk里面用到的函数提取到project_mapping的functions里面。。。
我觉得这个过程完全可以跟传入case/suite 路径的时候一样由httprunner自己去实现。

**Comment by debugtalk** [comment]
@hazer491 传入 case/suite 路径的时候，因为有文件路径，所以可以基于文件路径去查找 debugtalk.py，从而确定出项目的根路径。

而传入 JSON 的时候：
（1）是没有 case/suite 文件路径的，也就没法去自动定位项目根路径了；
（2）传入 JSON，说明是将 HttpRunner 当作库函数在调用，通常需要更高的自由度，因此参数准备交给调用方也比较合适。
