### ISSUE TITLE
命令行执行hrun时 添加自定义的一个参数 执行结束后报错

### ISSUE THREAD

**Issue by grily** [httprunner/httprunner#737]
我的执行命令：hrun testsuites\agent_info_suit.yaml 3
报错信息如下：
ERROR    !!!!!!!!!! exception stage: generate html report !!!!!!!!!!
httprunner.exceptions.ParamsError: Invalid testcase path or testcases: 3

原先的执行命令是：hrun testsuites\agent_info_suit.yaml 执行没有问题
后面为了区分不同的执行环境 ；执行命令中添加最后一个参数 3；执行后可以生成报告；但是在最后会报一个异常信息；

**Comment by debugtalk** [comment]
问题在于，hrun 后面需要指定 1 个或多个 测试用例的路径。
而你写的 `3` 不是测试用例路径，所以会报错。
