### ISSUE TITLE
测试数据的来源问题

### ISSUE THREAD

**Issue by Helen-Shen** [HttpRunner/HttpRunner#74]
想问一下，现在测试数据可以通过csv等文件或者是从数据库中读取吗?
同一个接口入参和预期值有多套的时候怎么维护数据比较好呢？

**Comment by debugtalk** [comment]
@Helen-Shen 你提到的功能当前还不具备，属于计划中开发的功能点。

**Comment by debugtalk** [comment]
测试用例已经支持参数化数据驱动机制。
设计文档：http://debugtalk.com/post/httprunner-data-driven/
使用文档：http://cn.httprunner.org/data-driven/
