### ISSUE TITLE
疑问&建议

### ISSUE THREAD

**Issue by HK714456322** [HttpRunner/HttpRunner#75]
1、如何执行多个yml文件，结果报告合并展示到同一HTML文件
2、结果报告文件能否展示更详细的日志记录，包括具体的请求数据和验证数据？
3、是否支持跨yml文件传参数？

**Comment by debugtalk** [comment]
@HK714456322 
1&2、请阅读文档 [运行测试用例](http://cn.httprunner.org/run-test/)
3、支持，请参考 [HttpRunner 的测试用例分层机制](http://debugtalk.com/post/HttpRunner-testcase-layer/)
