### ISSUE TITLE
验证结果能否结合查询数据库？

### ISSUE THREAD

**Issue by ccmteorljh** [HttpRunner/HttpRunner#76]
在编写测试用例yml文件时能否在
validate:
        - {"check": "status_code", "expect": 200}
里面添加自定义的数据库查询函数,如：
validate:
        - {"check": ${isExist($tablename,$useId)}, "expect":true}

**Comment by debugtalk** [comment]
@ccmteorljh 你的需求其实就是在`validate`中调用自定义函数，并比较自定义函数的运行结果。

请参考[《HttpRunner 的结果校验器优化》](http://debugtalk.com/post/HttpRunner-validator-optimization/) 中的 “新增支持自定义结果校验器” 章节。
