### ISSUE TITLE
validate中contains和contained_by不存在？

### ISSUE THREAD

**Issue by Kewings** [httprunner/httprunner#769]
## 问题描述

有没有提供A in B或者B in A的方法？

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [e.g. 3.7.3]
 - HttpRunner 版本 [e.g. 2.2.5]

**Comment by debugtalk** [comment]
有的，详见 `httprunner/built_in.py`
