### ISSUE TITLE
如何能让api中的结果验证和testcase中的结果验证并存

### ISSUE THREAD

**Issue by Jay518801** [HttpRunner/HttpRunner#78]
在api中设置了返回值结果验证：
validators:
        - eq: ["content.result_code", "success"]
        - gt: ["content.data.activity_id", 0]
        - ne: ["content.request_id", ""]
        - gt: ["content.server_time", 0]

在testcase中同样设置了返回值结果验证：
validate:
        - eq: ["content.result_code", "success"]

但这两者无法同时进行check，仅testcase的生效了，api的未生效

**Comment by debugtalk** [comment]
@Jay518801 当前的机制是这样的：

1、testcase 中假如没有 validate，则取 api 中的；
2、testcase 中假如有 validate，则覆盖 api 中的。

**Comment by Jay518801** [comment]
是否有可能让两者同时生效呢，这样api中添加的是对接口最基本的验证，而testcase中的则是场景化的返回值验证。也减少重复编写结果验证的麻烦

**Comment by debugtalk** [comment]
@Jay518801 嗯，我调整下，调整后会是这样的：

1、testcase 先继承 api 中的校验器；
2、将testcase 中的校验器与api中的校验器进行合并，若存在相同的校验项，则取testcase中的校验项。

**Comment by debugtalk** [comment]
@Jay518801 改好了，你那边也测试看下吧。
