### ISSUE TITLE
1. 如果我debugtalk.py里面通过sql取数据是多个，传参是否支持多个？

### ISSUE THREAD

**Issue by chy-zhangxue** [httprunner/httprunner#785]
## 问题描述

1. 我通过debugtalk.py查询出多个值并作为入参，在case的yml/json文件中引用这个参数的时候是否支持传指定某个参数？

## 版本信息
请提供如下版本信息：

 - 操作系统类型: [ Windows]
 - Python 版本 [3.7.4]
 - HttpRunner 版本 [2.3.1]

**Comment by chenkyy** [comment]
len_eq可以断言数组长度

**Comment by chy-zhangxue** [comment]
debugtalk中添加通过index获取数据的方法即可；
