### ISSUE TITLE
使用新的测试用例分层机制，是否还能在API中使用variables定义一些参数值？

### ISSUE THREAD

**Issue by Jay518801** [HttpRunner/HttpRunner#79]

**Comment by debugtalk** [comment]
@Jay518801 可以的。

**Comment by Jay518801** [comment]
当testcase中和API中同时存在variables并定义了一些参数， testcase中的参数无法被正常导入，被API的参数覆盖了。在testcase.py中，增加添加的代码就好了

                if "api" in test_block_dict:
                    ref_name = test_block_dict["api"]
                    test_info = get_testinfo_by_reference(ref_name, "api")
           +++ test_info["variables"]= test_info["variables"] + test_block_dict["variables"]
                    test_block_dict.update(test_info)
                    testset["testcases"].append(test_block_dict)
