### ISSUE TITLE
基础库调用中，传入标准结构体的格式问题

### ISSUE THREAD

**Issue by esnhysythh** [httprunner/httprunner#790]
HttpRunner V2.x 中文使用文档 中
对传入的标准结构体的方法， 传入的结构的标准描述非常笼统，只有一个简单的testcase级别的样例，
对于如何传入单独的api，或者testsuit都没有说明，
对于在testcase的teststeps中引入api的格式也没有说明

目前，我参照运行时 save_tests=True 参数生成的 load.json 的格式，将testcase传入是没有问题的。
但是，参照 load.json 的格式传入 api 时则会显示 "Invalid testcase path or testcases"

希望能完善传入标准结构体进行测试的相关功能的文档，增加一下标准结构体的规范说明和更丰富的实例

**Comment by esnhysythh** [comment]
更新：
传入结构体格式按照“ save_tests=True 参数生成的 load.json 的格式”是可行的，

但是对于单独的 api， 以及 testsuits 来说，不能直接用HttpRunner.run( ) 方法
会报 Invalid testcase path or testcases 错误
但直接调用 HttpRunner.run_tests( ) 方法是可行的。

疑似bug， 传入 api 或者 testsuit 的结构体时识别有错误

**Comment by esnhysythh** [comment]
更新：
问题出在 run 方法中调用的校验方法 validator._is_testcases
该方法实质上是校验了传入的结构体“是否为标准的testcases形式”，校验了传入的结构体是否包含“testcases”字段，以及字段是否为空等。

但是如果传入的结构体中，是纯粹的 testsuit 或者 api 则无法识别，尽管该结构体符合 run_test 方法的规范

**Comment by debugtalk** [comment]
坐等 @readyou 的 jsonschema

**Comment by debugtalk** [comment]
@esnhysythh 已支持 jsonschema 校验。apis/testcases/testsuites 的校验也已修复。
