### ISSUE TITLE
在case1中output一个变量值，然后在case2中，使用这个变量值作为请求参数和预期结果，预期结果中值显示是：LazyString($audid)

### ISSUE THREAD

**Issue by LinZLin** [httprunner/httprunner#791]
case2中，发出请求正确，但是预期结果出错，把LazyString($audid)当成了预期结果，导致判断失败

**Comment by LinZLin** [comment]
audid是output的参数值
换了两个浏览器都上传不了图片，尴尬

**Comment by hazer491** [comment]
可以试试在case2里面设置一个变量来接收$audid，再对这个变量进行check。

**Comment by LinZLin** [comment]
按照上面的方法解决了，感谢
