### ISSUE TITLE
环境配置求助

### ISSUE THREAD

**Issue by masterliu** [httprunner/httprunner#797]
## 问题描述
环境配置:
安装完httprunenr后,查看包内没有locustios,直接安装了pip install locustio
执行帮助文档中的locusts -V的时候.没有像文档中返回相应的提示.
![捕获](https://user-images.githubusercontent.com/6879319/71168439-ad38bb00-2291-11ea-9155-12be5d588e42.PNG)

请问需要我怎么做.
## 版本信息
 - 操作系统类型: [e.g. Windows]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 2.4.4]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

locusts -V
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\locusts.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'httprunner.plugins'

**Comment by GodXzy** [comment]
我也遇到这个问题了，使用的是httprunner-2.4.5，将版本更换为httprunner-2.4.0时解决了这个问题；

**Comment by masterliu** [comment]
> 我也遇到这个问题了，使用的是httprunner-2.4.5，将版本更换为httprunner-2.4.0时解决了这个问题；

哦哦好。感谢
