### ISSUE TITLE
手动传入结构体时，没有自动设置全局变量“project_working_directory”(测试根目录)

### ISSUE THREAD

**Issue by esnhysythh** [httprunner/httprunner#808]
## 问题描述
httprunner在接收手动传入的结构体时，
没有添加全局变量project_working_directory，即表示测试项目根目录的全局变量
即使我已经将“PWD”关键字存入传入结构体的“project_mapping”中。

这在大多数情况下是不会出问题的，
但是在用文件上传的方法时，即调用upload关键字时，就会出现问题，

文件上传的方法，调用了httprunner.loder.locate.py 中的 get_project_working_directory():方法，该方法会查询 httprunner.loder.locate.py 中的全局变量 project_working_directory ，如果没有设置该变量，会报出“loader.load_cases() has not been called” 的错误，产生的结果是，用例无法正常运行，接口直接无法访问
## 版本信息

 - 操作系统类型: [Windows7]
 - Python 版本 [3.7.4]
 - HttpRunner 版本 [2.4.5]

## 项目文件内容
我传入的结构体如下：
~~~~~~~~~~~~~~
{
	"project_mapping": {
		"env": {},
		"PWD": "F:\\httprunner-auto-test",
		"function": {}，
		"test_path": "F:\\httprunner-auto-test\\api"
	},
	"apis": [
		{
			"name": "notebooks",
			"request": {
				"url": "xxxxxxxxx(an url)"
				"headers": {
					"Authorization": "xxxxxxxxx(a token)"
				},
				"method": "POST",
				"upload": {
					"file": "xxxxxxxxx(a path to file)",
					"title": "test_title",
					"content": "test_content"
				}
			},
			"validate": [
				{
					"eq": ["status_code", 200]
				}
			],
			"path": "F:\\httprunner-auto-test\\api\\notebooks.yml",
			"type": "api"
		}
	]
}

~~~~~~~~~~~~~~~~~~~
虽然在 project_mapping 中写入了 "PWD": "F:\\httprunner-auto-test"， 但是并没有设置到全局变量中。

目前解决方法为，手动调用httprunner相关参数，写入全局变量，
~~~~~~~~~~~~~~~~~~~
form httprunner.loader.locate import init_project_working_directory

init_project_working_directory("F:\\httprunner-auto-test")
~~~~~~~~~~~~~~~~~~~
如上

## 运行命令 && 堆栈信息
公司内部机不联网，
以下代码为手敲，可能有小错误：
~~~~~~~~~~~~~~~~~~~
Traceback (most recent call lasr):
  File "C:\python37\lib\site-packages\httprunner\api.py", line 61, in test
    test_runner.run_test(test_dict)
httprunner.exception.MyBaseFailure: loader.load_case() has not been called!
~~~~~~~~~~~~~~~~~~~
httprunner中具体报错文件位置为：
httprunner\loader\locate.py  第 108 行

**Comment by debugtalk** [comment]
@esnhysythh 这的确是个问题，已修复。
