### ISSUE TITLE
能提供一下框架流程图？

### ISSUE THREAD

**Issue by kavenxue** [HttpRunner/HttpRunner#81]

**Comment by debugtalk** [comment]
![image](https://user-images.githubusercontent.com/3657070/36880795-8aa2ad72-1e05-11e8-91b4-aec8aad0ff50.png)

**Comment by debugtalk** [comment]
后续再参考美团的 lego 画一个更完整的框架流程图。

https://tech.meituan.com/chenyongda-LegoApiTest.html

**Comment by debugtalk** [comment]
已补充：
https://www.processon.com/view/link/5b263148e4b0c383b07bde17
