### ISSUE TITLE
Extra的时候无法调用debugtalk里面的方法

### ISSUE THREAD

**Issue by handsonh** [httprunner/httprunner#815]
## Extra的时候无法调用debugtalk里面的方法

在debugtalk里面定义了一个方法，加了个判断，希望通过在extra的时候调用方法，结果报错了

![image](https://user-images.githubusercontent.com/59244317/71461021-3f3c4880-27e9-11ea-943c-64930bbabfac.png)

版本信息：

 - 操作系统类型: Windows-10-10.0.17763-SP0
 - Python 版本： 3.7
 - HttpRunner 版本：2.2.4

## 项目文件内容（非必须）

```python
def set_OLP_SUI():
    if (env=='QA1'):
        QA_OLP_SUI = "cookies.QA"
    elif (env=='PP'):
        QA_OLP_SUI = "cookies.PP"
    return QA_OLP_SUI
```

**Comment by debugtalk** [comment]
@handsonh 你的这种写法当前的确不支持。
