### ISSUE TITLE
HttpRunner V2.x 中文使用文档基础调用库中summary = runner.summary报错

### ISSUE THREAD

**Issue by wangyanqing666** [httprunner/httprunner#821]
## 问题描述
针对HTTPrunner进行二次开发
1：from httprunner.api import HttpRunner
2：runner=HttpRunner()
3：runner.run('测试用例.yml')
4:获取summary 
 runner.summary 会报错
AttributeError: 'dict' object has no attribute 'summary'
请对遇到的 bug 进行简要描述。
AttributeError: 'dict' object has no attribute 'summary'
## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.6.7
 - HttpRunner 版本最新版本

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。
查看源码：2以上版本return self._summary 已经变成私有了，1版本还是放开的。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd
/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/tests
$ hrun testcases/setup.yml
INFO     Loading environment variables from /Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/tests/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
ModuleNotFoundError: No module named 'tests.api_server'
```

**Comment by Aaaaace** [comment]
现在用`summary = runner.run(testcase)`就可以。
