### ISSUE TITLE
[bug] request json body is a list

### ISSUE THREAD

**Issue by moyanzhiyu** [httprunner/httprunner#824]
## 问题描述

我们的新增接口只会返回status code，response中不会返回任何。用postman直接调用是返回的200.
但是使用httprunner的话就报错 

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Windows]
 - Python 版本 [3.6]
 - HttpRunner 版本 [2.1.2]

报错信息

----------------------------------------------------------------------
Traceback (most recent call last):
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

![image](https://user-images.githubusercontent.com/26082425/71575186-f9ec8380-2b26-11ea-9e33-8a691eb6cbf5.png)

**Comment by debugtalk** [comment]
@moyanzhiyu 你直接使用 requests 库去请求有报错么？

**Comment by moyanzhiyu** [comment]
更新到最新版本 不会报错了 谢谢 但是现在最新版本 有另一个问题
teststeps:
-   name: /v1/klcs/classes/70/teachers
    request:
        headers:
        json:
        -   duty: 班主任
            teacher_id: 297
        method: POST

如果我直接在body里面放一个数组 就会报错 不让运行
ERROR    [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}] is not of type 'object'

Failed validating 'type' in schema[0]:
    {'description': 'request body in json format', 'type': 'object'}

On instance:
    [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}]
 
但是之前版本可以跑的

**Comment by moyanzhiyu** [comment]
我直接录制转换不管json还是yml都报错

**Comment by moyanzhiyu** [comment]
{
    "config": {
        "name": "testcase description",
        "variables": {}
    },
    "teststeps": [
        {
            "name": "/v1/klcs/classes/70/teachers",
            "request": {
                "url": "",
                "method": "POST",
                "headers": {
                },
                "json": [
                    {
                        "teacher_id": 297,
                        "duty": "班主任"
                    }
                ]
            },
            "validate": [
                {
                    "eq": [
                        "status_code",
                        200
                    ]
                }
            ]
        }
    ]
}

**Comment by moyanzhiyu** [comment]
@debugtalk

**Comment by debugtalk** [comment]
@moyanzhiyu 你确定这个接口请求的 body 是一个 list 格式？

**Comment by moyanzhiyu** [comment]
嗯 确定是一个数组

**Comment by debugtalk** [comment]
request json 已支持 list 类型。

**Comment by LeeJian** [comment]
@debugtalk  可以再2.x版本同步修复这个问题么？ 3.0由于httprunner的改动，之前的debugtalk文件需要从写

**Comment by debugtalk** [comment]
@LeeJian v3 已经兼容支持 v2 的用例格式了。

**Comment by LeeJian** [comment]
`
from httprunner.api import HttpRunner  

runner = HttpRunner()  

runner.run(r'testcases/login/login.yml', mapping=mapping)
`
这样写会先提示httprunner.api 不存在， 然后去掉api， 会提示 run（）没有mapping参数

**Comment by karencaiyuping** [comment]
> 更新到最新版本 不会报错了 谢谢 但是现在最新版本 有另一个问题
> 
> ```yaml
> teststeps:
> -   name: /v1/klcs/classes/70/teachers
>     request:
>         headers:
>         json:
>         -   duty: 班主任
>             teacher_id: 297
>         method: POST
> ```
> 
> 如果我直接在body里面放一个数组 就会报错 不让运行
> 
> ERROR [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}] is not of type 'object'
> 
> Failed validating 'type' in schema[0]:
> {'description': 'request body in json format', 'type': 'object'}
> 
> On instance:
> [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}]
> 
> 但是之前版本可以跑的

我跟你一样遇到了相同的问题，我是在2.及的版本遇到的

**Comment by karencaiyuping** [comment]
> > 更新到最新版本 不会报错了 谢谢 但是现在最新版本 有另一个问题
> > ```yaml
> > teststeps:
> > -   name: /v1/klcs/classes/70/teachers
> >     request:
> >         headers:
> >         json:
> >         -   duty: 班主任
> >             teacher_id: 297
> >         method: POST
> > ```
> > 
> > 
> > 如果我直接在body里面放一个数组 就会报错 不让运行
> > ERROR [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}] is not of type 'object'
> > Failed validating 'type' in schema[0]:
> > {'description': 'request body in json format', 'type': 'object'}
> > On instance:
> > [{'duty': '$duty_type0', 'teacher_id': '$teacher_id0'}]
> > 但是之前版本可以跑的
> 
> 我跟你一样遇到了相同的问题，我是在2.及的版本遇到的

你之前2.记得版本是可以的吗？也是一样这样写的吗，那你api那边是怎么写的呀

**Comment by wangtesting** [comment]
但是很多带参数的运行方式，随着不同版本，导致有的生效有的无效，很痛苦，不敢随意升级了都，也没有明确的些
