### ISSUE TITLE
windows 执行hrun生成报告失败

### ISSUE THREAD

**Issue by jaychang1989** [httprunner/httprunner#826]
## Describe the bug

生成报告报错，应该使用默认的格式时间问题，windows不支持带：符号的文件名

## Versions

Please complete the following information:

 - OS: [Windows]
 - Python [3.6]
 - HttpRunner [e.g. 2.4.9]

## Traceback

Traceback when bug occurs.

## Project structure

File structure of your project. A good way is to run `tree -a` command.

## Project files (If possible)
![image](https://user-images.githubusercontent.com/2285653/71617379-bc0a6080-2bf5-11ea-9dd6-a157f5524a73.png)
Provide your project files to help locate and debug bugs faster. This is not mandatory.

NOTICE: Before uploading your project files, don't forget to remove sensitive data, e.g. IP, username and password, key info etc.

**Comment by liuchangfu** [comment]
我也遇到这个问题了，请问该怎么解决?

**Comment by liuchangfu** [comment]
我的环境是
OS: [Windows]
Python [3.8]
HttpRunner [e.g. 2.4.9]
