### ISSUE TITLE
兼容性稀烂，发版前你做过windows兼容性测试么？？？

### ISSUE THREAD

**Issue by jaychang1989** [httprunner/httprunner#830]
## Describe the bug

2.4.9 生成报告文件格式windows不兼容；
2.5.0 报告<urlopen error [WinError 2] 系统找不到指定的文件。: '\\common.schema.json'>

## Versions

Please complete the following information:

 - OS: [Windows]
 - Python [3.6]
 - HttpRunner [2.5.0]

## Traceback

Traceback when bug occurs.

## Project structure

File structure of your project. A good way is to run `tree -a` command.

## Project files (If possible)
![QQ截图20200102100333.png](http://ww1.sinaimg.cn/large/6fa4e58agy1gahznu8gulj20hz03ra9x.jpg)

Provide your project files to help locate and debug bugs faster. This is not mandatory.

NOTICE: Before uploading your project files, don't forget to remove sensitive data, e.g. IP, username and password, key info etc.

**Comment by moyanzhiyu** [comment]
我也是遇到一样的问题 麻烦尽快修复

**Comment by debugtalk** [comment]
已修复。

本想在 GitHub Actions 中添加 HttpRunner 在 Windows 平台的兼容性测试。但始终运行失败，从日志中也看不出是啥问题，而且手头也没有 Windows 电脑可以验证。

**Comment by Master-An** [comment]
这提问的态度也太差了吧
