### ISSUE TITLE
请问validate校验中有unittest的一些断言方法吗？

### ISSUE THREAD

**Issue by loneyao** [httprunner/httprunner#831]
请问validate校验中有unittest的一些断言方法吗？比如：assertIsInstance，assertTrue这样的。

**Comment by debugtalk** [comment]
内置有如下断言方式。你也可以自定义断言。

"eq", "equals", "==", "is",
"lt", "less_than",
"le", "less_than_or_equals",
"gt", "greater_than",
"ge", "greater_than_or_equals",
"ne", "not_equals",
"str_eq", "string_equals",
"len_eq", "length_equals", "count_eq",
"len_gt", "count_gt", "length_greater_than", "count_greater_than",
"len_ge", "count_ge", "length_greater_than_or_equals", "count_greater_than_or_equals",
"len_lt", "count_lt", "length_less_than", "count_less_than",
"len_le", "count_le", "length_less_than_or_equals", "count_less_than_or_equals",
"contains",
"contained_by",
"type_match",
"regex_match",
"startswith",
"endswith"
