### ISSUE TITLE
2.4.9用绝对路径执行testsuite, 生成report报错

### ISSUE THREAD

**Issue by handsonh** [httprunner/httprunner#832]
## 问题描述

无法生成report，提示路径错误
## 版本信息

请提供如下版本信息：

 - 操作系统类型: windows 10
 - Python 版本 3.7
 - HttpRunner 版本 2.4.9

## 运行命令 && 堆栈信息

生成的report 路径会变成：

```
Generated Html report: D:\\API_Testing\\reports\\1577936050.html
```

如果是2.4.4版本正常的路径应该是：

```
Generated Html report: D:\API_Testing\reports\1577936050.html
```

所以现在只能卸载2.4.9，用回2.4.4才能解决这个问题

**Comment by debugtalk** [comment]
@handsonh 没看出你列出的两个版本生成 report 路径的差异。

报错有错误堆栈么？

**Comment by handsonh** [comment]
![image](https://user-images.githubusercontent.com/59244317/71701012-efb9d600-2e01-11ea-92e9-8bcfa23ca5b8.png)

**Comment by handsonh** [comment]
![image](https://user-images.githubusercontent.com/59244317/71701023-0102e280-2e02-11ea-8014-c38d65b578cd.png)

能看到图片么？

就是多了一个 /

// 和 /的区别

**Comment by handsonh** [comment]
应该是\

\\和\的区别

**Comment by handsonh** [comment]
回复变成了两个都一样显示了
