### ISSUE TITLE
linux下执行hrun命令报错：AttributeError: 'module' object has no attribute 'disable_warnings'

### ISSUE THREAD

**Issue by maxiaoqian** [httprunner/httprunner#838]
## 问题描述

linux系统中运行hrun命令报错

## 版本信息

请提供如下版本信息：

 - 操作系统类型: Linux
 - Python 版本 3.4
 - HttpRunner 版本：2.2.3

## 运行命令 && 堆栈信息

![image](https://user-images.githubusercontent.com/12823798/71718460-39341080-2e56-11ea-9f02-b6167821c30d.png)

**Comment by debugtalk** [comment]
@maxiaoqian HttpRunner 不支持 Python 3.4 版本，建议使用 Python 3.6+
