### ISSUE TITLE
校验器中的type_match功能无效

### ISSUE THREAD

**Issue by Jay518801** [HttpRunner/HttpRunner#84]
- type_match: ["content.data.users.0.user_id", 'int']

结果
	check item name: content.data.users.0.user_id;
	check item value: 580509390 (int);
	comparator: type_match;
	expected value: int (str).

**Comment by debugtalk** [comment]
@Jay518801 确定是bug，已经修复了。

之前的问题在于，`int`在Python脚本中是类型，而在`YAML/JSON`中是字符串，所以应该有个转换的过程才对。
