### ISSUE TITLE
运行中出现异常，summary没有完整信息，缺少请求信息

### ISSUE THREAD

**Issue by hellodjc11** [httprunner/httprunner#845]
## 问题描述
运行中如果出现异常，如extract的字段应对中没有，summary就会缺少信息，没有请求信息，无法判断请求是不是有问题，如下：
{'success': False, 'stat': {'testcases': {'total': 1, 'success': 0, 'fail': 1}, 'teststeps': {'total': 1, 'failures': 1, 'errors': 0, 'skipped': 0, 'expectedFailures': 0, 'unexpectedSuccesses': 0, 'successes': 0}}, 'time': {'start_at': 1578478050.6165676, 'duration': 0.18689250946044922}, 'platform': {'httprunner_version': '2.4.7', 'python_version': 'CPython 3.8.0', 'platform': 'Windows-10-10.0.17763-SP0'}, 'details': [{'success': False, 'stat': {'total': 1, 'failures': 1, 'errors': 0, 'skipped': 0, 'expectedFailures': 0, 'unexpectedSuccesses': 0, 'successes': 0}, 'time': {'start_at': 1578478050.6165676, 'duration': 0.18689250946044922}, 'records': [{'name': '查询分拣的信息', 'status': 'failure', 'attachment': 'Traceback (most recent call last):\n  File "C:\\Users\\daijiechao\\Desktop\\httprunner\\gongsi\\Api_auto\\api_master\\httprunner\\api.py", line 63, in test\n    test_runner.run_test(test_dict)\nhttprunner.exceptions.ExtractFailure: Failed to extract! => datas\nresponse body: {\'message\': \'无越库位拣货任务\', \'code\': \'301130231\', \'timestamp\': \'Wed Jan 08 18:07:30 GMT+08:00 2020\', \'success\': False}\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\daijiechao\\Desktop\\httprunner\\gongsi\\Api_auto\\api_master\\httprunner\\api.py", line 65, in test\n    self.fail(str(ex))\nAssertionError: Failed to extract! => datas\nresponse body: {\'message\': \'无越库位拣货任务\', \'code\': \'301130231\', \'timestamp\': \'Wed Jan 08 18:07:30 GMT+08:00 2020\', \'success\': False}\n\n', 'meta_datas': None, 'meta_datas_expanded': [], 'response_time': '0.00'}], 'name': 'web上创建波次，手持端拣货和分拣，web上出库完成-手持端查询波次下的任务的每个详细信息，并进行拣货', 'in_out': {'in': {'doRefNo': '', 'doType': 'TO', 'planId': 3529, 'test_id': 12924, 'waveId': 664530435095060480, 'waveNo': 'WV04732020010800035', 'waveType4View': 'TO_WS'}, 'out': {}}}]}
## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [e.g. 3.8.0]
 - HttpRunner 版本 [ 2.4.7]

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

summary =HttpRunner(failfast=False).run(new_case_file_name)

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

查询分拣的信息
INFO     GET http://t.bsapi.dingdongxiaoqu.com/wms-service/sorting/distribution
INFO     status_code: 200, response_time(ms): 150.92 ms, response_length: 122 bytes

ERROR    Failed to extract! => datas
response body: {'message': '无越库位拣货任务', 'code': '301130231', 'timestamp': 'Wed Jan 08 18:07:30 GMT+08:00 2020', 'success': False}

F

======================================================================
FAIL: test_0000_000 (httprunner.api.TestSequense)
查询分拣的信息
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\daijiechao\Desktop\httprunner\gongsi\Api_auto\api_master\httprunner\api.py", line 63, in test
    test_runner.run_test(test_dict)
httprunner.exceptions.ExtractFailure: Failed to extract! => datas
response body: {'message': '无越库位拣货任务', 'code': '301130231', 'timestamp': 'Wed Jan 08 18:07:30 GMT+08:00 2020', 'success': False}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daijiechao\Desktop\httprunner\gongsi\Api_auto\api_master\httprunner\api.py", line 65, in test
    self.fail(str(ex))
AssertionError: Failed to extract! => datas
response body: {'message': '无越库位拣货任务', 'code': '301130231', 'timestamp': 'Wed Jan 08 18:07:30 GMT+08:00 2020', 'success': False}

----------------------------------------------------------------------

**Comment by esnhysythh** [comment]
这确实是一个问题，给我也造成了很多困扰，希望早点解决吧。

问题体现在，只要 extract 出现问题，就会在 summary 中没有接口运行的log信息， 只有 traceback 相关的信息，即【不光是没有请求信息，同样也没有响应的信息】

目前我用的替代方法，是通过另外的抓包工具（目前使用的是Fiddler），再运行用例去抓到请求，检查问题。
