### ISSUE TITLE
har2case 转换的测例无法执行

### ISSUE THREAD

**Issue by LeeJian** [httprunner/httprunner#855]
## 问题描述

请对遇到的 bug 进行简要描述。
使用har2case 转换yml格式测例，执行报错：
ERROR    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}] is not of type 'object'

Failed validating 'type' in schema[0]:
    {'description': 'request body in json format', 'type': 'object'}

On instance:
    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}]
WARNING  Invalid test file format: hars/varia.yml
ERROR    test result summary is empty ! {'success': True, 'stat': {'testcases': {'total': 0, 'success': 0, 'fail': 0}, 'teststeps': {}}, 'time': {}, 'platform': {'httprunner_version': '2.5.4', 'python_version': 'CPython 3.7.6', 'platform': 'Darwin-19.3.0-x86_64-i386-64bit'}, 'details': []}
!!!!!!!!!! exception stage: generate html report !!!!!!!!!!

## 版本信息
2.5.4
请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本 3.7.6
 - HttpRunner 版本 2.5.4
 - **设备 ID**: [e.g. 190070690681122]

获取方式：

报错yml文件

```bash
-   name: /gateway/base/api/projects/18da66a7-9c7c-44ad-9893-942dcbcc3453/variables
    request:
        headers:
            Content-Type: application/json;charset=utf-8
            User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101
                Firefox/72.0
            sophonLocale: zh
        json:
        -   desc: aa
            name: aa
            value: aa
        method: POST
        url: https://172.26.0.43:8066/gateway/base/api/projects/18da66a7-9c7c-44ad-9893-942dcbcc3453/variables
    validate:
    -   eq:
        - status_code
        - 200
    -   eq:
        - headers.Content-Type
        - application/json;charset=UTF-8
```

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息
 hrun hars/varia.yml --log-level=debug
INFO     HttpRunner version: 2.5.4
INFO     Loading environment variables from /Users/lijian/Documents/soat/.env
DEBUG    Set OS environment variable: gateway_url
DEBUG    Set OS environment variable: auth_url
DEBUG    Set OS environment variable: username
DEBUG    Set OS environment variable: password
DEBUG    Set OS environment variable: login_url
ERROR    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}] is not of type 'object'

Failed validating 'type' in schema[0]:
    {'description': 'request body in json format', 'type': 'object'}

On instance:
    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}]
WARNING  Invalid test file format: hars/varia.yml
ERROR    test result summary is empty ! {'success': True, 'stat': {'testcases': {'total': 0, 'success': 0, 'fail': 0}, 'teststeps': {}}, 'time': {}, 'platform': {'httprunner_version': '2.5.4', 'python_version': 'CPython 3.7.6', 'platform': 'Darwin-19.3.0-x86_64-i386-64bit'}, 'details': []}
!!!!!!!!!! exception stage: generate html report !!!!!!!!!!

Sentry is attempting to send 3 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by whitexie** [comment]
har2case默认是转换为1.x版本的， 在转换时要加个参数`-fmt =v2`
![Snipaste_2020-02-19_13-14-06.png](https://i.loli.net/2020/02/19/vtiKPSboOrp9w2C.png)

**Comment by LeeJian** [comment]
添加了参数 `-fmt=v2`, 仍然存在相同问题。
转换出的case中，json写法仍是
`        json:
        -   desc: aa
            name: aa
            value: aa`
`ERROR    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}] is not of type 'object'

Failed validating 'type' in schema[0]:
    {'description': 'request body in json format', 'type': 'object'}

On instance:
    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}]
WARNING  Invalid test file format: hars/varia.yml
ERROR    test result summary is empty ! {'success': True, 'stat': {'testcases': {'total': 0, 'success': 0, 'fail': 0}, 'teststeps': {}}, 'time': {}, 'platform': {'httprunner_version': '2.5.4', 'python_version': 'CPython 3.7.6', 'platform': 'Darwin-19.3.0-x86_64-i386-64bit'}, 'details': []}
!!!!!!!!!! exception stage: generate html report !!!!!!!!!!

Sentry is attempting to send 3 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit`

**Comment by whitexie** [comment]
@LeeJian 能贴下har内容吗？

**Comment by LeeJian** [comment]
har中request部分如下：
`        "request": {
          "bodySize": 40,
          "method": "POST",
          "url": "https://xxxxxx:/gateway/base/api/projects/18da66a7-9c7c-44ad-9893-942dcbcc3453/variables",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "xxxx"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Accept-Language",
              "value": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Content-Type",
              "value": "application/json;charset=utf-8"
            },
            {
              "name": "sophonLocale",
              "value": "zh"
            },
            {
              "name": "Content-Length",
              "value": "40"
            },
            {
              "name": "Origin",
              "value": ""
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "https://xxxxx/projects/18da66a7-9c7c-44ad-9893-942dcbcc3453/settings"
            },
            {
              "name": "Cookie",
              "value": "locale=zh; SOPHONID=2a978619-5712-4fa9-868e-5a603c0e2b02; JSESSIONID=D5B0D807B42A523841B51A14DE536838; SESSION=b4547596-1b20-4785-b057-714cb2bee85b"
            }
          ],
          "cookies": [
            {
              "name": "locale",
              "value": "zh"
            },
            {
              "name": "SOPHONID",
              "value": "2a978619-5712-4fa9-868e-5a603c0e2b02"
            },
            {
              "name": "JSESSIONID",
              "value": "D5B0D807B42A523841B51A14DE536838"
            },
            {
              "name": "SESSION",
              "value": "b4547596-1b20-4785-b057-714cb2bee85b"
            }
          ],
          "queryString": [],
          "headersSize": 757,
          "postData": {
            "mimeType": "application/json;charset=utf-8",
            "params": [],
            "text": "[{\"name\":\"aa\",\"value\":\"aa\",\"desc\":\"aa\"}]"
          }
        },`

**Comment by whitexie** [comment]
@LeeJian  我转换之后看了下，request.json部分是个list，  和#824一样的问题，这个问题等作者调整吧
![image](https://user-images.githubusercontent.com/30469146/74905057-33839180-53e8-11ea-9a02-cfa6f0e48aff.png)

```
(venv) [test] hrun 123.yml                                                                                                                                         
INFO     HttpRunner version: 2.5.6
ERROR    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}] is not of type 'object'

Failed validating 'type' in schema[0]:
    {'description': 'request body in json format', 'type': 'object'}

On instance:
    [{'desc': 'aa', 'name': 'aa', 'value': 'aa'}]
WARNING  Invalid test file format: 123.yml
ERROR    failed to parse all cases, abort.
!!!!!!!!!! exception stage: parse tests !!!!!!!!!!

```

**Comment by LeeJian** [comment]
@whitexie  感谢
dup with #824
