### ISSUE TITLE
使用jsonpath报错

### ISSUE THREAD

**Issue by hazer491** [httprunner/httprunner#858]
## 问题描述
response.py 62行：
result = jsonpath.jsonpath(self.parsed_body(), field)
这里运行会报错：ResponseObject does not have attribute: parsed_body。
这个parsed_body()是什么？？

**Comment by whitexie** [comment]
如果可以的话，麻烦贴下脚本的yml

**Comment by debugtalk** [comment]
HttpRunner 支持的是 jmespath，暂不支持 jsonpath
