### ISSUE TITLE
如何将第一个api在数据库插入的数据传给第二个api

### ISSUE THREAD

**Issue by wushenghang** [HttpRunner/HttpRunner#86]
**场景是这样的：**
在测一个验证码登陆的功能的时候，需要调用两个接口，第一个是发送验证码接口，此时会在数据库插入一条信息，第二个接口是登陆接口，需要拿到第一个接口在数据库插入的验证码校验
**我们是这么做的：**
在debugtalk里写一个查询数据的方法getSmsCode()返回数据库最新的一条记录，定义两个api，在第二个api的时候设置了一个variable    `sms_code: ${getSmsCode()}`  再定义一个testcase，调用者两个api
**结果是：**
第一个接口成功通过了，但是第二个接口失败了，查看日志看出，第二个接口的sms_code取的是请求第一个接口前数据库最新的数据
**猜测：**
在执行testcase前，就已经将所有的variable加载完毕了
**试图解决一：**
将  `sms_code: ${getSmsCode()}` 放在第一个接口的extract，这样第一个接口执行完毕后用提取器去调用函数，得到sms_code传入下个接口，结果貌似extract无法调用函数
**试图解决二：**
第一种方法无法解决后，我就尝试将函数放入第二个接口的请求参数内，但由于接口还有另一个识别码sm，sm需要调用加密函数，`getSm()` 入参为所有接口入参，这样就会sm就会变成：
`sm: ${getSm(system=$system,versions=$versions,sms_code=${getSmsCode()},phone=$phone)}`
结果什么传入的值就是 `${getSm(system=$system,versions=$versions,sms_code=${getSmsCode()},phone=$phone)}`，而不是计算后的sm值
**问题：**
是否有其他种方案能解决这种问题？又或者是我操作错误了？

**Comment by wushenghang** [comment]
SQL查询的函数太早执行，加个休眠就行了

**Comment by Bu1eCat** [comment]
请问楼主，休眠是加在debugtalk的对应函数中么？

**Comment by xiaomanyaoer** [comment]
如果在执行testcase前，就已经将所有的variable加载完毕了，加休眠有用吗？

**Comment by xiaomanyaoer** [comment]
请问，这种情况应该怎么解决呢？多谢啦 @debugtalk

**Comment by RongXiaoCong** [comment]
> 一个测试用例有两个测试步骤，下边的测试步骤想用上一个测试步骤的执行结果作为入参，这个执行结果并不在response里边，而是存在了库里。请问，这种情况应该怎么解决呢？多谢啦 @debugtalk

1.在debugtalk.py中定义一个函数，用于执行sql
2.在测试用例头部的variables中加入sql
3.在需要使用数据的api中的variables中定义变量，调用函数，参数为前面写的sql
完成以上步骤参数就会传入了api了
