### ISSUE TITLE
tear_down的功能应该更丰富

### ISSUE THREAD

**Issue by hazer491** [httprunner/httprunner#865]
## 背景描述
目前的tear_down函数还是基于response做处理。
希望可以增加更广泛的功能。
比如跟report建立起联系：
1）修改当前case在report里面的的名字（特别是数据驱动的时候， 修改名字可以提高可读性）；
2）决定该条case是否展现在report里面（有些请求可能仅仅是为了获取某个参数，只是一个中间过 
      程， 不希望它出现在report里面）。

当然，以上两点都可以通过改最终的summary来实现， 但是改summary毕竟不方便。

**Comment by debugtalk** [comment]
@hazer491 在 v3 版本中，已将内置的 unittest 替换为 pytest，进而支持了 pytest 的 fixture 特性。你的这类需求都可以通过自定义 fixture 来实现。

下面是一个 fixture 示例。

https://github.com/httprunner/httprunner/blob/master/examples/postman_echo/request_methods/conftest.py

**Comment by debugtalk** [comment]
@hazer491 跟 summary 相关的另一个代码示例：

https://github.com/httprunner/httprunner/blob/master/httprunner/compat.py#L217
