### ISSUE TITLE
数据驱动

### ISSUE THREAD

**Issue by yanghuo662** [HttpRunner/HttpRunner#87]
比如我要访问一个文件上传接口，文件是分片来上传的，那么上传完1个文件可能需要访问这个接口100次，而每一次请求可能只有个别参数发生变化（如分片ID和分片内容等），能否循环调用优雅的实现呢？

**Comment by debugtalk** [comment]
@yanghuo662 当前是有`times`这么一个字段，可以指定某个接口运行从次数。

但针对你说的这种情况，数据驱动是最好方式，也就是指定需要运行的参数列表，这个是我后续要增加的一个功能。

**Comment by Doraly** [comment]
期待该框架 支持数据驱动的更新..

**Comment by debugtalk** [comment]
已更新支持[数据驱动](https://github.com/HttpRunner/HttpRunner/commit/f8569aad914d4fe47ec24ac2e2e472b7b93c310d)。
