### ISSUE TITLE
文档服务器好像是在国外，是否中文的文档在国内可以做一个镜像

### ISSUE THREAD

**Issue by xhuihui** [httprunner/httprunner#875]
## 背景描述
最近才开始了解项目，正在看文档，中文的文档在访问的时候会出现无法访问情况。简单查了一下服务好像不在国内

> 重点描述遇到的问题：在国内访问文档不稳定

## 期望的功能特性

> 期望 文档服务器在国内可以有镜像

**Comment by debugtalk** [comment]
@xhuihui 好的。

**Comment by debugtalk** [comment]
所有历史版本的文档会在这个仓库进行存档。
https://github.com/httprunner/docs
