### ISSUE TITLE
jsonpath 提取数据报错

### ISSUE THREAD

**Issue by malinpop** [httprunner/httprunner#876]
## 问题描述

使用 jsonpath 提取响应的 json 格式数据，报错：”ResponseObject does not have attribute: parsed_body“

## 版本信息

 - 操作系统类型: [Win7 64 旗舰]
 - Python 版本 [3.7]
 - HttpRunner 版本 [2.5.5]

## 项目文件内容（非必须）

- config:
    name: 码云API文档 - 用例 
    base_url: https://gitee.com/api/v5/repos
    variables:
      p_owner: youxxxxxx
      p_repo: Test
      p_sha: master
      p_token: 3d194.....
  

- test:
    name: 步骤 - 获取master分支所有的提交

    request:
      url: /$p_owner/$p_repo/commits
      method: GET
      params:
        sha: $p_sha
        access_token: $p_token

    extract:
      # - x: json.0.commit.committer  此行正确执行

      # 变成以下写法执行失败
      - x: "$..committer"            

    validate:
      - len_eq: [$x, 3]

**Comment by zhang598** [comment]
语法错误吧

```
# - x: json.0.commit.committer 此行正确执行

# 变成以下写法执行失败
- x: "$..committer"     
```

**Comment by debugtalk** [comment]
@malinpop HttpRunner 支持 jmespath，而不是 jsonpath。建议升级到 v3。

https://jmespath.org/
