### ISSUE TITLE
api方式调用时，testsuites类型时，两种schema会重复校验，导致报错，但不影响执行用例

### ISSUE THREAD

**Issue by weirdohaibo** [httprunner/httprunner#877]
## 问题描述
`from httprunner.api import HttpRunner`
api方式调用时，testsuites类型时，两种testcases schema会重复校验，导致报错，但不影响执行用例
一种报错说是要array类型，改成array时又要object
## 版本信息

请提供如下版本信息：

 - 操作系统类型: [ Linux, Windows]
 - Python 版本 [ 3.6]
 - HttpRunner 版本 [ 3.0.1]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

```
Failed validating 'type' in schema['properties']['testcases']:
    {'description': 'testcase of a testsuite',
     'items': {'$ref': 'testsuite.schema.v2.json#/definitions/testcase'},
     'minItems': 1,
     'type': 'array'}
On instance['testcases']:
```

**Comment by weirdohaibo** [comment]
@debugtalk httprunner/loader/check.py 203 行，建议增加判断，如果一种schema已经校验通过，则不校验另一种格式，避免在控制台打印大量的报错log。。

**Comment by debugtalk** [comment]
已替换使用 pydantic

**Comment by loneyao** [comment]
> pydantic

pydantic有使用的例子吗？
