### ISSUE TITLE
httprunner使用过程中存在的一些问题。

### ISSUE THREAD

**Issue by aspstar** [HttpRunner/HttpRunner#88]
HTTPRUNNER在使用过程中存在以下问题和疑问希望得到解决：
首先httprunner是一款国人编写的开源接口测试框架，让人心生佩服，有不少好的思路。不过实际使用过程感觉一些基本功能的缺失，只能完成简单的手工功能接口测试，所以请作者或其它大神帮忙解释一下我心中的疑惑。
1.har2case转换har文件时如何text:中存在因中文转换问题导致的"时，转换失败。
2.在执行yml过程中，如果YML的描述中存在某些JS或图片文件或连接参数中包括$时，执行失败。
3.httprunner到底有没有批量执行yml文件的能力？目前只能单个执行，没办法通过通配符批量执行。
4.没有类似loadrunner的参数化机制，如何使用10个线程执行10个不同参数的接口yml？

**Comment by aspstar** [comment]
问题3批量执行搞明白了，可以指定执行目录就能执行目录里所有的YML了，其它问题继续。

**Comment by debugtalk** [comment]
@aspstar 

1、正常情况下 har2case 应该是可以支持中文的；如果你使用时出现问题，建议在`har2case`项目中单独提issue，并附上出现问题的 har 文件，方便我这边进行排查；
2、这是因为在httprunner中$符号是有特殊含义的，作为变量和函数的转义符；
4、数据驱动的特性当前的确还没有实现，但已经加入近期的优化计划项了。

**Comment by debugtalk** [comment]
测试用例已经支持参数化数据驱动机制。
设计文档：http://debugtalk.com/post/httprunner-data-driven/
使用文档：http://cn.httprunner.org/data-driven/
