### ISSUE TITLE
接口文档与实际调用结果不一致

### ISSUE THREAD

**Issue by Jayzhang1995** [httprunner/httprunner#882]
我装的版本是2.5.7,发现测试结果与文档上很多地方都不一致了，麻烦更新一下文档
另外 2.5.7版本detail里没有base_url的参数了，也没看到其他参数可以替代
如果是我调用方法不对，还望指出
文档实例：
{
  "success": true,
  "stat": {
    "testsRun": 2,
    "failures": 0,
    "errors": 0,
    "skipped": 0,
    "expectedFailures": 0,
    "unexpectedSuccesses": 0,
    "successes": 2
  },
  "time": {
    "start_at": 1538449655.944404,
    "duration": 0.03181314468383789
  },
  "platform": {
    "httprunner_version": "1.5.14",
    "python_version": "CPython 3.6.5+",
    "platform": "Darwin-17.6.0-x86_64-i386-64bit"
  },
  "details": [
    {
      "success": true,
      "name": "testcase description",
      "base_url": "",
      "stat": {"testsRun": 2, "failures": 0, "errors": 0, "skipped": 0, "expectedFailures": 0, "unexpectedSuccesses": 0, "successes": 2},
      "time": {"start_at": 1538449655.944404, "duration": 0.03181314468383789},

实际调用结果：
{
	'success': True,
	'stat': {
		'testcases': {
			'total': 1,
			'success': 1,
			'fail': 0
		},
		'teststeps': {
			'total': 1,
			'failures': 0,
			'errors': 0,
			'skipped': 0,
			'expectedFailures': 0,
			'unexpectedSuccesses': 0,
			'successes': 1
		}
	},
	'time': {
		'start_at': '2020-04-23 17-10-35',
		'duration': 0.04336047172546387
	},
	'platform': {
		'httprunner_version': '2.5.7',
		'python_version': 'CPython 3.6.5',
		'platform': 'Linux-2.6.32-642.el6.x86_64-x86_64-with-centos-6.8-Final'
	},
	'details': [{
		'success': True,
		'stat': {
			'total': 1,
			'failures': 0,
			'errors': 0,
			'skipped': 0,
			'expectedFailures': 0,
			'unexpectedSuccesses': 0,
			'successes': 1
		},
		'time': {
			'start_at': 1587633035.552573,
			'duration': 0.04336047172546387
		},

**Comment by debugtalk** [comment]
@Jayzhang1995 建议升级到 v3 版本；相应文档会在近一周内更新。
