### ISSUE TITLE
最新的版本已经是3.0+，想问一下3.0对于2.0有更大的变更吗？

### ISSUE THREAD

**Issue by xhuihui** [httprunner/httprunner#886]
- 想了解3.0对比2.0是否有了比较大的变更？
      -  最近再看3.0源码，感觉里面解析的时候有一些2.0文档中没有提到的yaml字段，想知道是遗留，还是3.0做了新版升级。

**Comment by debugtalk** [comment]
@xhuihui 是的，基本上重写了。详见 changelog
https://github.com/httprunner/httprunner/blob/master/docs/CHANGELOG.md
