### ISSUE TITLE
安装完成后输入hrun -V，提示无效命令，hrun: error: unrecognized arguments: -V

### ISSUE THREAD

**Issue by liu-mang** [httprunner/httprunner#887]
## 问题描述
python 3.8.0 环境，输入pip install httprunner,安装完成，提示成功；过程如下：
C:\Users\我是你标哥>pip install httprunner
Collecting httprunner
  Using cached https://files.pythonhosted.org/packages/c9/cb/47ad33ed6b232def7aebfcc73b39340aacf8c40de6608dc47886c6479dc1/httprunner-3.0.1.2-py3-none-any.whl
Requirement already satisfied: loguru<0.5.0,>=0.4.1 in c:\python\lib\site-packages (from httprunner) (0.4.1)
Requirement already satisfied: requests<3.0.0,>=2.22.0 in c:\python\lib\site-packages (from httprunner) (2.23.0)
Requirement already satisfied: jsonpath<0.83,>=0.82 in c:\python\lib\site-packages (from httprunner) (0.82)
Requirement already satisfied: jinja2<3.0.0,>=2.10.3 in c:\python\lib\site-packages (from httprunner) (2.11.2)
Requirement already satisfied: requests-toolbelt<0.10.0,>=0.9.1 in c:\python\lib\site-packages (from httprunner) (0.9.1)
Requirement already satisfied: filetype<2.0.0,>=1.0.5 in c:\python\lib\site-packages (from httprunner) (1.0.6)
Requirement already satisfied: pydantic<2.0,>=1.4 in c:\python\lib\site-packages (from httprunner) (1.5.1)
Requirement already satisfied: pyyaml<6.0.0,>=5.1.2 in c:\python\lib\site-packages (from httprunner) (5.3.1)
Requirement already satisfied: win32-setctime>=1.0.0; sys_platform == "win32" in c:\python\lib\site-packages (from loguru<0.5.0,>=0.4.1->httprunner) (1.0.1)
Requirement already satisfied: colorama>=0.3.4; sys_platform == "win32" in c:\python\lib\site-packages (from loguru<0.5.0,>=0.4.1->httprunner) (0.4.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests<3.0.0,>=2.22.0->httprunner) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python\lib\site-packages (from requests<3.0.0,>=2.22.0->httprunner) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python\lib\site-packages (from requests<3.0.0,>=2.22.0->httprunner) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\python\lib\site-packages (from requests<3.0.0,>=2.22.0->httprunner) (2.9)
Requirement already satisfied: MarkupSafe>=0.23 in c:\python\lib\site-packages (from jinja2<3.0.0,>=2.10.3->httprunner) (1.1.1)
Installing collected packages: httprunner
Successfully installed httprunner-3.0.1.2

请对遇到的 bug 进行简要描述。

输入hrun -V，提示无效命令，如下：
C:\Users\我是你标哥>hrun -V
usage: hrun [-h] [-V] {run,startproject,har2case,locusts} ...
hrun: error: unrecognized arguments: -V
## 版本信息
httprunner-3.0.1.2
请提供如下版本信息：

 - 操作系统类型: [ Windows 10 ,64位]
 - Python 版本 [3.8.0]
 - HttpRunner 版本 [httprunner-3.0.1.2]
 - **设备 ID**: [戴尔电脑台式机]

获取方式：

在 Python 交互式 shell 中输入如下命令进行获取：

```bash
>>> import uuid; print(uuid.getnode())
190070690681122
```

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd
/Users/debugtalk/MyProjects/HttpRunner-dev/httprunner/tests
$ hrun testcases/setup.yml
INFO     Loading environment variables from /Users/debugtalk/MyProjects/HttpRunner-dev/HttpRunner/tests/.env
ERROR    !!!!!!!!!! exception stage: load tests !!!!!!!!!!
ModuleNotFoundError: No module named 'tests.api_server'
```

**Comment by wangchunshen** [comment]
我也遇到了同样的问题

**Comment by he183137** [comment]
新版本在cli.py 有个方法，在执行前追加了一个run的参数，我把insert那行注掉就ok。
使用startproject 等非run的参数也会存在问题，都是因为run这个参数造成。
`def main_hrun_alias():
    """ command alias
        hrun = httprunner run
    """
    sys.argv.insert(1, "run")
    main()
`

**Comment by debugtalk** [comment]
感谢反馈，已修复。
