### ISSUE TITLE
配置本地中文手册遇到问题

### ISSUE THREAD

**Issue by LodonWu** [httprunner/httprunner#889]
按照教程配置了mkdocs，但是不可以启动服务，有个.icons/.svg 不知道是什么意思

PS D:\ALMApi> mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory

.icons/.svg

**Comment by namekkozZ** [comment]
mkdocs-materiald
这个依赖的版本太高了 你换成3.X 的版本应该就可以了

**Comment by LodonWu** [comment]
> mkdocs-materiald
> 这个依赖的版本太高了 你换成3.X 的版本应该就可以了

解决了，非常感谢
