### ISSUE TITLE
request_body里传入的参数只能是json字符串形式，能否传入其他形式

### ISSUE THREAD

**Issue by yanghuo662** [HttpRunner/HttpRunner#89]
我们有个接口只能处理content-type = application/octet-stream的请求，所以在request请求的body里只能传入一个文件的二进制数据流，但是目前框架body只能传str类型

**Comment by yanghuo662** [comment]
已解决

**Comment by debugtalk** [comment]
@yanghuo662 可否将解决方式也分享下，例如将你的用例贴出来，方便后续用户。

**Comment by yanghuo662** [comment]
瞎看了下源码里的单元测试，发现用例在设置request body时使用“data”关键字就可以传bytes类型参数：
    request:
        url: $urls
        method: POST
        verify: false
        headers:
            taskId: $TaskId_uodate
            fileName: ${get_filename_urlencode($file_name)}
            totalPart: '1'
            partSize: '131072'
            partHash: ${get_partHash_sha256($file_path, $partid)}
            partMac: ${get_partMac($file_path, $partid, $Mackey)}
            blockHash: ${get_blockHash_sha256($file_path)}
            partId: $partid
            Content-Type: $Content_Type
        data: ${getFilesdata($file_path)}
