### ISSUE TITLE
生成的报告中，断言模块存在LazyString()

### ISSUE THREAD

**Issue by zhaoguoqing1005** [httprunner/httprunner#892]
## 问题描述

1.api中对响应断言，期望结果使用参数化 $value
2.生成的报告中断言部分的期望结果是 LazyString($value)
## 版本信息

请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本：3.7
 - HttpRunner 版本 :2.5.5
 - **设备 ID**: 143349483114497

## 项目文件内容（非必须）

validate:
  - eq: ["status_code", 200]
  - eq: [content.message, 操作成功]
  - eq: [content.data.minPrice, $minPrice]

**Comment by debugtalk** [comment]
@zhaoguoqing1005 这是 v2 版本惰性运算特性带来的固有缺陷。
在 v3 版本中不再存在该问题。
