### ISSUE TITLE
扩展开发的时候传入标准测试用例结构体的疑问

### ISSUE THREAD

**Issue by namekkozZ** [httprunner/httprunner#893]
## 背景描述

> 使用api中的run方法传入标准的测试用例结构体 需要传入的内容（标准的测试用例结构体）不明确 感觉文档上写的不准确、像是以前的结构 并不适用新版本

## 期望的功能特性

> 期望 文档可以更明确（如果是我理解不对希望指正一下）

**Comment by hazer491** [comment]
你可以参考 https://github.com/httprunner/httprunner/issues/736

**Comment by debugtalk** [comment]
@namekkozZ 文档的确是没有更新。
在 v3 版本中，可以实际查看测试用例的 model 定义。
https://github.com/httprunner/httprunner/blob/master/httprunner/schema.py
