### ISSUE TITLE
什么时候能出3.0的使用文档啊？

### ISSUE THREAD

**Issue by wanwj7575** [httprunner/httprunner#900]
## 背景描述

> 重点描述遇到的问题：在什么场景下，HttpRunner 当前的功能特性不能（很好地）实现需求。

## 期望的功能特性

> 期望 HttpRunner 实现怎样的功能特性。

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。

**Comment by debugtalk** [comment]
http://docs.httprunner.org/

**Comment by xhuihui** [comment]
2.0的文档能否保留，如果是一个小白，看一下3.0 比2.0的文档上手难度大了很多啊

**Comment by debugtalk** [comment]
https://github.com/httprunner/docs
