### ISSUE TITLE
httprunner执行报错ERROR: test_0000_000 (httprunner.api.TestSequense)

### ISSUE THREAD

**Issue by guodh1** [httprunner/httprunner#906]
我是用httprunner实现的接口自动化平台，yml文件已经生成，进入docker容器直接使用hrun可以正常运行，但是通过调用runner.run(testcase_dir_path)方法确一直报错，用例路径传的没有问题，版本是2.5.7
![image](https://user-images.githubusercontent.com/53330101/82719028-684e0000-9cd9-11ea-9570-e1c0ea52e85d.png)
直接调用hrun却可以
![image](https://user-images.githubusercontent.com/53330101/82719049-a6e3ba80-9cd9-11ea-8a4a-135cbafe7d4b.png)

**Comment by debugtalk** [comment]
@guodh1 你的截图中没有堆栈，看不出问题。
建议升级到 v3 最新版本再试下。
