### ISSUE TITLE
使用jsonpath一直报错

### ISSUE THREAD

**Issue by pengdaan** [httprunner/httprunner#908]
## 问题描述
在httprunner使用jsonpath一直报错。parsed_body 属性找不到

请对遇到的 bug 进行简要描述。
Traceback (most recent call last):↵AttributeError: 'Response' object has no attribute 'parsed_body'↵↵During handling of the above exception, another exception occurred:↵↵Traceback (most recent call last):↵httprunner.exceptions.ParamsError: ResponseObject does not have attribute: parsed_body

## 版本信息
2.5.4
请提供如下版本信息：

 - 操作系统类型: macos
 - Python 版本  3.7
 - HttpRunner 版本 2.5.4

获取方式：

作者你好，我在把jmeter的脚本迁移到httprunner的过程中，使用了jsonpath。
我的接口返回结果如下：
  {
        "isSuccess": true, 
        "responseCode": 0, 
        "responseMsg": "\u8bf7\u6c42\u6210\u529f", 
        "token": "f5ff36cab6cfaedb455dcc3a191a4d10", 
        "applyTime": 0
      }
使用jsonPath提取token :$.token

每次运行报错:
"msg": "Traceback (most recent call last):\nAttributeError: 'Response' object has no attribute 'parsed_body'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\nhttprunner.exceptions.ParamsError: ResponseObject does not have attribute: parsed_body\n"
  
后续，我对框架内的response.py 进行了修改：
![image](https://user-images.githubusercontent.com/13775385/82859307-f4b22a00-9f48-11ea-8122-944e8e2e3c53.png)
报错停止了。

本人技术有限，不知道修改是否妥当，还请指导。

**Comment by debugtalk** [comment]
@pengdaan httprunner 支持的是 jmespath 的语法；另外请尽快升级到 v3 版本。
https://jmespath.org/
