### ISSUE TITLE
3.06版本执行用例后无法生成测试报告？

### ISSUE THREAD

**Issue by canhingbo** [httprunner/httprunner#911]
## 问题描述

安装了3.06版本，startproject 创建了一个文件模板。
模板的文件夹少了一个testsuits。 执行testcases里面的例子成功后，无法在reports文件夹生成测试报告。

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows10]
 - Python 版本 [e.g. 3.7.1]
 - HttpRunner 版本 [e.g. 3.06]

**Comment by debugtalk** [comment]
@canhingbo 默认不生成 html 报告，你可以结合 pytest-html 或 allure 插件来生成报告。使用方法参考 pytest
