### ISSUE TITLE
POST传入参数格式校验，类型检查错误，期望是JSON，而不是DICT

### ISSUE THREAD

**Issue by webyabo** [httprunner/httprunner#913]
## 问题描述
POST接口，josn参数非JOSN时类型检查错误。 
同时使用requests，传入次参数请求成功，b'[{"mediaLeadsId": "204240986", "mediaType": "1"}]'

    "json": [
          {
            "mediaLeadsId": "xxx",
            "mediaType": "xxx",
          }
        ]

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [Windows]
 - Python 版本 [3.7]
 - HttpRunner 版本 [3.0.6]

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

2020-06-02 12:54:32.134 | ERROR    | httprunner.loader:load_testcase:83 - TestCase ValidationError:
file: D:\PycharmProjects\dealerqa_newteam_api_test\test.json
error: 1 validation error for TestCase
teststeps -> 1 -> request -> json
  value is not a valid dict (type=type_error.dict)

```

**Comment by webyabo** [comment]
#req_json: Dict = Field({}, alias="json")
    req_json: Any = Field(Any, alias="json")
临时解决了，希望能根本解决

**Comment by debugtalk** [comment]
@webyabo 感谢反馈，已增加 List 类型的兼容。

req_json: Union[Dict, List] = Field({}, alias="json")
