### ISSUE TITLE
断言"headers.Content-Type"时报错，与jmespath语法规则有关

### ISSUE THREAD

**Issue by BenjaminYing** [httprunner/httprunner#915]
## 问题描述

断言"headers.Content-Type"时，报错：Bad jmespath expression: Unknown token '-'。

## 版本信息
 - 操作系统类型: [Linux]
 - Python 版本 [e.g. 3.6]
 - HttpRunner 版本 [e.g. 3.0.5]

## 运行命令 && 堆栈信息
```bash
$ hrun docs/data/xxx.json
INFO     httprunner/response.py:173: in validate
    check_value = jmespath.search(check_item, self.resp_obj_meta)
ERROR    Bad jmespath expression: Unknown token '-':
```
##原因
jmespath.search的key中若有特殊符号，该项需要用引号引起

##参考
http://jmespath.org/specification.html#examples

正确用法应为：'headers."Content-Type"'

**Comment by debugtalk** [comment]
@BenjaminYing 这个问题在 3.0.6+ 已修复。

**Comment by jameshuang-i** [comment]
我用的是3.1.4版本，还有这个问题@

**Comment by jameshuang-i** [comment]
@debugtalk
