### ISSUE TITLE
type_match expect type 认为是str

### ISSUE THREAD

**Issue by Photooo** [HttpRunner/HttpRunner#92]
- type_match: ["content", 'list']

得到的： expected value: list (str).

version： HttpRunner version: 0.8.8
                PyUnitReport version: 0.1.4

**Comment by debugtalk** [comment]
@Photooo 之前有修复过`type_match`的bug，#84

你能将你遇到的问题再描述详细点么？

**Comment by Photooo** [comment]
@debugtalk 
httprunner.exception.ValidationError:
        check item name: content;
        check item value: [] (list);
        comparator: type_match;
        expected value: list (str).

test.yml 里是
validate:
        - eq: ["status_code", 200]
        - type_match: ["content", list]
