### ISSUE TITLE
大佬，locust功能什么时候回归，是基于什么原因暂时下架了locust功能？

### ISSUE THREAD

**Issue by zcyuefan** [httprunner/httprunner#920]
## 背景描述

> 重点描述遇到的问题：在什么场景下，HttpRunner 当前的功能特性不能（很好地）实现需求。

大佬，如题，谢谢

**Comment by debugtalk** [comment]
HttpRunner V3 进行了重写，暂时去除了 locust，后续会再添加回来。

**Comment by debugtalk** [comment]
@zcyuefan 在 3.1.0 版本中已重新集成 locust。
