### ISSUE TITLE
v3版本variable，base_url，verify自上而下override的功能以及参数化的功能现在好像都没有了

### ISSUE THREAD

**Issue by zcyuefan** [httprunner/httprunner#928]
## 背景描述

> 重点描述遇到的问题：这些功能都是v2有的

## 期望的功能特性

> 建议增加这些特性

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。

**Comment by debugtalk** [comment]
change: override variables
    (1) testcase: session variables > step variables > config variables
    (2) testsuite: testcase variables > config variables
    (3) testsuite testcase variables > testcase config variables

**Comment by debugtalk** [comment]
已经支持了
