### ISSUE TITLE
基于 pytest.maker.parametrise 实现参数化数据驱动

### ISSUE THREAD

**Issue by master-walker** [httprunner/httprunner#929]
## 背景描述

> 重点描述遇到的问题：
比如以下的参数化不支持了吗？？
...
variables:
      name: ['12321', '12321']
      password: ${get_pwd()} #返回多个数据
      name-pwd: ${P(examples/data.csv)}

## 期望的功能特性

> 期望 HttpRunner 实现怎样的功能特性。
不同数据驱动同一个接口，实现不同用例

## 示例描述（可选）

> 结合示例进行描述，可让开发者更准确理解你的需求。

**Comment by zcyuefan** [comment]
这个功能不是很难，结合pytest已有的参数化功能实现。思路如下：重写一下make.py相关内容，在testcase模板中增加如下内容
import pytest

@pytest.maker.parametrise（你的参数列表，参数值列表）：
def test_start（）：
      self.__config.variables…更新对应的key
      super（）.test_start（）

在讲2.x版本中parser.py parse_parameters（）方法适当改造即可

**Comment by debugtalk** [comment]
@master-walker v3.x 版本重写了，parameters 功能暂时还没有添加；后续会结合 pytest 的 pytest.maker.parametrise 机制来实现。

**Comment by debugtalk** [comment]
@zcyuefan 基本会按照该思路。你有兴趣的话可以提交个 PR 么？

**Comment by zcyuefan** [comment]
> @zcyuefan 基本会按照该思路。你有兴趣的话可以提交个 PR 么？

**Comment by debugtalk** [comment]
see #1153
