### ISSUE TITLE
httprunner的文档更新程度远远落后于已经实现的功能，文档说明中缺少严格的版本说明

### ISSUE THREAD

**Issue by dy20082250** [httprunner/httprunner#930]
1 文档中未说明哪些示例适用于哪个版本，示例未经过严格的版本测试

2 httprunner应用于复杂环境缺少对应的示例，目前已有的示例的组织和场景相对简单

3 文档说明与功能实现存在不一致的地方

**Comment by ouchengogo** [comment]
不仅是httprunner，其他的开源工具大部分也是文档版本之后很严重，哎

**Comment by debugtalk** [comment]
文档：https://httprunner.com/docs
