### ISSUE TITLE
最新版本的paramters关键字不能正常工作，定义了paramters后依然报错，提示变量未定义

### ISSUE THREAD

**Issue by dy20082250** [httprunner/httprunner#931]
测试使用的是httprunner最新版本
使用paramters的方式是按照2.x版本的方式，或许是httprunner版本的paramters使用方式改动了？

**Comment by debugtalk** [comment]
@dy20082250 parameters 机制在 v3.x 中还没有添加。

**Comment by dy20082250** [comment]
@debugtalk 明白了，我使用的时候pip默认下载的最新版本，然后我按照旧版本的doc去测试，parameters真是让我纠结了一上午，各种尝试都不成功。。。

**Comment by WandyYing** [comment]
parameters 机制我已经在测试了。通过的话会提一个PR
