### ISSUE TITLE
debugtalk内的函数传入列表或字典参数后不能正常使用

### ISSUE THREAD

**Issue by lcwsy** [httprunner/httprunner#933]
## 问题描述
使用函数传参有时会用到列表或字典作为参数输入，以满足更灵活的数据输入。
debugtalk内定义函数后，在teststep内调用，并传入列表和字典等其他参数，运行用例时没有识别该函数，将列表和字段的参数去掉后，就可以正常识别，上面的使用方法没有和python函数使用方法保持一致

## 版本信息
请提供如下版本信息：
 - 操作系统类型: [Windows]
 - Python 版本 [3.6.5]
 - HttpRunner 版本 [3.0.1]

## 项目文件内容（非必须）
下面是teststeps：
`-`
    `name: 创建shell节点工作流`
    `api: api/项目/工作流定义/创建工作流.yml`
    `variables:`
        `project_name: $project_name`
       `tasks: ${get_tasks([$node_type],{$node_id:$node_name},[["date"]])}`
       ` locations: ${get_locations($node_id=$node_name)}`
        `connects: ${get_connects($node_id)}`
        `flow_name: $flow_name`
    `validate:`
      `- eq: [content.msg, success]`

下面是debugtalk的对应函数get_tasks:
`def get_tasks(node_type,node_id_name,parameters):`
    `task = tasks.Commonparameter(node_type,node_id_name,parameters)`
    `return task.get_node_tasks()`

python测试使用该方法传入列表和字典可以正常识别运行.

## 测试结果
get_tasks函数在request内的没有被识别
{
  "processData": {
    "globalParams": [],
    `"tasks": "${get_tasks([$node_type],{$node_id:$node_name},[[\"date\"]])}",`
    "timeout": 0
  },
  "locations": {
    "tasks-shell": {
      "name": "shell_node",
      "targetarr": "",
      "x": 100,
      "y": 100
    }
  },
  "connects": [],
  "name": "Shell7095f498641d468d976464772bb249c7",
  "desc": "测试"
}

**Comment by debugtalk** [comment]
@lcwsy 当前解析 function 的时候是基于正则匹配；函数参数不支持 [], {} 符号。
如果你需要传入这类复杂结构体的参数，那么可以先设置个变量，在函数引用时参数引用变量即可。

**Comment by lcwsy** [comment]
谢谢指点，解决了我的问题。
