### ISSUE TITLE
httprunner3版本还有api,testcase,testsuit这样的分层概念吗，  脚手架生成的项目只有testcase目录，har2case生成的文件也是testcase的。

### ISSUE THREAD

**Issue by liuchang6** [httprunner/httprunner#938]
您好：
    我在testerhome上看到了您的框架，这几天试用了下，感觉非常棒，想请教下几个问题：

- httprunner3版本还有api,testcase,testsuit这样的分层概念吗?  脚手架生成的项目只有testcase目录，har2case生成的文件也是testcase的。

- httprunner3为什么要使用FASTAPI的框架，为什么要重构；新版本里面make转换py脚本有什么好处；还有什么新特性。

**Comment by debugtalk** [comment]
@liuchang6 
1、在 v3 版本中，去除了 API 的概念，目的是将概念进行了一些简化；但用例分层机制还是有的：
![image](https://user-images.githubusercontent.com/3657070/85218985-6ce9ff00-b3d2-11ea-82a4-c4b102e44eba.png)

2、并没有太多的是会用 fastapi；而是内置使用了 pydantic models 来定义用例的格式；生成 pytest 脚本的好处是减少框架复杂度，将具体执行交给 pytest；而且同时可以使用到 pytest 的海量生态插件，例如 allure-pytest 等。
