### ISSUE TITLE
3.1.2的版本 hrun login.yml 执行成功但是没有生成测试报告

### ISSUE THREAD

**Issue by victorm315** [httprunner/httprunner#953]
## 问题描述

3.1.2的版本 hrun login.yml 执行成功但是没有生成测试报告

## 版本信息

请提供如下版本信息：

 - 操作系统类型: [macos]
 - Python 版本 [3.7.7]
 - HttpRunner 版本 [3.1.2]
 - **设备 ID**: [268678282199869]

## 项目文件内容（非必须）

如果可能，提供项目测试用例文件原始内容可加快 bug 定位和修复速度。

提示：请注意在去除项目敏感信息（IP、账号密码、密钥等）后再进行上传。
![image](https://user-images.githubusercontent.com/16413574/86534749-719fce80-bf0d-11ea-8ec9-96d42a11f791.png)

## 运行命令 && 堆栈信息

请提供在命令行中运行测试时所在的目录和命令，以及报错时的详细堆栈内容。

```bash
$ pwd
/Users/qiaoersun/Documents/taoche/CodeTaoChe/httprunnerDemo/testcases
$  hrun login.yml 

login_test.py .                                                                                                                                                        [100%]
```

**Comment by WandyYing** [comment]
@victorm315 请参考该链接: https://docs.httprunner.org/user/testing_report/
