### ISSUE TITLE
能否支持类似unittest中的skip注解，方便灵活剔除某些用例，不执行。

### ISSUE THREAD

**Issue by TommyXie1990** [HttpRunner/HttpRunner#96]
背景：
目前在接口测试日常构建中，会遇到一些接口开发暂时屏蔽了或者降级，导致用例执行失败；所以想当遇到这些情况的时候，能够临时剔除掉某些用例不执行；等后续恢复后，再去掉，然后恢复执行。

**Comment by debugtalk** [comment]
新增支持`skip`参数：

1、指定`skip`为`True`时，相当于指定`times`为0，当前`test`将不运行；
2、`skip`参数的优先级高于`times`，当同时指定`skip`为`True`，并且`times`为非零值时，当前`test`仍将不运行。

**Comment by debugtalk** [comment]
已经对`skip`机制进行重构：

1、支持`skip`关键字，指定的内容不再是boolean值，而是skip的原因；
2、支持`skipIf`关键字，支持指定`${func()}`形式的函数表达式，并根据表达式的运算结果来判断是否skip当前测试；该函数同样定义在`debugtalk.py`的函数中。

e.g.

测试案例：https://github.com/HttpRunner/HttpRunner/blob/master/tests/data/demo_testset_cli.yml

对应的测试报告形式：

![image](https://user-images.githubusercontent.com/3657070/35961851-16dfb32a-0cea-11e8-89f0-6a3b9fb12e6e.png)
