### ISSUE TITLE
{{}}引用变量

### ISSUE THREAD

**Issue by guhan121** [httprunner/httprunner#974]
## 背景描述
目前测试是在postman上测试，有很多变量，在postman上面使用的{{var}}替换，并且请求的数据里面包含$

## 期望的功能特性

> 不要用$var来替换变量，使用{{}}

**Comment by debugtalk** [comment]
@guhan121 这个变动的影响会很大，而且使用 $var ${var} 也能满足要求；如果数据里面包含了 $ ，那么可以使用 $$ 来 escape。

**Comment by guhan121** [comment]
@debugtalk  很大么;我就改了 parse_string_variables extract_variables 函数，然后好像可以用了 
就是注释什么都没改

**Comment by guhan121** [comment]
@debugtalk $$转$$是在哪个函数中定义的 我去看一下
